// Generated by GitHub Copilot
export interface HealthStatus {
  service: "desktop" | "provider" | "audio" | "screenshot";
  status: "ok" | "warning" | "error";
  timestampIso: string;
}

export * from "./ipc";
