// Generated by GitHub Copilot

import type {
  ConsentAuditListResponse,
  ConsentTextResponse,
  ContextProfileDeleteRequest,
  ContextProfileDuplicateRequest,
  ContextProfileSaveRequest,
  ContextProfilesListResponse,
  MeetingActiveAlertEvent,
  MeetingActiveDismissRequest,
  MeetingActiveDismissResponse,
  MeetingMidSummaryEvent,
  MeetingMidSummaryResponse,
  MeetingPrefs,
  MeetingSessionCancelResponse,
  MeetingSessionCompletedEvent,
  MeetingSessionStartRequest,
  MeetingSessionStartResponse,
  MeetingSessionStatusEvent,
  MeetingSessionStopResponse,
  MeetingTemplatesListResponse,
  MeetingTranscriptBookmarkEvent,
  MeetingTranscriptDeltaEvent,
  RetentionPurgeRunResponse,
  TeamMemoryListResponse,
  TeamMemoryUpdateRequest,
  TokenUsageDailyResponse,
  TokenUsageThresholdEvent
} from "./meeting";
import type {
  TranslationLineEvent,
  TranslationPrefs,
  TranslationSessionStartRequest,
  TranslationSessionStartResponse,
  TranslationSessionStatusResponse,
  TranslationSessionStopResponse
} from "./translation";
import type {
  LlmProviderTestRequest,
  LlmProviderTestResponse,
  LlmSettingsPublic,
  TokenUsageSessionResponse
} from "./llm";

export type {
  ContextProfileSaveRequest,
  ContextProfilesListResponse,
  MeetingSessionCancelResponse,
  MeetingSessionCompletedEvent,
  MeetingSessionStartRequest,
  MeetingSessionStartResponse,
  MeetingSessionStatusEvent,
  MeetingSessionStopResponse,
  MeetingTranscriptDeltaEvent,
  MeetingActiveAlertEvent,
  MeetingActiveDismissRequest,
  MeetingActiveDismissResponse,
  MeetingPrefs,
  TeamMemoryListResponse,
  TranslationLineEvent,
  TranslationPrefs,
  TranslationSessionStatusResponse,
  TranslationSessionStartRequest,
  TranslationSessionStartResponse,
  TranslationSessionStopResponse,
  LlmProviderTestRequest,
  LlmProviderTestResponse,
  LlmSettingsPublic,
  TokenUsageSessionResponse
};

/**
 * Canais IPC permitidos entre renderer e main process.
 */
export const IPC_CHANNELS = {
  desktopPing: "desktop:ping",
  screenshotCapture: "screenshot:capture",
  screenshotQueueGet: "screenshot:queue:get",
  screenshotQueueClear: "screenshot:queue:clear",
  screenshotDisplaysList: "screenshot:displays:list",
  screenshotCaptureSave: "screenshot:capture:save",
  screenshotQueueUpdated: "screenshot:queue-updated",
  screenshotQuickAnalyze: "screenshot:quick-analyze",
  stealthStateChanged: "stealth:state-changed",
  chatAsk: "chat:ask",
  chatStreamEvent: "chat:stream-event",
  promptPresetsGet: "prompt:presets:get",
  audioTranscribe: "audio:transcribe",
  stealthSetMode: "stealth:set-mode",
  settingsGet: "settings:get",
  settingsSave: "settings:save",
  settingsReset: "settings:reset",
  diagnosticsGet: "diagnostics:get",
  diagnosticsSetLogLevel: "diagnostics:set-log-level",
  featureFlagsGet: "feature-flags:get",
  featureFlagsSave: "feature-flags:save",
  featureFlagsReset: "feature-flags:reset",
  envGet: "env:get",
  autoUpdateGetState: "auto-update:get-state",
  autoUpdateSaveConfig: "auto-update:save-config",
  autoUpdateCheck: "auto-update:check",
  autoUpdateDownload: "auto-update:download",
  autoUpdateInstall: "auto-update:install",
  autoUpdateRollback: "auto-update:rollback",
  autoUpdateConfirmHealth: "auto-update:confirm-health",
  autoUpdateEvent: "auto-update:event",
  llmSettingsGet: "llm:settings:get",
  llmSettingsSave: "llm:settings:save",
  llmProviderTest: "llm:providers:test",
  meetingSessionStart: "meeting:session:start",
  meetingSessionStop: "meeting:session:stop",
  meetingSessionCancel: "meeting:session:cancel",
  meetingSessionStatus: "meeting:session:status",
  meetingSessionCompleted: "meeting:session:completed",
  meetingTranscriptAppend: "meeting:transcript:append",
  meetingTranscriptDelta: "meeting:transcript:delta",
  meetingActiveAlert: "meeting:active:alert",
  meetingActiveDismiss: "meeting:active:dismiss",
  contextTeamMemoryList: "context:team-memory:list",
  contextTeamMemoryDelete: "context:team-memory:delete",
  usageTokensSession: "usage:tokens:session",
  contextProfilesList: "context:profiles:list",
  contextProfileSave: "context:profiles:save",
  translationSessionStart: "translation:session:start",
  translationSessionStop: "translation:session:stop",
  translationSessionStatus: "translation:session:status",
  translationChunkIngest: "translation:chunk:ingest",
  translationLine: "translation:line",
  translationError: "translation:error"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export interface DesktopPingRequest {
  timestampIso?: string;
}

export interface DesktopPingResponse {
  ok: true;
  timestampIso: string;
}

export interface ScreenshotCaptureRequest {
  source: "full" | "region";
}

export interface ScreenshotCaptureResponse {
  captureId: string;
  imagePath: string;
  createdAtIso: string;
  source: "full" | "region";
  trigger: "manual" | "shortcut";
  previewDataUrl: string;
}

export interface ScreenshotQueueItem extends ScreenshotCaptureResponse {}

export interface ScreenshotQueueGetResponse {
  items: ScreenshotQueueItem[];
}

export interface ScreenshotQueueClearResponse {
  items: ScreenshotQueueItem[];
  clearedAtIso: string;
}

export interface ScreenshotQueueUpdatedEvent {
  items: ScreenshotQueueItem[];
}

export type ScreenCaptureMode = "primary" | "all_displays" | "specific_display";

export interface ScreenCaptureSettings {
  mode: ScreenCaptureMode;
  displayId?: string;
}

export interface DisplayInfo {
  id: string;
  label: string;
  bounds: { x: number; y: number; width: number; height: number };
  size: { width: number; height: number };
  scaleFactor: number;
  isPrimary: boolean;
}

export interface ScreenshotDisplaysListResponse {
  displays: DisplayInfo[];
}

export interface ScreenshotQuickAnalyzeEvent {
  captureId: string;
  previewDataUrl: string;
  captureIds?: string[];
  previewDataUrls?: string[];
}

export interface ChatAskRequest {
  sessionId: string;
  ask: string;
  screenshotIds?: string[];
  audioIds?: string[];
  presetId?: string;
}

export interface AudioAddRequest {
  audioBase64: string;
  mimeType: string;
  durationSeconds: number;
}

export interface AudioAddResponse {
  audioId: string;
  durationSeconds: number;
  createdAtIso: string;
}

export interface AudioRemoveRequest {
  audioId: string;
}

export interface ChatAskResponse {
  requestId: string;
  status: "accepted";
}

export interface ChatStreamEvent {
  requestId: string;
  status: "started" | "chunk" | "completed" | "error";
  deltaText?: string;
  fullText?: string;
  errorMessage?: string;
  errorCode?:
    | "LOCAL_PROVIDER_UNAVAILABLE"
    | "LOCAL_ONLY_PRIVACY_MODE_ACTIVE"
    | "MISSING_API_KEY"
    | "PROMPT_GUARDRAIL_BLOCKED"
    | "AUTH_INVALID_API_KEY"
    | "RATE_LIMIT"
    | "NETWORK"
    | "TIMEOUT"
    | "SERVER"
    | "UNKNOWN";
  actionableMessage?: string;
  retryable?: boolean;
  createdAtIso: string;
}

export interface PromptPreset {
  id: string;
  title: string;
  description: string;
}

export interface PromptPresetsGetResponse {
  presets: PromptPreset[];
}

export interface AudioTranscribeRequest {
  sessionId: string;
  chunkBase64: string;
  language?: string;
}

export interface AudioTranscribeResponse {
  text: string;
  isFinal: boolean;
}

export interface StealthSetModeRequest {
  enabled: boolean;
}

export interface StealthSetModeResponse {
  enabled: boolean;
  fullStealth?: boolean;
  opacity: number;
  appliedAtIso: string;
}

export interface StealthStateChangedEvent {
  enabled: boolean;
  fullStealth?: boolean;
  hardening: StealthHardening;
  opacity: number;
  source: "ipc" | "shortcut";
  appliedAtIso: string;
}

export interface ShortcutPushToTalkEvent {
  triggeredAtIso: string;
}

export interface AppSettings {
  language: string;
  /** Quando true, a janela usa perfil normal (sem stealth). Padrão: false (stealth ativo). */
  nonStealthModeEnabled: boolean;
  /** Linguagem padrão para soluções de código (ex.: java). */
  defaultCodeLanguage: string;
  selectedAudioInputDeviceId?: string;
  selectedAudioInputDeviceLabel?: string;
  shortcuts: {
    captureScreen: string;
    pushToTalk: string;
    toggleFullStealth: string;
  };
  hasGeminiApiKey: boolean;
  llm?: LlmSettingsPublic;
  audioCapture?: {
    mode: string;
    deviceId?: string;
    sampleRate?: number;
    channelCount?: number;
    preRollValidationSeconds?: number;
    /** Persistir chunks de áudio de reunião/tradução em disco */
    saveRecordings?: boolean;
    /** Pasta efetiva (custom ou padrão da app) */
    recordingsPath?: string;
    /** Caminho padrão em userData/meeting-recordings */
    defaultRecordingsPath?: string;
  };
  screenCapture?: ScreenCaptureSettings;
  transcriptionPacks?: {
    installedLanguageIds: string[];
    preferredModelTier: "base" | "small" | "medium";
  };
  meetingPrefs?: MeetingPrefs;
  translationPrefs?: TranslationPrefs;
}

export type TranscriptionPackStatus = "missing" | "downloading" | "ready" | "needs_engine" | "error";

export interface TranscriptionLanguagePack {
  id: string;
  label: string;
  languageCode: string;
  required: boolean;
  description: string;
  installed: boolean;
  status: TranscriptionPackStatus;
  busy?: boolean;
}

export interface TranscriptionPacksListResponse {
  packs: TranscriptionLanguagePack[];
  modelTiers: {
    id: string;
    label: string;
    modelKey: string;
    description: string;
    approximateSizeMb: number;
    installed?: boolean;
    active?: boolean;
    filePath?: string;
  }[];
  preferredModelTier: "base" | "small" | "medium";
  engine: {
    modelReady: boolean;
    binaryReady: boolean;
    fullyReady?: boolean;
    modelPath?: string;
    binaryPath?: string;
    downloadPercent?: number | null;
    busyPackId?: string;
    lastError?: string;
    whisperState?: string;
    lastModelError?: string;
    preferredModelKey?: string;
  };
  requiredReady: boolean;
  requiredInstalled: boolean;
  requiredLanguageIds: string[];
}

export interface SetupChecklistItem {
  id: string;
  tab: string;
  title: string;
  description: string;
  severity: "required" | "recommended" | "optional";
  ready: boolean;
  actionLabel: string;
}

export interface SetupChecklistResponse {
  items: SetupChecklistItem[];
  pending: SetupChecklistItem[];
  pendingRequired: SetupChecklistItem[];
  readyCount: number;
  totalCount: number;
  allRequiredReady: boolean;
  byTab: Record<string, SetupChecklistItem[]>;
}

export interface TranscriptionPacksProgressEvent {
  kind: string;
  status?: string;
  packId?: string;
  modelKey?: string;
  message?: string;
  percent?: number | null;
  emittedAtIso?: string;
}

export interface FfmpegStatusResponse {
  available: boolean;
  path: string;
  managedPath: string;
  installState: "idle" | "downloading" | "extracting" | "ready" | "failed";
  lastError: string;
  lastInstalledAtIso: string;
  platformSupported: boolean;
  downloadUrl?: string;
  progressPercent?: number | null;
  progressMessage?: string;
}

export interface FfmpegInstallProgressEvent {
  installState: FfmpegStatusResponse["installState"];
  percent?: number | null;
  message?: string;
  lastError?: string;
  emittedAtIso?: string;
}

export interface AudioCaptureLevelEvent {
  capturing: boolean;
  source?: string;
  mode?: string;
  label?: string;
  deviceId?: string;
  dbFs?: number;
  peakDbFs?: number;
  rms?: number;
  error?: string;
  meterSource?: string;
  emittedAtIso?: string;
}

export type AutoUpdateChannel = "stable" | "beta";

export interface AutoUpdateConfig {
  enabled: boolean;
  feedUrl?: string;
  channel: AutoUpdateChannel;
  allowPrerelease: boolean;
}

export type AutoUpdateStatus =
  | "disabled"
  | "idle"
  | "checking"
  | "update-available"
  | "downloading"
  | "downloaded"
  | "up-to-date"
  | "rollback-ready"
  | "unavailable"
  | "error";

export interface AutoUpdateState {
  config: AutoUpdateConfig;
  status: AutoUpdateStatus;
  isPackaged: boolean;
  currentVersion: string;
  availableVersion?: string;
  downloadedVersion?: string;
  rollbackChannel?: AutoUpdateChannel;
  lastCheckedAtIso?: string;
  lastDownloadedAtIso?: string;
  lastError?: string;
  canCheck: boolean;
  canDownload: boolean;
  canInstall: boolean;
  canRollback: boolean;
  requiresHealthConfirmation: boolean;
}

export interface AutoUpdateGetStateResponse {
  state: AutoUpdateState;
}

export interface AutoUpdateSaveConfigRequest {
  enabled?: boolean;
  feedUrl?: string | null;
  channel?: AutoUpdateChannel;
  allowPrerelease?: boolean;
}

export interface AutoUpdateSaveConfigResponse {
  state: AutoUpdateState;
  savedAtIso: string;
}

export interface AutoUpdateCheckResponse {
  state: AutoUpdateState;
  checkedAtIso: string;
}

export interface AutoUpdateDownloadResponse {
  state: AutoUpdateState;
  startedAtIso: string;
}

export interface AutoUpdateInstallResponse {
  accepted: boolean;
  appliedAtIso: string;
}

export interface AutoUpdateRollbackRequest {
  channel?: AutoUpdateChannel;
}

export interface AutoUpdateRollbackResponse {
  state: AutoUpdateState;
  acceptedAtIso: string;
}

export interface AutoUpdateConfirmHealthResponse {
  state: AutoUpdateState;
  confirmedAtIso: string;
}

export interface AutoUpdateEvent {
  state: AutoUpdateState;
  kind:
    | "state-changed"
    | "checking"
    | "update-available"
    | "update-not-available"
    | "download-progress"
    | "update-downloaded"
    | "rollback-ready"
    | "error";
  message: string;
  progressPercent?: number;
  emittedAtIso: string;
}

export interface SettingsGetResponse {
  settings: AppSettings;
}

export interface LlmSettingsSaveRequest {
  providers?: Partial<
    Record<
      "gemini" | "openai" | "anthropic",
      {
        enabled?: boolean;
        defaultModelId?: string;
        apiKey?: string | null;
      }
    >
  >;
  routing?: Partial<LlmSettingsPublic["routing"]>;
  tokenBudget?: Partial<LlmSettingsPublic["tokenBudget"]>;
  privacy?: Partial<LlmSettingsPublic["privacy"]>;
}

export interface SettingsSaveRequest {
  language?: string;
  nonStealthModeEnabled?: boolean;
  defaultCodeLanguage?: string;
  selectedAudioInputDeviceId?: string | null;
  selectedAudioInputDeviceLabel?: string | null;
  shortcuts?: {
    captureScreen?: string;
    pushToTalk?: string;
    toggleFullStealth?: string;
  };
  geminiApiKey?: string | null;
  llm?: LlmSettingsSaveRequest;
  screenCapture?: Partial<ScreenCaptureSettings>;
  meetingPrefs?: Partial<MeetingPrefs>;
  translationPrefs?: Partial<TranslationPrefs>;
}

export interface SettingsSaveResponse {
  settings: AppSettings;
  savedAtIso: string;
}

export interface SettingsResetResponse {
  settings: AppSettings;
  resetAtIso: string;
}

export type LogLevel = "debug" | "info" | "warn" | "error";

export interface TranslationErrorEvent {
  sessionId: string;
  code: string;
  message: string;
  emittedAtIso: string;
}

export interface ContentProtectionStatus {
  enabled: boolean;
  platformSupported: boolean;
  protectionLevel: "full" | "partial" | "none";
  platformDetail: string;
  windowCount: number;
  watchdogActive: boolean;
  lastError: string;
}

export interface DiagnosticsGetResponse {
  logLevel: LogLevel;
  logFilePath: string;
  recentLines: string[];
}

export interface DiagnosticsSetLogLevelRequest {
  level: LogLevel;
}

export interface DiagnosticsSetLogLevelResponse {
  logLevel: LogLevel;
  updatedAtIso: string;
}

export type ProviderMode = "cloud" | "local" | "hybrid";
export type StealthHardening = "off" | "safe" | "strict";

export interface FeatureFlags {
  providerMode: ProviderMode;
  localProviderEnabled: boolean;
  forceLocalOnly: boolean;
  stealthHardening: StealthHardening;
}

export interface FeatureFlagsSource {
  providerMode: "persisted" | "env";
  localProviderEnabled: "persisted" | "env";
  forceLocalOnly: "persisted" | "env";
  stealthHardening: "persisted" | "env";
}

export interface FeatureFlagsGetResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
}

export interface FeatureFlagsSaveRequest {
  providerMode?: ProviderMode;
  localProviderEnabled?: boolean;
  forceLocalOnly?: boolean;
  stealthHardening?: StealthHardening;
}

export interface FeatureFlagsSaveResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
  savedAtIso: string;
}

export interface FeatureFlagsResetResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
  resetAtIso: string;
}

export interface EnvironmentSnapshot {
  nodeEnv: string;
  logLevel: string;
  geminiModel?: string;
  providerMode?: ProviderMode;
  localProviderEnabled?: boolean;
  forceLocalOnly?: boolean;
  stealthHardening?: StealthHardening;
  llamaServerPath?: string;
  whisperCliPath?: string;
}

export interface EnvironmentOverride {
  envKey: string;
  label: string;
  field: string;
  value: string;
}

export interface EnvironmentCatalogEntry {
  envKey: string;
  label: string;
  field: string;
  isSet: boolean;
}

export interface EnvGetResponse {
  env: EnvironmentSnapshot;
  overrides: EnvironmentOverride[];
  catalog: EnvironmentCatalogEntry[];
}

/**
 * Contrato tipado da API exposta no preload.
 */
export interface DesktopApi {
  version: string;
  ping(payload: DesktopPingRequest): Promise<DesktopPingResponse>;
  captureScreenshot(payload: ScreenshotCaptureRequest): Promise<ScreenshotCaptureResponse>;
  getScreenshotQueue(): Promise<ScreenshotQueueGetResponse>;
  clearScreenshotQueue(): Promise<ScreenshotQueueClearResponse>;
  listDisplays(): Promise<ScreenshotDisplaysListResponse>;
  saveScreenCapture(payload: Partial<ScreenCaptureSettings>): Promise<{
    screenCapture: ScreenCaptureSettings;
    savedAtIso: string;
  }>;
  getPromptPresets(): Promise<PromptPresetsGetResponse>;
  submitAsk(payload: ChatAskRequest): Promise<ChatAskResponse>;
  onChatStreamEvent(listener: (payload: ChatStreamEvent) => void): () => void;
  addAudio(payload: AudioAddRequest): Promise<AudioAddResponse>;
  removeAudio(payload: AudioRemoveRequest): Promise<{ ok: boolean }>;
  transcribeAudioChunk(payload: AudioTranscribeRequest): Promise<AudioTranscribeResponse>;
  setStealthMode(payload: StealthSetModeRequest): Promise<StealthSetModeResponse>;
  toggleFullStealth(): Promise<StealthSetModeResponse>;
  exitFullStealth(): Promise<{ changed: boolean; enabled: boolean; fullStealth: boolean; appliedAtIso: string }>;
  getContentProtectionStatus(): Promise<ContentProtectionStatus>;
  getSettings(): Promise<SettingsGetResponse>;
  saveSettings(payload: SettingsSaveRequest): Promise<SettingsSaveResponse>;
  resetSettings(): Promise<SettingsResetResponse>;
  getDiagnostics(): Promise<DiagnosticsGetResponse>;
  setLogLevel(payload: DiagnosticsSetLogLevelRequest): Promise<DiagnosticsSetLogLevelResponse>;
  getFeatureFlags(): Promise<FeatureFlagsGetResponse>;
  saveFeatureFlags(payload: FeatureFlagsSaveRequest): Promise<FeatureFlagsSaveResponse>;
  resetFeatureFlags(): Promise<FeatureFlagsResetResponse>;
  getEnvironment(): Promise<EnvGetResponse>;
  getAutoUpdateState(): Promise<AutoUpdateGetStateResponse>;
  saveAutoUpdateConfig(payload: AutoUpdateSaveConfigRequest): Promise<AutoUpdateSaveConfigResponse>;
  checkForAutoUpdate(): Promise<AutoUpdateCheckResponse>;
  downloadAutoUpdate(): Promise<AutoUpdateDownloadResponse>;
  installAutoUpdate(): Promise<AutoUpdateInstallResponse>;
  rollbackAutoUpdate(payload: AutoUpdateRollbackRequest): Promise<AutoUpdateRollbackResponse>;
  confirmAutoUpdateHealth(): Promise<AutoUpdateConfirmHealthResponse>;
  quitApp(): Promise<void>;
  minimizeWindow(): Promise<void>;
  setWindowOpacity(opacity: number): Promise<{ opacity: number }>;
  setWindowLayout(layout: "chat" | "settings" | "expanded"): Promise<{
    layout: "chat" | "settings" | "expanded";
    applied: boolean;
    width?: number;
    height?: number;
  }>;
  onScreenshotQueueUpdated(listener: (payload: ScreenshotQueueUpdatedEvent) => void): () => void;
  onQuickAnalyze(listener: (payload: ScreenshotQuickAnalyzeEvent) => void): () => void;
  onStealthStateChanged(listener: (payload: StealthStateChangedEvent) => void): () => void;
  onPushToTalkShortcut(listener: (payload: ShortcutPushToTalkEvent) => void): () => void;
  onAutoUpdateEvent(listener: (payload: AutoUpdateEvent) => void): () => void;
  getLlmSettings(): Promise<{ llm: LlmSettingsPublic }>;
  saveLlmSettings(payload: LlmSettingsSaveRequest): Promise<{ llm: LlmSettingsPublic; savedAtIso: string }>;
  testLlmProvider(payload: LlmProviderTestRequest): Promise<LlmProviderTestResponse>;
  getTokenUsageSession(sessionId: string): Promise<TokenUsageSessionResponse>;
  getTokenUsageDaily(): Promise<TokenUsageDailyResponse>;
  listMeetingTemplates(): Promise<MeetingTemplatesListResponse>;
  getMeetingConsentText(): Promise<ConsentTextResponse>;
  listConsentAudit(limit?: number): Promise<ConsentAuditListResponse>;
  runRetentionPurge(): Promise<RetentionPurgeRunResponse>;
  startMeetingSession(payload: MeetingSessionStartRequest): Promise<MeetingSessionStartResponse>;
  stopMeetingSession(payload: { sessionId: string }): Promise<MeetingSessionStopResponse>;
  cancelMeetingSession(payload: { sessionId: string }): Promise<MeetingSessionCancelResponse>;
  requestMeetingMidSummary(payload: { sessionId: string }): Promise<MeetingMidSummaryResponse>;
  addMeetingBookmark(payload: { sessionId: string }): Promise<{ ok: boolean }>;
  appendMeetingTranscript(payload: { sessionId: string; text: string }): Promise<{ ok: boolean }>;
  deleteContextProfile(payload: ContextProfileDeleteRequest): Promise<ContextProfilesListResponse>;
  duplicateContextProfile(
    payload: ContextProfileDuplicateRequest
  ): Promise<ContextProfilesListResponse>;
  updateTeamMemoryItem(payload: TeamMemoryUpdateRequest): Promise<TeamMemoryListResponse>;
  listAudioSources(): Promise<{
    modes: string[];
    outputs: { id: string; label: string }[];
    platformSupported?: boolean;
    loopbackProvider?: string;
    error?: string;
    defaultOutputId?: string;
  }>;
  getDesktopLoopbackSource(): Promise<{ id: string; name: string; displayId?: string }>;
  testAudioSource(payload: {
    mode?: string;
    deviceId?: string;
  }): Promise<{ ok: boolean; code: string; message: string }>;
  saveAudioCapture(payload: {
    mode?: string;
    deviceId?: string;
    saveRecordings?: boolean;
    recordingsPath?: string;
  }): Promise<{ audioCapture: AppSettings["audioCapture"]; savedAtIso: string }>;
  getFfmpegStatus(): Promise<FfmpegStatusResponse>;
  installFfmpeg(payload?: { force?: boolean }): Promise<FfmpegStatusResponse>;
  onFfmpegInstallProgress(listener: (payload: FfmpegInstallProgressEvent) => void): () => void;
  onAudioCaptureLevel(listener: (payload: AudioCaptureLevelEvent) => void): () => void;
  reportAudioCaptureLevel(payload: {
    dbFs?: number;
    peakDbFs?: number;
    rms?: number;
  }): Promise<{ ok: boolean }>;
  startAudioCaptureMeter(payload?: {
    mode?: string;
    deviceId?: string;
    source?: string;
    label?: string;
  }): Promise<{ ok: boolean; mode?: string; meterSource?: string }>;
  stopAudioCaptureMeter(): Promise<{ ok: boolean }>;
  getAudioRecordingsDefaults(): Promise<{
    defaultPath: string;
    recordingsPath: string;
    saveRecordings: boolean;
  }>;
  pickAudioRecordingsFolder(): Promise<{ canceled: boolean; path: string }>;
  saveMeetingAudioChunk(payload: {
    sessionId: string;
    chunkBase64: string;
    extension?: string;
    kind?: "meeting" | "translation";
  }): Promise<{ saved: boolean; filePath?: string; dir?: string; reason?: string }>;
  listTranscriptionPacks(): Promise<TranscriptionPacksListResponse>;
  installTranscriptionPack(payload: { packId: string }): Promise<TranscriptionPacksListResponse>;
  uninstallTranscriptionPack(payload: { packId: string }): Promise<TranscriptionPacksListResponse>;
  installRequiredTranscriptionPacks(): Promise<TranscriptionPacksListResponse>;
  setupTranscriptionRuntime(payload?: {
    tier?: "base" | "small" | "medium";
  }): Promise<TranscriptionPacksListResponse>;
  setTranscriptionModelTier(payload: {
    tier: "base" | "small" | "medium";
  }): Promise<TranscriptionPacksListResponse>;
  uninstallTranscriptionModel(payload: {
    tier: "base" | "small" | "medium";
  }): Promise<TranscriptionPacksListResponse>;
  getSetupChecklist(): Promise<SetupChecklistResponse>;
  onTranscriptionPacksProgress(listener: (payload: TranscriptionPacksProgressEvent) => void): () => void;
  listContextProfiles(): Promise<ContextProfilesListResponse>;
  saveContextProfile(payload: ContextProfileSaveRequest): Promise<ContextProfilesListResponse>;
  onMeetingSessionStatus(listener: (payload: MeetingSessionStatusEvent) => void): () => void;
  onMeetingSessionCompleted(listener: (payload: MeetingSessionCompletedEvent) => void): () => void;
  onMeetingTranscriptDelta(listener: (payload: MeetingTranscriptDeltaEvent) => void): () => void;
  onMeetingMidSummary(listener: (payload: MeetingMidSummaryEvent) => void): () => void;
  onMeetingTranscriptBookmark(listener: (payload: MeetingTranscriptBookmarkEvent) => void): () => void;
  onTokenUsageThreshold(listener: (payload: TokenUsageThresholdEvent) => void): () => void;
  onMeetingActiveAlert(listener: (payload: MeetingActiveAlertEvent) => void): () => void;
  dismissMeetingActiveAlert(
    payload: MeetingActiveDismissRequest
  ): Promise<MeetingActiveDismissResponse>;
  listTeamMemory(): Promise<TeamMemoryListResponse>;
  deleteTeamMemoryItem(payload: { itemId: string }): Promise<TeamMemoryListResponse>;
  getTranslationConsentText(): Promise<ConsentTextResponse>;
  startTranslationSession(
    payload: TranslationSessionStartRequest
  ): Promise<TranslationSessionStartResponse & { captureMode?: string }>;
  stopTranslationSession(): Promise<TranslationSessionStopResponse>;
  getTranslationSessionStatus(): Promise<TranslationSessionStatusResponse>;
  ingestTranslationMicChunk(payload: { chunkBase64: string }): Promise<{ ok: boolean }>;
  onTranslationLine(listener: (payload: TranslationLineEvent) => void): () => void;
  onTranslationError(listener: (payload: TranslationErrorEvent) => void): () => void;
}
