// Generated by GitHub Copilot

/**
 * Canais IPC permitidos entre renderer e main process.
 */
export const IPC_CHANNELS = {
  desktopPing: "desktop:ping",
  screenshotCapture: "screenshot:capture",
  screenshotQueueGet: "screenshot:queue:get",
  screenshotQueueClear: "screenshot:queue:clear",
  screenshotQueueUpdated: "screenshot:queue-updated",
  stealthStateChanged: "stealth:state-changed",
  chatAsk: "chat:ask",
  chatStreamEvent: "chat:stream-event",
  promptPresetsGet: "prompt:presets:get",
  audioTranscribe: "audio:transcribe",
  stealthSetMode: "stealth:set-mode",
  settingsGet: "settings:get",
  settingsSave: "settings:save",
  settingsReset: "settings:reset",
  diagnosticsGet: "diagnostics:get",
  diagnosticsSetLogLevel: "diagnostics:set-log-level",
  featureFlagsGet: "feature-flags:get",
  featureFlagsSave: "feature-flags:save",
  featureFlagsReset: "feature-flags:reset",
  envGet: "env:get",
  autoUpdateGetState: "auto-update:get-state",
  autoUpdateSaveConfig: "auto-update:save-config",
  autoUpdateCheck: "auto-update:check",
  autoUpdateDownload: "auto-update:download",
  autoUpdateInstall: "auto-update:install",
  autoUpdateRollback: "auto-update:rollback",
  autoUpdateConfirmHealth: "auto-update:confirm-health",
  autoUpdateEvent: "auto-update:event"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export interface DesktopPingRequest {
  timestampIso?: string;
}

export interface DesktopPingResponse {
  ok: true;
  timestampIso: string;
}

export interface ScreenshotCaptureRequest {
  source: "full" | "region";
}

export interface ScreenshotCaptureResponse {
  captureId: string;
  imagePath: string;
  createdAtIso: string;
  source: "full" | "region";
  trigger: "manual" | "shortcut";
  previewDataUrl: string;
}

export interface ScreenshotQueueItem extends ScreenshotCaptureResponse {}

export interface ScreenshotQueueGetResponse {
  items: ScreenshotQueueItem[];
}

export interface ScreenshotQueueClearResponse {
  items: ScreenshotQueueItem[];
  clearedAtIso: string;
}

export interface ScreenshotQueueUpdatedEvent {
  items: ScreenshotQueueItem[];
}

export interface ChatAskRequest {
  sessionId: string;
  ask: string;
  screenshotIds?: string[];
  presetId?: string;
}

export interface ChatAskResponse {
  requestId: string;
  status: "accepted";
}

export interface ChatStreamEvent {
  requestId: string;
  status: "started" | "chunk" | "completed" | "error";
  deltaText?: string;
  fullText?: string;
  errorMessage?: string;
  errorCode?:
    | "LOCAL_PROVIDER_UNAVAILABLE"
    | "LOCAL_ONLY_PRIVACY_MODE_ACTIVE"
    | "MISSING_API_KEY"
    | "PROMPT_GUARDRAIL_BLOCKED"
    | "AUTH_INVALID_API_KEY"
    | "RATE_LIMIT"
    | "NETWORK"
    | "TIMEOUT"
    | "SERVER"
    | "UNKNOWN";
  actionableMessage?: string;
  retryable?: boolean;
  createdAtIso: string;
}

export interface PromptPreset {
  id: string;
  title: string;
  description: string;
}

export interface PromptPresetsGetResponse {
  presets: PromptPreset[];
}

export interface AudioTranscribeRequest {
  sessionId: string;
  chunkBase64: string;
  language?: string;
}

export interface AudioTranscribeResponse {
  text: string;
  isFinal: boolean;
}

export interface StealthSetModeRequest {
  enabled: boolean;
}

export interface StealthSetModeResponse {
  enabled: boolean;
  opacity: number;
  appliedAtIso: string;
}

export interface StealthStateChangedEvent {
  enabled: boolean;
  hardening: StealthHardening;
  opacity: number;
  source: "ipc" | "shortcut";
  appliedAtIso: string;
}

export interface AppSettings {
  language: string;
  selectedAudioInputDeviceId?: string;
  shortcuts: {
    captureScreen: string;
    pushToTalk: string;
    toggleStealth: string;
  };
  hasGeminiApiKey: boolean;
}

export type AutoUpdateChannel = "stable" | "beta";

export interface AutoUpdateConfig {
  enabled: boolean;
  feedUrl?: string;
  channel: AutoUpdateChannel;
  allowPrerelease: boolean;
}

export type AutoUpdateStatus =
  | "disabled"
  | "idle"
  | "checking"
  | "update-available"
  | "downloading"
  | "downloaded"
  | "up-to-date"
  | "rollback-ready"
  | "unavailable"
  | "error";

export interface AutoUpdateState {
  config: AutoUpdateConfig;
  status: AutoUpdateStatus;
  isPackaged: boolean;
  currentVersion: string;
  availableVersion?: string;
  downloadedVersion?: string;
  rollbackChannel?: AutoUpdateChannel;
  lastCheckedAtIso?: string;
  lastDownloadedAtIso?: string;
  lastError?: string;
  canCheck: boolean;
  canDownload: boolean;
  canInstall: boolean;
  canRollback: boolean;
  requiresHealthConfirmation: boolean;
}

export interface AutoUpdateGetStateResponse {
  state: AutoUpdateState;
}

export interface AutoUpdateSaveConfigRequest {
  enabled?: boolean;
  feedUrl?: string | null;
  channel?: AutoUpdateChannel;
  allowPrerelease?: boolean;
}

export interface AutoUpdateSaveConfigResponse {
  state: AutoUpdateState;
  savedAtIso: string;
}

export interface AutoUpdateCheckResponse {
  state: AutoUpdateState;
  checkedAtIso: string;
}

export interface AutoUpdateDownloadResponse {
  state: AutoUpdateState;
  startedAtIso: string;
}

export interface AutoUpdateInstallResponse {
  accepted: boolean;
  appliedAtIso: string;
}

export interface AutoUpdateRollbackRequest {
  channel?: AutoUpdateChannel;
}

export interface AutoUpdateRollbackResponse {
  state: AutoUpdateState;
  acceptedAtIso: string;
}

export interface AutoUpdateConfirmHealthResponse {
  state: AutoUpdateState;
  confirmedAtIso: string;
}

export interface AutoUpdateEvent {
  state: AutoUpdateState;
  kind:
    | "state-changed"
    | "checking"
    | "update-available"
    | "update-not-available"
    | "download-progress"
    | "update-downloaded"
    | "rollback-ready"
    | "error";
  message: string;
  progressPercent?: number;
  emittedAtIso: string;
}

export interface SettingsGetResponse {
  settings: AppSettings;
}

export interface SettingsSaveRequest {
  language?: string;
  selectedAudioInputDeviceId?: string | null;
  shortcuts?: {
    captureScreen?: string;
    pushToTalk?: string;
    toggleStealth?: string;
  };
  geminiApiKey?: string | null;
}

export interface SettingsSaveResponse {
  settings: AppSettings;
  savedAtIso: string;
}

export interface SettingsResetResponse {
  settings: AppSettings;
  resetAtIso: string;
}

export type LogLevel = "debug" | "info" | "warn" | "error";

export interface DiagnosticsGetResponse {
  logLevel: LogLevel;
  logFilePath: string;
  recentLines: string[];
}

export interface DiagnosticsSetLogLevelRequest {
  level: LogLevel;
}

export interface DiagnosticsSetLogLevelResponse {
  logLevel: LogLevel;
  updatedAtIso: string;
}

export type ProviderMode = "cloud" | "local" | "hybrid";
export type StealthHardening = "off" | "safe" | "strict";

export interface FeatureFlags {
  providerMode: ProviderMode;
  localProviderEnabled: boolean;
  forceLocalOnly: boolean;
  stealthHardening: StealthHardening;
}

export interface FeatureFlagsSource {
  providerMode: "persisted" | "env";
  localProviderEnabled: "persisted" | "env";
  forceLocalOnly: "persisted" | "env";
  stealthHardening: "persisted" | "env";
}

export interface FeatureFlagsGetResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
}

export interface FeatureFlagsSaveRequest {
  providerMode?: ProviderMode;
  localProviderEnabled?: boolean;
  forceLocalOnly?: boolean;
  stealthHardening?: StealthHardening;
}

export interface FeatureFlagsSaveResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
  savedAtIso: string;
}

export interface FeatureFlagsResetResponse {
  persisted: FeatureFlags;
  effective: FeatureFlags;
  source: FeatureFlagsSource;
  resetAtIso: string;
}

export interface EnvironmentSnapshot {
  nodeEnv: string;
  logLevel: string;
  providerMode?: ProviderMode;
  localProviderEnabled?: boolean;
  forceLocalOnly?: boolean;
  stealthHardening?: StealthHardening;
}

export interface EnvGetResponse {
  env: EnvironmentSnapshot;
}

/**
 * Contrato tipado da API exposta no preload.
 */
export interface DesktopApi {
  version: string;
  ping(payload: DesktopPingRequest): Promise<DesktopPingResponse>;
  captureScreenshot(payload: ScreenshotCaptureRequest): Promise<ScreenshotCaptureResponse>;
  getScreenshotQueue(): Promise<ScreenshotQueueGetResponse>;
  clearScreenshotQueue(): Promise<ScreenshotQueueClearResponse>;
  getPromptPresets(): Promise<PromptPresetsGetResponse>;
  submitAsk(payload: ChatAskRequest): Promise<ChatAskResponse>;
  onChatStreamEvent(listener: (payload: ChatStreamEvent) => void): () => void;
  transcribeAudioChunk(payload: AudioTranscribeRequest): Promise<AudioTranscribeResponse>;
  setStealthMode(payload: StealthSetModeRequest): Promise<StealthSetModeResponse>;
  getSettings(): Promise<SettingsGetResponse>;
  saveSettings(payload: SettingsSaveRequest): Promise<SettingsSaveResponse>;
  resetSettings(): Promise<SettingsResetResponse>;
  getDiagnostics(): Promise<DiagnosticsGetResponse>;
  setLogLevel(payload: DiagnosticsSetLogLevelRequest): Promise<DiagnosticsSetLogLevelResponse>;
  getFeatureFlags(): Promise<FeatureFlagsGetResponse>;
  saveFeatureFlags(payload: FeatureFlagsSaveRequest): Promise<FeatureFlagsSaveResponse>;
  resetFeatureFlags(): Promise<FeatureFlagsResetResponse>;
  getEnvironment(): Promise<EnvGetResponse>;
  getAutoUpdateState(): Promise<AutoUpdateGetStateResponse>;
  saveAutoUpdateConfig(payload: AutoUpdateSaveConfigRequest): Promise<AutoUpdateSaveConfigResponse>;
  checkForAutoUpdate(): Promise<AutoUpdateCheckResponse>;
  downloadAutoUpdate(): Promise<AutoUpdateDownloadResponse>;
  installAutoUpdate(): Promise<AutoUpdateInstallResponse>;
  rollbackAutoUpdate(payload: AutoUpdateRollbackRequest): Promise<AutoUpdateRollbackResponse>;
  confirmAutoUpdateHealth(): Promise<AutoUpdateConfirmHealthResponse>;
  quitApp(): Promise<void>;
  minimizeWindow(): Promise<void>;
  setWindowOpacity(opacity: number): Promise<{ opacity: number }>;
  onScreenshotQueueUpdated(listener: (payload: ScreenshotQueueUpdatedEvent) => void): () => void;
  onStealthStateChanged(listener: (payload: StealthStateChangedEvent) => void): () => void;
  onAutoUpdateEvent(listener: (payload: AutoUpdateEvent) => void): () => void;
}
