// Generated by GitHub Copilot
const fs = require("node:fs");
const path = require("node:path");
const { randomUUID } = require("node:crypto");
const { app } = require("electron");

const MAX_QUEUE = 5;

/**
 * Gerencia fila de áudios gravados no disco, com lifecycle explícito.
 * Audios são armazenados em userData/audio-captures e removidos sob demanda.
 */
function createAudioQueue(options) {
  const logger = options?.logger || {
    info: () => {},
    warn: () => {},
    error: () => {}
  };
  const audiosDir = path.join(app.getPath("userData"), "audio-captures");
  const queue = [];

  function ensureDir() {
    if (!fs.existsSync(audiosDir)) {
      fs.mkdirSync(audiosDir, { recursive: true });
    }
  }

  /**
   * Persiste áudio em disco e adiciona ao início da fila.
   * Remove o item mais antigo quando MAX_QUEUE é atingido.
   */
  function addAudio({ audioBase64, mimeType, durationSeconds }) {
    ensureDir();
    const audioId = randomUUID();
    const ext = mimeType.includes("webm") ? "webm" : mimeType.includes("ogg") ? "ogg" : "bin";
    const audioPath = path.join(audiosDir, `${audioId}.${ext}`);
    const buffer = Buffer.from(audioBase64, "base64");
    fs.writeFileSync(audioPath, buffer);

    const item = {
      audioId,
      audioPath,
      mimeType,
      durationSeconds,
      createdAtIso: new Date().toISOString()
    };

    queue.unshift(item);

    while (queue.length > MAX_QUEUE) {
      const removed = queue.pop();
      if (removed && fs.existsSync(removed.audioPath)) {
        fs.rmSync(removed.audioPath, { force: true });
      }
    }

    logger.info("Audio added to queue", {
      audioId,
      durationSeconds: Math.round(durationSeconds),
      sizeKB: Math.round(buffer.length / 1024),
      mimeType
    });

    return item;
  }

  function getQueue() {
    return [...queue];
  }

  function removeAudio(audioId) {
    const idx = queue.findIndex((a) => a.audioId === audioId);
    if (idx !== -1) {
      const item = queue.splice(idx, 1)[0];
      if (item && fs.existsSync(item.audioPath)) {
        fs.rmSync(item.audioPath, { force: true });
      }
      logger.info("Audio removed from queue", { audioId });
    }
  }

  function clearQueue() {
    while (queue.length > 0) {
      const item = queue.pop();
      if (item && fs.existsSync(item.audioPath)) {
        fs.rmSync(item.audioPath, { force: true });
      }
    }
  }

  return { addAudio, getQueue, removeAudio, clearQueue };
}

module.exports = { createAudioQueue };
