// Generated by GitHub Copilot
const test = require("node:test");
const assert = require("node:assert/strict");
const { EventEmitter } = require("node:events");
const {
  createAutoUpdateService,
  normalizeAutoUpdateConfig,
  validateAutoUpdateConfig
} = require("./auto-update-service.cjs");

/**
 * Cria store em memoria para exercitar o service sem tocar o filesystem.
 */
function createSettingsStore(seed = {}) {
  let state = {
    enabled: false,
    feedUrl: "",
    channel: "stable",
    allowPrerelease: false,
    pendingVersion: "",
    previousVersion: "",
    previousChannel: "stable",
    pendingHealthConfirmation: false,
    ...seed
  };

  return {
    getAutoUpdateSettings() {
      return { ...state };
    },
    saveAutoUpdateSettings(partial) {
      state = {
        ...state,
        ...(partial || {})
      };
      return { ...state };
    }
  };
}

/**
 * Cria updater fake com a superficie minima usada pelo service.
 */
function createFakeAutoUpdater() {
  const updater = new EventEmitter();
  updater.autoDownload = false;
  updater.autoInstallOnAppQuit = false;
  updater.allowPrerelease = false;
  updater.allowDowngrade = false;
  updater.fullChangelog = false;
  updater.feedConfig = null;
  updater.quitAndInstallCalls = 0;
  updater.setFeedURL = (config) => {
    updater.feedConfig = config;
  };
  updater.checkForUpdates = async () => {
    updater.emit("checking-for-update");
    updater.emit("update-not-available");
  };
  updater.downloadUpdate = async () => {
    updater.emit("download-progress", { percent: 55.4 });
    updater.emit("update-downloaded", { version: "0.2.0" });
  };
  updater.quitAndInstall = () => {
    updater.quitAndInstallCalls += 1;
  };
  return updater;
}

test("validateAutoUpdateConfig blocks insecure feed URLs", () => {
  const result = validateAutoUpdateConfig({
    enabled: true,
    feedUrl: "http://updates.example.com",
    channel: "stable",
    allowPrerelease: false
  });

  assert.equal(result, "Feed URL de auto-update deve usar HTTPS.");
});

test("normalizeAutoUpdateConfig trims feed URL and constrains channel", () => {
  const config = normalizeAutoUpdateConfig({
    enabled: 1,
    feedUrl: "  https://updates.example.com/app  ",
    channel: "beta",
    allowPrerelease: "yes"
  });

  assert.deepEqual(config, {
    enabled: true,
    feedUrl: "https://updates.example.com/app",
    channel: "beta",
    allowPrerelease: true
  });
});

test("createAutoUpdateService reports rollback-ready after downloaded version boots", () => {
  const settingsStore = createSettingsStore({
    enabled: true,
    feedUrl: "https://updates.example.com/clone-perssua",
    pendingVersion: "0.2.0",
    previousVersion: "0.1.0",
    previousChannel: "stable",
    pendingHealthConfirmation: true
  });
  const autoUpdater = createFakeAutoUpdater();
  const service = createAutoUpdateService({
    logger: { info() {}, warn() {}, error() {}, debug() {} },
    app: {
      isPackaged: true,
      getVersion() {
        return "0.2.0";
      }
    },
    settingsStore,
    autoUpdater,
    emitRendererEvent() {}
  });

  const state = service.getState();
  assert.equal(state.status, "rollback-ready");
  assert.equal(state.requiresHealthConfirmation, true);
  assert.equal(state.canRollback, true);
});

test("rollbackUpdate forces downgrade-capable check on previous channel", async () => {
  const settingsStore = createSettingsStore({
    enabled: true,
    feedUrl: "https://updates.example.com/clone-perssua",
    channel: "beta",
    previousChannel: "stable",
    pendingHealthConfirmation: true
  });
  const autoUpdater = createFakeAutoUpdater();
  const service = createAutoUpdateService({
    logger: { info() {}, warn() {}, error() {}, debug() {} },
    app: {
      isPackaged: true,
      getVersion() {
        return "0.2.0";
      }
    },
    settingsStore,
    autoUpdater,
    emitRendererEvent() {}
  });

  const state = await service.rollbackUpdate({});
  assert.equal(autoUpdater.allowDowngrade, true);
  assert.deepEqual(autoUpdater.feedConfig, {
    provider: "generic",
    url: "https://updates.example.com/clone-perssua",
    channel: "stable"
  });
  assert.equal(state.status, "downloaded");
  assert.equal(state.downloadedVersion, "0.2.0");
});
