// Generated by GitHub Copilot

function parseBoolean(value) {
  if (typeof value !== "string") {
    return undefined;
  }

  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) {
    return true;
  }

  if (["0", "false", "no", "off"].includes(normalized)) {
    return false;
  }

  return undefined;
}

function parseProviderMode(value) {
  if (typeof value !== "string") {
    return undefined;
  }

  const normalized = value.trim().toLowerCase();
  if (["cloud", "local", "hybrid"].includes(normalized)) {
    return normalized;
  }

  return undefined;
}

function parseStealthHardening(value) {
  if (typeof value !== "string") {
    return undefined;
  }

  const normalized = value.trim().toLowerCase();
  if (["off", "safe", "strict"].includes(normalized)) {
    return normalized;
  }

  return undefined;
}

/**
 * Lê variáveis de ambiente relevantes para configuração do runtime.
 */
function getEnvironmentConfig() {
  return {
    nodeEnv: process.env.NODE_ENV || "development",
    logLevel: process.env.DESKTOP_LOG_LEVEL || "info",
    providerMode: parseProviderMode(process.env.FEATURE_PROVIDER_MODE),
    localProviderEnabled: parseBoolean(process.env.FEATURE_LOCAL_PROVIDER_ENABLED),
    forceLocalOnly: parseBoolean(process.env.FEATURE_FORCE_LOCAL_ONLY),
    stealthHardening: parseStealthHardening(process.env.FEATURE_STEALTH_HARDENING)
  };
}

module.exports = {
  getEnvironmentConfig
};
