// Generated by GitHub Copilot
const test = require("node:test");
const assert = require("node:assert/strict");
const { resolveFeatureFlags } = require("./feature-flags.cjs");

test("resolveFeatureFlags aplica defaults e persisted", () => {
  const result = resolveFeatureFlags(
    {
      providerMode: "hybrid",
      localProviderEnabled: true,
      forceLocalOnly: false,
      stealthHardening: "strict"
    },
    {}
  );

  assert.equal(result.effective.providerMode, "hybrid");
  assert.equal(result.effective.localProviderEnabled, true);
  assert.equal(result.effective.stealthHardening, "strict");
});

test("resolveFeatureFlags com forceLocalOnly força provider local e habilita localProviderEnabled", () => {
  const result = resolveFeatureFlags(
    {
      providerMode: "cloud",
      localProviderEnabled: false,
      forceLocalOnly: true,
      stealthHardening: "safe"
    },
    {}
  );

  assert.equal(result.effective.forceLocalOnly, true);
  assert.equal(result.effective.providerMode, "local");
  assert.equal(result.effective.localProviderEnabled, true);
});

test("resolveFeatureFlags aplica override de env", () => {
  const result = resolveFeatureFlags(
    {
      providerMode: "cloud",
      localProviderEnabled: false,
      forceLocalOnly: false,
      stealthHardening: "safe"
    },
    {
      providerMode: "hybrid",
      localProviderEnabled: true,
      forceLocalOnly: false,
      stealthHardening: "strict"
    }
  );

  assert.equal(result.effective.providerMode, "hybrid");
  assert.equal(result.effective.localProviderEnabled, true);
  assert.equal(result.effective.stealthHardening, "strict");
  assert.equal(result.source.providerMode, "env");
});
