// Generated by GitHub Copilot

const DEFAULT_FEATURE_FLAGS = {
  providerMode: "cloud",
  localProviderEnabled: false,
  forceLocalOnly: false,
  stealthHardening: "safe"
};

/**
 * Resolve o estado efetivo das flags, aplicando overrides de ambiente.
 */
function resolveFeatureFlags(persistedFlags, envConfig) {
  const persisted = {
    ...DEFAULT_FEATURE_FLAGS,
    ...(persistedFlags || {})
  };

  const effective = {
    ...persisted
  };

  const source = {
    providerMode: "persisted",
    localProviderEnabled: "persisted",
    forceLocalOnly: "persisted",
    stealthHardening: "persisted"
  };

  if (envConfig.providerMode) {
    effective.providerMode = envConfig.providerMode;
    source.providerMode = "env";
  }

  if (typeof envConfig.localProviderEnabled === "boolean") {
    effective.localProviderEnabled = envConfig.localProviderEnabled;
    source.localProviderEnabled = "env";
  }

  if (typeof envConfig.forceLocalOnly === "boolean") {
    effective.forceLocalOnly = envConfig.forceLocalOnly;
    source.forceLocalOnly = "env";
  }

  if (envConfig.stealthHardening) {
    effective.stealthHardening = envConfig.stealthHardening;
    source.stealthHardening = "env";
  }

  if (effective.forceLocalOnly) {
    effective.providerMode = "local";
    effective.localProviderEnabled = true;
  }

  if (!effective.localProviderEnabled && effective.providerMode === "local") {
    effective.providerMode = "cloud";
  }

  return {
    persisted,
    effective,
    source
  };
}

module.exports = {
  DEFAULT_FEATURE_FLAGS,
  resolveFeatureFlags
};
