// Generated by GitHub Copilot
const { ipcMain, app, BrowserWindow, dialog, desktopCapturer, screen } = require("electron");
const { getDefaultMeetingRecordingsPath } = require("./meeting-audio-archive.cjs");
const { randomUUID } = require("node:crypto");
const { z } = require("zod");
const { getEnvironmentConfig, getEnvironmentReport } = require("./env-config.cjs");
const { resolveFeatureFlags } = require("./feature-flags.cjs");
const { buildPromptWithPreset, getPromptPresets } = require("./prompt-presets.cjs");
const { applyStealthFromSettings } = require("./stealth-profile.cjs");
const { applyWindowLayout } = require("./window-layout.cjs");
const { listMeetingTemplates, applyTemplateToSessionInput } = require("./meeting-templates.cjs");

const pingRequestSchema = z.object({
  timestampIso: z.string().datetime().optional()
});

const screenshotCaptureRequestSchema = z.object({
  source: z.enum(["full", "region"])
});

const chatAskRequestSchema = z.object({
  sessionId: z.string().min(1),
  ask: z.string().max(10000).optional().default(""),
  screenshotIds: z.array(z.string().min(1)).optional(),
  audioIds: z.array(z.string().min(1)).optional(),
  presetId: z.string().min(1).optional()
});

const audioAddRequestSchema = z.object({
  audioBase64: z.string().min(8),
  mimeType: z.string().min(5).max(60),
  durationSeconds: z.number().min(0).max(3600)
});

const audioRemoveRequestSchema = z.object({
  audioId: z.string().min(1)
});

const audioTranscribeRequestSchema = z.object({
  sessionId: z.string().min(1),
  chunkBase64: z.string().min(8),
  language: z.string().min(2).max(12).optional()
});

const stealthSetModeRequestSchema = z.object({
  enabled: z.boolean()
});

const audioCaptureSaveSchema = z.object({
  mode: z.enum(["microphone", "system_loopback", "output_device", "application"]).optional(),
  deviceId: z.string().max(512).optional(),
  preRollValidationSeconds: z.number().min(1).max(15).optional(),
  saveRecordings: z.boolean().optional(),
  recordingsPath: z.string().max(1024).optional()
});

const screenCaptureSaveSchema = z.object({
  mode: z.enum(["primary", "all_displays", "specific_display"]).optional(),
  displayId: z.string().max(128).optional()
});

const settingsSaveRequestSchema = z.object({
  language: z.string().min(2).max(20).optional(),
  selectedAudioInputDeviceId: z.string().max(256).nullable().optional(),
  selectedAudioInputDeviceLabel: z.string().max(256).nullable().optional(),
  shortcuts: z
    .object({
      captureScreen: z.string().min(3).max(40).optional(),
      pushToTalk: z.string().min(3).max(40).optional(),
      toggleFullStealth: z.string().min(3).max(40).optional()
    })
    .optional(),
  nonStealthModeEnabled: z.boolean().optional(),
  defaultCodeLanguage: z.string().min(2).max(24).optional(),
  geminiApiKey: z.string().max(2048).nullable().optional(),
  audioCapture: audioCaptureSaveSchema.optional(),
  screenCapture: screenCaptureSaveSchema.optional()
});

const diagnosticsSetLogLevelRequestSchema = z.object({
  level: z.enum(["debug", "info", "warn", "error"])
});

const featureFlagsSaveRequestSchema = z.object({
  providerMode: z.enum(["cloud", "local", "hybrid"]).optional(),
  localProviderEnabled: z.boolean().optional(),
  forceLocalOnly: z.boolean().optional(),
  stealthHardening: z.enum(["off", "safe", "strict"]).optional()
});

const autoUpdateSaveConfigRequestSchema = z.object({
  enabled: z.boolean().optional(),
  feedUrl: z.string().max(2048).nullable().optional(),
  channel: z.enum(["stable", "beta"]).optional(),
  allowPrerelease: z.boolean().optional()
});

const autoUpdateRollbackRequestSchema = z.object({
  channel: z.enum(["stable", "beta"]).optional()
});

const llmSettingsSaveSchema = z.object({
  providers: z
    .object({
      gemini: z
        .object({
          enabled: z.boolean().optional(),
          defaultModelId: z.string().optional(),
          apiKey: z.string().nullable().optional()
        })
        .optional(),
      openai: z
        .object({
          enabled: z.boolean().optional(),
          defaultModelId: z.string().optional(),
          apiKey: z.string().nullable().optional()
        })
        .optional(),
      anthropic: z
        .object({
          enabled: z.boolean().optional(),
          defaultModelId: z.string().optional(),
          apiKey: z.string().nullable().optional()
        })
        .optional()
    })
    .optional(),
  routing: z.record(z.any()).optional(),
  tokenBudget: z.record(z.any()).optional(),
  privacy: z.record(z.any()).optional()
});

const meetingTemplateIdSchema = z.enum([
  "daily",
  "retro",
  "one_on_one",
  "planning",
  "review",
  "interview"
]);

const meetingStartSchema = z.object({
  profileId: z.string().min(1),
  objective: z.string().max(4000),
  customPrompt: z.string().max(8000).optional(),
  endAtIso: z.string().datetime().optional(),
  useCloud: z.boolean(),
  mode: z.enum(["passive", "active", "hybrid"]).optional(),
  userAliases: z.array(z.string().max(120)).max(20).optional(),
  questionOnlyMode: z.boolean().optional(),
  templateId: meetingTemplateIdSchema.optional(),
  consentAccepted: z.literal(true),
  consentTextVersion: z.string().max(64).optional()
});

const sessionIdSchema = z.object({
  sessionId: z.string().min(1)
});

const meetingTranscriptAppendSchema = z.object({
  sessionId: z.string().min(1),
  text: z.string().min(1).max(50000)
});

const translationStartSchema = z.object({
  sourceLanguage: z.enum(["auto", "pt", "en", "es", "fr", "de", "it"]),
  targetLanguage: z.enum(["pt", "en", "es", "fr", "de", "it"]),
  useCloud: z.boolean(),
  consentAccepted: z.literal(true),
  consentTextVersion: z.string().max(64).optional()
});

const translationMicChunkSchema = z.object({
  chunkBase64: z.string().min(1).max(12_000_000)
});

const llmProviderTestSchema = z.object({
  providerId: z.enum(["gemini", "openai", "anthropic"]),
  modelId: z.string().optional()
});

const audioSourceTestSchema = z.object({
  mode: z.enum(["microphone", "system_loopback", "output_device"]).optional(),
  deviceId: z.string().max(512).optional(),
  preRollValidationSeconds: z.number().min(1).max(15).optional()
});

/**
 * Registra handlers IPC com validacao de payload para reduzir entrada invalida no main process.
 */
function createNoopLogger() {
  return {
    debug: () => {},
    info: () => {},
    warn: () => {},
    error: () => {},
    getLevel: () => "info",
    setLevel: () => "info",
    getLogFilePath: () => "",
    getRecentLines: () => []
  };
}

/**
 * Traduz erros técnicos em mensagens acionáveis para o usuário final.
 */
function toActionableChatError(error) {
  const rawMessage = error instanceof Error ? error.message : "Erro desconhecido";
  const message = rawMessage.toLowerCase();

  if (message.includes("api key") || message.includes("unauth") || message.includes("401")) {
    return {
      errorCode: "AUTH_INVALID_API_KEY",
      errorMessage: rawMessage,
      actionableMessage: "Valide a API key Gemini em Settings e tente novamente.",
      retryable: false
    };
  }

  if (message.includes("no longer available") || message.includes("model not found") || (message.includes("404") && message.includes("model"))) {
    return {
      errorCode: "MODEL_NOT_AVAILABLE",
      errorMessage: rawMessage,
      actionableMessage: "Modelo Gemini indisponível. Atualize o modelo em Configurações → Provedores IA (ou GEMINI_MODEL no .env) para gemini-3.5-flash.",
      retryable: false
    };
  }

  if (message.includes("429") || message.includes("quota") || message.includes("rate limit") || message.includes("resource_exhausted")) {
    return {
      errorCode: "RATE_LIMIT",
      errorMessage: rawMessage,
      actionableMessage: "Limite de requisições atingido. Aguarde alguns segundos e tente novamente.",
      retryable: true
    };
  }

  if (message.includes("timeout") || message.includes("timed out") || message.includes("deadline")) {
    return {
      errorCode: "TIMEOUT",
      errorMessage: rawMessage,
      actionableMessage: "A resposta demorou mais que o esperado. Reenvie com um ASK mais curto.",
      retryable: true
    };
  }

  if (message.includes("network") || message.includes("fetch") || message.includes("enotfound")) {
    return {
      errorCode: "NETWORK",
      errorMessage: rawMessage,
      actionableMessage: "Falha de rede. Verifique conexão com a internet e tente novamente.",
      retryable: true
    };
  }

  if (message.includes("500") || message.includes("503") || message.includes("internal")) {
    return {
      errorCode: "SERVER",
      errorMessage: rawMessage,
      actionableMessage: "Instabilidade temporária do serviço. Tente novamente em instantes.",
      retryable: true
    };
  }

  if (message.includes("local_only_privacy_mode_active") || message.includes("fallback cloud bloqueado")) {
    return {
      errorCode: "LOCAL_ONLY_PRIVACY_MODE_ACTIVE",
      errorMessage: rawMessage,
      actionableMessage: "Modo local-only ativo. Ajuste runtime local (modelo/binario) ou desative force local-only nas Feature flags.",
      retryable: false
    };
  }

  return {
    errorCode: "UNKNOWN",
    errorMessage: rawMessage,
    actionableMessage: "Erro inesperado. Revise Settings e tente novamente.",
    retryable: true
  };
}

function setupIpcHandlers(dependencies) {
  const logger = dependencies?.logger || createNoopLogger();
  const settingsStore = dependencies?.settingsStore;
  const screenshotService = dependencies?.screenshotService;
  const audioQueue = dependencies?.audioQueue;
  const shortcutService = dependencies?.shortcutService;
  const providerRouter = dependencies?.providerRouter;
  const llmProviderRegistry = dependencies?.llmProviderRegistry;
  const tokenUsageTracker = dependencies?.tokenUsageTracker;
  const meetingOrchestrator = dependencies?.meetingOrchestrator;
  const translationSession = dependencies?.translationSession;
  const audioLoopbackCapture = dependencies?.audioLoopbackCapture;
  const contextStore = dependencies?.contextStore;
  const consentAuditStore = dependencies?.consentAuditStore;
  const retentionPurgeService = dependencies?.retentionPurgeService;
  const audioSourceEnumerator = dependencies?.audioSourceEnumerator;
  const ffmpegInstaller = dependencies?.ffmpegInstaller;
  const audioCaptureMeter = dependencies?.audioCaptureMeter;
  const meetingAudioArchive = dependencies?.meetingAudioArchive;
  const transcriptionPacksService = dependencies?.transcriptionPacksService;
  const setupChecklistService = dependencies?.setupChecklistService;
  const audioSourceValidator = dependencies?.audioSourceValidator;
  const sttAdapter = dependencies?.sttAdapter;
  const autoUpdateService = dependencies?.autoUpdateService;
  const stealthWindowService = dependencies?.stealthWindowService;
  const contentProtectionGuard = dependencies?.contentProtectionGuard;
  const getMainWindow = dependencies?.getMainWindow;
  const emitRendererEvent = dependencies?.emitRendererEvent;

  // Persiste a opacidade do modo stealth entre ativações
  const DEFAULT_STEALTH_OPACITY = 0.9;
  let savedStealthOpacity = DEFAULT_STEALTH_OPACITY;

  if (!settingsStore || !screenshotService || !providerRouter || !sttAdapter || !autoUpdateService || !stealthWindowService || !emitRendererEvent) {
    throw new Error("IPC dependencies not provided.");
  }

  function syncStealthFromSettings(source) {
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    const applied = applyStealthFromSettings({
      settingsStore,
      stealthWindowService,
      effectiveFlags,
      opacity: savedStealthOpacity
    });
    emitRendererEvent("stealth:state-changed", {
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity,
      source,
      appliedAtIso: applied.appliedAtIso
    });
    return applied;
  }

  ipcMain.handle("desktop:ping", async (_event, payload) => {
    const parsed = pingRequestSchema.parse(payload ?? {});
    logger.debug("IPC desktop:ping", parsed);
    return {
      ok: true,
      timestampIso: parsed.timestampIso || new Date().toISOString()
    };
  });

  ipcMain.handle("screenshot:capture", async (_event, payload) => {
    const parsed = screenshotCaptureRequestSchema.parse(payload);
    logger.info("IPC screenshot:capture", parsed);
    return screenshotService.captureScreenshot({
      source: parsed.source,
      trigger: "manual"
    });
  });

  ipcMain.handle("screenshot:queue:get", async () => {
    logger.debug("IPC screenshot:queue:get");
    return {
      items: screenshotService.getQueue()
    };
  });

  ipcMain.handle("screenshot:displays:list", async () => {
    if (typeof screenshotService.listDisplays === "function") {
      return { displays: screenshotService.listDisplays() };
    }
    return { displays: [] };
  });

  ipcMain.handle("screenshot:capture:save", async (_event, payload) => {
    const parsed = screenCaptureSaveSchema.parse(payload ?? {});
    const settings = settingsStore.savePartial({ screenCapture: parsed });
    return {
      screenCapture: settings.screenCapture,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("screenshot:queue:clear", async () => {
    const items = screenshotService.clearQueue();
    return {
      items,
      clearedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("prompt:presets:get", async () => {
    return {
      presets: getPromptPresets()
    };
  });

  ipcMain.handle("audio:add", async (_event, payload) => {
    const parsed = audioAddRequestSchema.parse(payload);
    if (!audioQueue) {
      throw new Error("Audio queue not available.");
    }
    const item = audioQueue.addAudio({
      audioBase64: parsed.audioBase64,
      mimeType: parsed.mimeType,
      durationSeconds: parsed.durationSeconds
    });
    logger.info("IPC audio:add", { audioId: item.audioId, durationSeconds: Math.round(item.durationSeconds) });
    return {
      audioId: item.audioId,
      durationSeconds: item.durationSeconds,
      createdAtIso: item.createdAtIso
    };
  });

  ipcMain.handle("audio:remove", async (_event, payload) => {
    const parsed = audioRemoveRequestSchema.parse(payload);
    if (audioQueue) {
      audioQueue.removeAudio(parsed.audioId);
    }
    return { ok: true };
  });

  ipcMain.handle("chat:ask", async (_event, payload) => {
    const parsed = chatAskRequestSchema.parse(payload);
    const requestId = randomUUID();
    logger.info("IPC chat:ask accepted", {
      requestId,
      sessionId: parsed.sessionId,
      askLength: parsed.ask.length,
      screenshotCount: parsed.screenshotIds?.length || 0,
      presetId: parsed.presetId || "ui-analysis"
    });

    void (async () => {
      const env = getEnvironmentConfig();
      const resolvedFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env);

      const askRoute = llmProviderRegistry
        ? llmProviderRegistry.resolveRoute("ask")
        : { providerId: "gemini", modelId: "gemini-3.5-flash" };
      const apiKey =
        askRoute.providerId === "local"
          ? ""
          : settingsStore.getProviderApiKey(askRoute.providerId) || settingsStore.getGeminiApiKey();

      if (
        askRoute.providerId !== "local" &&
        !apiKey &&
        resolvedFlags.effective.providerMode === "cloud" &&
        !resolvedFlags.effective.localProviderEnabled &&
        !resolvedFlags.effective.forceLocalOnly
      ) {
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: "MISSING_API_KEY",
          errorMessage: `API key nao configurada para ${askRoute.providerId}.`,
          actionableMessage: "Abra Configuracoes > Provedores de IA e salve a chave do provedor ativo.",
          retryable: false,
          createdAtIso: new Date().toISOString()
        });
        return;
      }

      const availableScreenshots = screenshotService.getQueue();
      const selectedScreenshots = parsed.screenshotIds?.length
        ? availableScreenshots.filter((item) => parsed.screenshotIds.includes(item.captureId))
        : [];

      const availableAudios = audioQueue ? audioQueue.getQueue() : [];
      const selectedAudios = parsed.audioIds?.length
        ? availableAudios.filter((item) => parsed.audioIds.includes(item.audioId))
        : [];

      const promptBuild = buildPromptWithPreset({
        ask: parsed.ask || "",
        presetId: parsed.presetId,
        hasScreenshots: selectedScreenshots.length > 0,
        hasAudio: selectedAudios.length > 0,
        defaultCodeLanguage: settingsStore.getDefaultCodeLanguage()
      });

      if (!promptBuild.ok) {
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: promptBuild.errorCode,
          errorMessage: promptBuild.errorMessage,
          actionableMessage: promptBuild.actionableMessage,
          retryable: promptBuild.retryable,
          createdAtIso: new Date().toISOString()
        });
        return;
      }

      try {
        await providerRouter.streamAskResponse({
          requestId,
          apiKey: resolvedFlags.effective.forceLocalOnly ? "" : apiKey,
          effectiveFlags: resolvedFlags.effective,
          ask: promptBuild.prompt,
          screenshots: selectedScreenshots,
          audioItems: selectedAudios,
          onEvent: (streamEvent) => emitRendererEvent("chat:stream-event", streamEvent)
        });
      } catch (error) {
        const mappedError = toActionableChatError(error);
        logger.error("ProviderRouter streaming failed", {
          requestId,
          message: mappedError.errorMessage,
          code: mappedError.errorCode
        });
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: mappedError.errorCode,
          errorMessage: mappedError.errorMessage,
          actionableMessage: mappedError.actionableMessage,
          retryable: mappedError.retryable,
          createdAtIso: new Date().toISOString()
        });
      }
    })();

    return {
      requestId,
      status: "accepted"
    };
  });

  ipcMain.handle("audio:transcribe", async (_event, payload) => {
    const parsed = audioTranscribeRequestSchema.parse(payload);
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    logger.debug("IPC audio:transcribe", {
      sessionId: parsed.sessionId,
      language: parsed.language || "auto",
      providerMode: effectiveFlags.providerMode,
      forceLocalOnly: effectiveFlags.forceLocalOnly
    });

    try {
      return await sttAdapter.transcribe({
        sessionId: parsed.sessionId,
        chunkBase64: parsed.chunkBase64,
        language: parsed.language,
        apiKey: effectiveFlags.forceLocalOnly ? "" : settingsStore.getGeminiApiKey(),
        effectiveFlags
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "Falha desconhecida no STT";
      logger.error("IPC audio:transcribe failed", {
        sessionId: parsed.sessionId,
        message
      });
      return {
        text: `Falha de transcricao: ${message}`,
        isFinal: false
      };
    }
  });

  ipcMain.handle("stealth:set-mode", async (_event, payload) => {
    const parsed = stealthSetModeRequestSchema.parse(payload);
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    logger.info("IPC stealth:set-mode", {
      enabled: parsed.enabled,
      hardening: effectiveFlags.stealthHardening
    });

    const applied = stealthWindowService.setStealthMode({
      enabled: parsed.enabled,
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity
    });

    emitRendererEvent("stealth:state-changed", {
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity,
      source: "ipc",
      appliedAtIso: applied.appliedAtIso
    });

    return {
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      opacity: savedStealthOpacity,
      appliedAtIso: applied.appliedAtIso
    };
  });

  ipcMain.handle("stealth:toggle-full", async () => {
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    const applied = stealthWindowService.toggleFullStealthMode({
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity
    });
    emitRendererEvent("stealth:state-changed", {
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity,
      source: "ipc",
      appliedAtIso: applied.appliedAtIso
    });
    return {
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      opacity: savedStealthOpacity,
      appliedAtIso: applied.appliedAtIso
    };
  });

  ipcMain.handle("stealth:exit-full", async () => {
    const applied = stealthWindowService.exitFullStealthIfActive();
    if (applied.changed) {
      const env = getEnvironmentConfig();
      const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
      emitRendererEvent("stealth:state-changed", {
        enabled: applied.enabled,
        fullStealth: Boolean(applied.fullStealth),
        hardening: effectiveFlags.stealthHardening,
        opacity: savedStealthOpacity,
        source: "ipc",
        appliedAtIso: applied.appliedAtIso
      });
    }
    return {
      changed: applied.changed,
      enabled: applied.enabled,
      fullStealth: Boolean(applied.fullStealth),
      appliedAtIso: applied.appliedAtIso
    };
  });

  ipcMain.handle("stealth:content-protection", async () => {
    if (!contentProtectionGuard) {
      return {
        enabled: false,
        platformSupported: false,
        protectionLevel: "none",
        platformDetail: "Guard de content protection indisponivel.",
        windowCount: 0,
        watchdogActive: false,
        lastError: ""
      };
    }
    contentProtectionGuard.applyAll();
    return contentProtectionGuard.getState();
  });

  ipcMain.handle("settings:get", async () => {
    logger.debug("IPC settings:get");
    return {
      settings: settingsStore.getPublicSettings()
    };
  });

  ipcMain.handle("settings:save", async (_event, payload) => {
    const parsed = settingsSaveRequestSchema.parse(payload ?? {});
    const settings = settingsStore.savePartial(parsed);
    if (shortcutService) {
      shortcutService.refreshShortcuts();
    }
    if (Object.prototype.hasOwnProperty.call(parsed, "nonStealthModeEnabled")) {
      syncStealthFromSettings("settings");
    }
    logger.info("IPC settings:save", {
      language: settings.language,
      hasGeminiApiKey: settings.hasGeminiApiKey,
      nonStealthModeEnabled: settings.nonStealthModeEnabled
    });
    return {
      settings,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("settings:reset", async () => {
    const settings = settingsStore.reset();
    if (shortcutService) {
      shortcutService.refreshShortcuts();
    }
    syncStealthFromSettings("settings");
    logger.warn("IPC settings:reset applied");
    return {
      settings,
      resetAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("diagnostics:get", async () => {
    logger.debug("IPC diagnostics:get");
    return {
      logLevel: logger.getLevel(),
      logFilePath: logger.getLogFilePath(),
      recentLines: logger.getRecentLines(80)
    };
  });

  ipcMain.handle("diagnostics:set-log-level", async (_event, payload) => {
    const parsed = diagnosticsSetLogLevelRequestSchema.parse(payload);
    const logLevel = logger.setLevel(parsed.level);
    return {
      logLevel,
      updatedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("feature-flags:get", async () => {
    const persisted = settingsStore.getFeatureFlags();
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.debug("IPC feature-flags:get", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return resolved;
  });

  ipcMain.handle("feature-flags:save", async (_event, payload) => {
    const parsed = featureFlagsSaveRequestSchema.parse(payload ?? {});
    const normalizedPayload = {
      ...parsed,
      providerMode: parsed.forceLocalOnly ? "local" : parsed.providerMode,
      localProviderEnabled: parsed.forceLocalOnly ? true : parsed.localProviderEnabled
    };
    const persisted = settingsStore.saveFeatureFlags(normalizedPayload);
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.info("IPC feature-flags:save", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return {
      ...resolved,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("feature-flags:reset", async () => {
    const persisted = settingsStore.resetFeatureFlags();
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.warn("IPC feature-flags:reset", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return {
      ...resolved,
      resetAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("env:get", async () => {
    const report = getEnvironmentReport();
    logger.debug("IPC env:get", {
      overrideCount: report.overrides.length
    });
    return report;
  });

  ipcMain.handle("auto-update:get-state", async () => {
    logger.debug("IPC auto-update:get-state");
    return {
      state: autoUpdateService.getState()
    };
  });

  ipcMain.handle("auto-update:save-config", async (_event, payload) => {
    const parsed = autoUpdateSaveConfigRequestSchema.parse(payload ?? {});
    const state = autoUpdateService.saveConfig({
      ...parsed,
      feedUrl: parsed.feedUrl === null ? "" : parsed.feedUrl
    });
    logger.info("IPC auto-update:save-config", {
      enabled: state.config.enabled,
      channel: state.config.channel,
      hasFeedUrl: Boolean(state.config.feedUrl)
    });
    return {
      state,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:check", async () => {
    logger.info("IPC auto-update:check");
    const state = await autoUpdateService.checkForUpdates();
    return {
      state,
      checkedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:download", async () => {
    logger.info("IPC auto-update:download");
    const state = await autoUpdateService.downloadUpdate();
    return {
      state,
      startedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:install", async () => {
    logger.warn("IPC auto-update:install");
    autoUpdateService.installUpdate();
    return {
      accepted: true,
      appliedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:rollback", async (_event, payload) => {
    const parsed = autoUpdateRollbackRequestSchema.parse(payload ?? {});
    logger.warn("IPC auto-update:rollback", {
      channel: parsed.channel || "previous"
    });
    const state = await autoUpdateService.rollbackUpdate(parsed);
    return {
      state,
      acceptedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:confirm-health", async () => {
    logger.info("IPC auto-update:confirm-health");
    const state = autoUpdateService.confirmHealth();
    return {
      state,
      confirmedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("audio:sources:list", async () => {
    if (!audioSourceEnumerator) {
      return { modes: ["microphone"], outputs: [], platformSupported: false };
    }
    return audioSourceEnumerator.listSources();
  });

  ipcMain.handle("audio:loopback:desktop-source", async () => {
    const sources = await desktopCapturer.getSources({
      types: ["screen"],
      thumbnailSize: { width: 1, height: 1 }
    });
    const primary = screen.getPrimaryDisplay();
    const withDisplay = sources.filter((s) => Boolean(s.display_id));
    const pool = withDisplay.length > 0 ? withDisplay : sources;
    const match =
      pool.find((s) => String(s.display_id) === String(primary.id)) || pool[0] || sources[0];
    if (!match) {
      return { id: "", name: "", displayId: "" };
    }
    return {
      id: match.id,
      name: match.name || "Tela",
      displayId: match.display_id ? String(match.display_id) : String(primary.id)
    };
  });

  ipcMain.handle("audio:source:test", async (_event, payload) => {
    const parsed = audioSourceTestSchema.parse(payload ?? {});
    const profile = {
      mode: parsed.mode || settingsStore.getAudioCapture().mode,
      deviceId: parsed.deviceId ?? settingsStore.getAudioCapture().deviceId,
      preRollValidationSeconds:
        parsed.preRollValidationSeconds || settingsStore.getAudioCapture().preRollValidationSeconds
    };
    // Loopback real no Windows usa desktopCapturer (FFmpeg não tem WASAPI).
    if (profile.mode !== "microphone") {
      const sources = await desktopCapturer.getSources({
        types: ["screen"],
        thumbnailSize: { width: 1, height: 1 }
      });
      if (!sources.length) {
        return {
          ok: false,
          code: "AUDIO_DEVICE_BUSY",
          message: "Nenhuma tela encontrada para captura de áudio do sistema."
        };
      }
      return {
        ok: true,
        code: "OK",
        message:
          "Fonte de loopback OK (Electron desktopCapturer). Use “Medidor ao vivo” para ver dB."
      };
    }
    if (!audioSourceValidator) {
      return { ok: true, code: "OK", message: "Validador indisponivel." };
    }
    return audioSourceValidator.testSource(profile);
  });

  ipcMain.handle("audio:capture:meter:start", async (_event, payload) => {
    if (!audioCaptureMeter?.start) {
      return { ok: false };
    }
    return audioCaptureMeter.start(payload || {});
  });

  ipcMain.handle("audio:capture:meter:stop", async () => {
    if (audioCaptureMeter?.stop) {
      audioCaptureMeter.stop();
    }
    return { ok: true };
  });

  ipcMain.handle("audio:capture:level:report", async (_event, payload) => {
    if (audioCaptureMeter?.reportRendererLevel) {
      audioCaptureMeter.reportRendererLevel(payload || {});
    }
    return { ok: true };
  });

  ipcMain.handle("audio:capture:save", async (_event, payload) => {
    const parsed = audioCaptureSaveSchema.parse(payload ?? {});
    const settings = settingsStore.savePartial({ audioCapture: parsed });
    return { audioCapture: settings.audioCapture, savedAtIso: new Date().toISOString() };
  });

  ipcMain.handle("audio:recordings:defaults", async () => {
    const ac = settingsStore.getAudioCapture();
    const defaultPath = getDefaultMeetingRecordingsPath();
    return {
      defaultPath,
      recordingsPath: ac.recordingsPath || defaultPath,
      saveRecordings: Boolean(ac.saveRecordings)
    };
  });

  ipcMain.handle("audio:recordings:pick-folder", async () => {
    const win = typeof getMainWindow === "function" ? getMainWindow() : null;
    const result = await dialog.showOpenDialog(win && !win.isDestroyed() ? win : undefined, {
      title: "Pasta para áudios de reunião",
      properties: ["openDirectory", "createDirectory"],
      defaultPath: settingsStore.getAudioCapture().recordingsPath || getDefaultMeetingRecordingsPath()
    });
    if (result.canceled || !result.filePaths?.[0]) {
      return { canceled: true, path: "" };
    }
    return { canceled: false, path: result.filePaths[0] };
  });

  ipcMain.handle("audio:recordings:save-chunk", async (_event, payload) => {
    const parsed = z
      .object({
        sessionId: z.string().min(1),
        chunkBase64: z.string().min(8),
        extension: z.string().max(12).optional(),
        kind: z.enum(["meeting", "translation"]).optional()
      })
      .parse(payload ?? {});
    if (!meetingAudioArchive) {
      return { saved: false, reason: "archive-unavailable" };
    }
    return meetingAudioArchive.saveChunkBase64(parsed);
  });

  ipcMain.handle("transcription:packs:list", async () => {
    if (!transcriptionPacksService) {
      return {
        packs: [],
        modelTiers: [],
        preferredModelTier: "base",
        engine: { modelReady: false, binaryReady: false, fullyReady: false },
        requiredReady: false,
        requiredInstalled: false,
        requiredLanguageIds: ["pt", "en"]
      };
    }
    return transcriptionPacksService.listPacks();
  });

  ipcMain.handle("transcription:packs:install", async (_event, payload) => {
    const packId = z.string().min(1).max(16).parse(payload?.packId);
    logger.info("IPC transcription:packs:install", { packId });
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.installPack(packId);
  });

  ipcMain.handle("transcription:packs:uninstall", async (_event, payload) => {
    const packId = z.string().min(1).max(16).parse(payload?.packId);
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.uninstallPack(packId);
  });

  ipcMain.handle("transcription:packs:install-required", async () => {
    logger.info("IPC transcription:packs:install-required");
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.setupEverything();
  });

  ipcMain.handle("transcription:packs:setup", async (_event, payload) => {
    const tier = z.enum(["base", "small", "medium"]).optional().parse(payload?.tier);
    logger.info("IPC transcription:packs:setup", { tier });
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.setupEverything(tier);
  });

  ipcMain.handle("transcription:packs:set-tier", async (_event, payload) => {
    const tier = z.enum(["base", "small", "medium"]).parse(payload?.tier ?? "base");
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.setPreferredModelTier(tier);
  });

  ipcMain.handle("transcription:packs:uninstall-model", async (_event, payload) => {
    const tier = z.enum(["base", "small", "medium"]).parse(payload?.tier ?? "base");
    if (!transcriptionPacksService) {
      throw new Error("Servico de pacotes indisponivel.");
    }
    return transcriptionPacksService.uninstallModelTier(tier);
  });

  ipcMain.handle("setup:checklist", async () => {
    if (!setupChecklistService) {
      return {
        items: [],
        pending: [],
        pendingRequired: [],
        readyCount: 0,
        totalCount: 0,
        allRequiredReady: true,
        byTab: {}
      };
    }
    return setupChecklistService.getChecklist();
  });

  ipcMain.handle("audio:ffmpeg:status", async () => {
    if (!ffmpegInstaller) {
      return {
        available: false,
        path: "",
        managedPath: "",
        installState: "idle",
        lastError: "Instalador indisponivel.",
        lastInstalledAtIso: "",
        platformSupported: process.platform === "win32"
      };
    }
    return ffmpegInstaller.getStatus();
  });

  ipcMain.handle("audio:ffmpeg:install", async (_event, payload) => {
    const force = Boolean(payload?.force);
    logger.info("IPC audio:ffmpeg:install", { force });
    if (!ffmpegInstaller) {
      return {
        available: false,
        path: "",
        managedPath: "",
        installState: "failed",
        lastError: "Instalador indisponivel.",
        lastInstalledAtIso: "",
        platformSupported: process.platform === "win32"
      };
    }
    return ffmpegInstaller.installPortable({ force });
  });

  ipcMain.handle("llm:settings:get", async () => ({
    llm: settingsStore.getPublicLlmSettings()
  }));

  ipcMain.handle("llm:settings:save", async (_event, payload) => {
    const parsed = llmSettingsSaveSchema.parse(payload ?? {});
    settingsStore.saveLlmPartial(parsed);
    return {
      llm: settingsStore.getPublicLlmSettings(),
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("llm:providers:test", async (_event, payload) => {
    const parsed = llmProviderTestSchema.parse(payload);
    if (!llmProviderRegistry) {
      return { ok: false, message: "Registry indisponivel.", testedAtIso: new Date().toISOString() };
    }
    try {
      const route = settingsStore.getLlmRouting();
      const modelId =
        parsed.modelId || settingsStore.getPublicLlmSettings().providers[parsed.providerId].defaultModelId;
      await llmProviderRegistry.testProvider(parsed.providerId, modelId);
      return { ok: true, message: "Conexao OK.", testedAtIso: new Date().toISOString() };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Falha no teste";
      return { ok: false, message, testedAtIso: new Date().toISOString() };
    }
  });

  ipcMain.handle("usage:tokens:session", async (_event, payload) => {
    const { sessionId } = sessionIdSchema.parse(payload ?? {});
    if (!tokenUsageTracker) {
      return {
        sessionId,
        estimatedTokens: 0,
        recordedInputTokens: 0,
        recordedOutputTokens: 0,
        cloudActive: false
      };
    }
    const u = tokenUsageTracker.getSessionUsage(sessionId);
    return {
      sessionId,
      estimatedTokens: u.estimatedTokens,
      recordedInputTokens: u.recordedInputTokens,
      recordedOutputTokens: u.recordedOutputTokens,
      cloudActive: u.cloudActive
    };
  });

  ipcMain.handle("usage:tokens:daily", async () => {
    if (!tokenUsageTracker?.getDailyUsage) {
      return {
        date: new Date().toISOString().slice(0, 10),
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
        overDaily: false
      };
    }
    const d = tokenUsageTracker.getDailyUsage();
    return {
      date: d.date,
      inputTokens: d.inputTokens,
      outputTokens: d.outputTokens,
      totalTokens: d.totalTokens,
      overDaily: d.overDaily
    };
  });

  if (consentAuditStore) {
    ipcMain.handle("meeting:consent:get", async () => consentAuditStore.getConsentText());

    ipcMain.handle("meeting:consent:list", async (_event, payload) => {
      const limit = z.number().int().min(1).max(200).optional().parse(payload?.limit);
      return { entries: consentAuditStore.listRecent(limit ?? 50) };
    });
  }

  ipcMain.handle("meeting:templates:list", async () => ({
    templates: listMeetingTemplates()
  }));

  if (retentionPurgeService) {
    ipcMain.handle("privacy:retention:purge", async () => retentionPurgeService.runPurge());
  }

  if (contextStore) {
    ipcMain.handle("context:profiles:list", async () => ({
      profiles: contextStore.listProfiles()
    }));

    ipcMain.handle("context:profiles:save", async (_event, payload) => {
      const profile = payload?.profile;
      if (!profile?.name) {
        throw new Error("Perfil invalido.");
      }
      const profiles = contextStore.saveProfile(profile);
      return { profiles };
    });

    ipcMain.handle("context:profiles:delete", async (_event, payload) => {
      const profileId = z.string().min(1).parse(payload?.profileId);
      const profiles = contextStore.deleteProfile(profileId);
      return { profiles };
    });

    ipcMain.handle("context:profiles:duplicate", async (_event, payload) => {
      const profileId = z.string().min(1).parse(payload?.profileId);
      contextStore.duplicateProfile(profileId);
      return { profiles: contextStore.listProfiles() };
    });

    ipcMain.handle("context:team-memory:list", async () => {
      return { items: contextStore.listTeamMemory() };
    });

    ipcMain.handle("context:team-memory:update", async (_event, payload) => {
      const itemId = z.string().min(1).parse(payload?.itemId);
      const updated = contextStore.updateTeamMemoryItem(itemId, {
        excerpt: payload?.excerpt,
        fullSummary: payload?.fullSummary,
        objective: payload?.objective
      });
      if (!updated) {
        throw new Error("Registro nao encontrado.");
      }
      return { items: contextStore.listTeamMemory() };
    });

    ipcMain.handle("context:team-memory:delete", async (_event, payload) => {
      const itemId = z.string().min(1).parse(payload?.itemId);
      const items = contextStore.deleteTeamMemoryItem(itemId);
      return { items };
    });
  }

  if (meetingOrchestrator) {
    ipcMain.handle("meeting:session:start", async (_event, payload) => {
      if (translationSession?.isActive?.()) {
        throw new Error("Encerre a traducao ao vivo antes de iniciar uma reuniao.");
      }
      let parsed = meetingStartSchema.parse(payload);
      if (parsed.templateId) {
        parsed = applyTemplateToSessionInput(parsed.templateId, parsed);
      }
      return meetingOrchestrator.startSession(parsed);
    });

    ipcMain.handle("meeting:session:mid-summary", async (_event, payload) => {
      const { sessionId } = sessionIdSchema.parse(payload);
      return meetingOrchestrator.requestMidCallSummary(sessionId);
    });

    ipcMain.handle("meeting:transcript:bookmark", async (_event, payload) => {
      const { sessionId } = sessionIdSchema.parse(payload);
      return meetingOrchestrator.addBookmark(sessionId);
    });

    ipcMain.handle("meeting:session:stop", async (_event, payload) => {
      const { sessionId } = sessionIdSchema.parse(payload);
      return meetingOrchestrator.stopSession({ sessionId });
    });

    ipcMain.handle("meeting:session:cancel", async (_event, payload) => {
      const { sessionId } = sessionIdSchema.parse(payload);
      return meetingOrchestrator.cancelSession({ sessionId });
    });

    ipcMain.handle("meeting:transcript:append", async (_event, payload) => {
      const parsed = meetingTranscriptAppendSchema.parse(payload);
      return meetingOrchestrator.appendTranscript(parsed.sessionId, parsed.text);
    });

    ipcMain.handle("meeting:active:dismiss", async (_event, payload) => {
      const sessionId = z.string().min(1).parse(payload?.sessionId);
      const questionText = z.string().min(1).max(2000).parse(payload?.questionText);
      return meetingOrchestrator.dismissActiveAlert(sessionId, questionText);
    });
  }

  if (consentAuditStore) {
    ipcMain.handle("translation:consent:get", async () => consentAuditStore.getConsentText());
  }

  if (translationSession) {
    ipcMain.handle("translation:session:start", async (_event, payload) => {
      if (meetingOrchestrator?.hasActiveRecording?.()) {
        throw new Error("Encerre a reuniao antes de iniciar traducao ao vivo.");
      }
      if (audioLoopbackCapture?.isRecording?.()) {
        throw new Error("Captura de audio em uso pela reuniao.");
      }
      const parsed = translationStartSchema.parse(payload);
      return translationSession.start(parsed);
    });

    ipcMain.handle("translation:session:stop", async () => translationSession.stop());

    ipcMain.handle("translation:session:status", async () => translationSession.getStatus());

    ipcMain.handle("translation:chunk:ingest", async (_event, payload) => {
      const parsed = translationMicChunkSchema.parse(payload);
      return translationSession.ingestMicChunk(parsed.chunkBase64);
    });
  }

  ipcMain.handle("app:quit", () => {
    logger.info("IPC app:quit — encerrando aplicacao");
    // process.exit bypasses all event handlers and quits immediately
    setImmediate(() => process.exit(0));
  });

  ipcMain.handle("window:minimize", () => {
    const win = (getMainWindow && getMainWindow()) || BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0];
    if (win && !win.isDestroyed()) win.minimize();
    logger.debug("IPC window:minimize");
  });

  ipcMain.handle("window:set-opacity", (_event, payload) => {
    const opacity = z.number().min(0.05).max(1).parse(payload?.opacity ?? 1);
    // Persiste para re-usar na próxima ativação do stealth
    savedStealthOpacity = opacity;
    const win = (getMainWindow && getMainWindow()) || BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0];
    if (win && !win.isDestroyed()) win.setOpacity(opacity);
    logger.debug("IPC window:set-opacity", { opacity, hasWin: Boolean(win) });
    return { opacity };
  });

  ipcMain.handle("window:set-layout", (_event, payload) => {
    const layout = z.enum(["chat", "settings", "expanded"]).parse(payload?.layout ?? "chat");
    const win = (getMainWindow && getMainWindow()) || BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0];
    if (!win || win.isDestroyed()) {
      return { layout, applied: false };
    }
    const result = applyWindowLayout(win, layout);
    logger.debug("IPC window:set-layout", result);
    return result;
  });
}

module.exports = {
  setupIpcHandlers
};
