// Generated by GitHub Copilot
const test = require("node:test");
const assert = require("node:assert/strict");
const Module = require("node:module");

function loadIpcWithMockedElectron(ipcMainMock) {
  const originalLoad = Module._load;
  Module._load = function patchedLoad(request, parent, isMain) {
    if (request === "electron") {
      return { ipcMain: ipcMainMock };
    }

    return originalLoad.call(this, request, parent, isMain);
  };

  try {
    delete require.cache[require.resolve("./ipc.cjs")];
    return require("./ipc.cjs");
  } finally {
    Module._load = originalLoad;
  }
}

function createHarness() {
  const handlers = new Map();
  const rendererEvents = [];

  const ipcMainMock = {
    handle(channel, handler) {
      handlers.set(channel, handler);
    }
  };

  const { setupIpcHandlers } = loadIpcWithMockedElectron(ipcMainMock);

  const dependencies = {
    logger: {
      debug: () => {},
      info: () => {},
      warn: () => {},
      error: () => {},
      getLevel: () => "info",
      setLevel: () => "info",
      getLogFilePath: () => "",
      getRecentLines: () => []
    },
    settingsStore: {
      getPublicSettings: () => ({
        language: "pt-BR",
        shortcuts: {
          captureScreen: "Ctrl+E",
          pushToTalk: "Ctrl+D",
          toggleStealth: "Ctrl+B"
        },
        hasGeminiApiKey: true
      }),
      getGeminiApiKey: () => "api-key",
      getFeatureFlags: () => ({
        providerMode: "cloud",
        localProviderEnabled: false,
        forceLocalOnly: false,
        stealthHardening: "safe"
      }),
      savePartial: () => ({
        language: "pt-BR",
        shortcuts: {
          captureScreen: "Ctrl+E",
          pushToTalk: "Ctrl+D",
          toggleStealth: "Ctrl+B"
        },
        hasGeminiApiKey: true
      }),
      reset: () => ({
        language: "pt-BR",
        shortcuts: {
          captureScreen: "Ctrl+E",
          pushToTalk: "Ctrl+D",
          toggleStealth: "Ctrl+B"
        },
        hasGeminiApiKey: false
      }),
      saveFeatureFlags: (partial) => ({
        providerMode: partial.providerMode || "cloud",
        localProviderEnabled: Boolean(partial.localProviderEnabled),
        forceLocalOnly: Boolean(partial.forceLocalOnly),
        stealthHardening: partial.stealthHardening || "safe"
      }),
      resetFeatureFlags: () => ({
        providerMode: "cloud",
        localProviderEnabled: false,
        forceLocalOnly: false,
        stealthHardening: "safe"
      })
    },
    screenshotService: {
      captureScreenshot: async () => ({
        captureId: "cap-1",
        imagePath: "tmp/cap-1.png",
        createdAtIso: new Date().toISOString(),
        source: "full",
        trigger: "manual",
        previewDataUrl: "data:image/png;base64,aaaa"
      }),
      getQueue: () => [
        {
          captureId: "cap-1",
          imagePath: "tmp/cap-1.png",
          createdAtIso: new Date().toISOString(),
          source: "full",
          trigger: "manual",
          previewDataUrl: "data:image/png;base64,aaaa"
        }
      ],
      clearQueue: () => []
    },
    shortcutService: {
      refreshShortcuts: () => ({ captureShortcut: "Ctrl+E", stealthShortcut: "Ctrl+B" })
    },
    providerRouter: {
      streamAskResponse: async (input) => {
        input.onEvent({
          requestId: input.requestId,
          status: "started",
          createdAtIso: new Date().toISOString()
        });
        input.onEvent({
          requestId: input.requestId,
          status: "completed",
          fullText: "ok",
          createdAtIso: new Date().toISOString()
        });
      }
    },
    sttAdapter: {
      transcribe: async () => ({
        text: "ok",
        isFinal: false
      })
    },
    autoUpdateService: {
      getState: () => ({
        config: {
          enabled: false,
          feedUrl: "",
          channel: "stable",
          allowPrerelease: false
        },
        status: "disabled",
        isPackaged: false,
        currentVersion: "0.1.0",
        rollbackChannel: "stable",
        canCheck: false,
        canDownload: false,
        canInstall: false,
        canRollback: false,
        requiresHealthConfirmation: false
      }),
      saveConfig: function saveConfig() {
        return this.getState();
      },
      checkForUpdates: async function checkForUpdates() {
        return this.getState();
      },
      downloadUpdate: async function downloadUpdate() {
        return this.getState();
      },
      installUpdate: () => {},
      rollbackUpdate: async function rollbackUpdate() {
        return this.getState();
      },
      confirmHealth: function confirmHealth() {
        return this.getState();
      }
    },
    stealthWindowService: {
      setStealthMode: ({ enabled }) => ({
        enabled,
        hardening: "safe",
        appliedAtIso: new Date().toISOString()
      })
    },
    emitRendererEvent: (channel, payload) => {
      rendererEvents.push({ channel, payload });
    }
  };

  setupIpcHandlers(dependencies);

  async function invoke(channel, payload) {
    const handler = handlers.get(channel);
    assert.ok(handler, `Handler nao registrado: ${channel}`);
    return handler({}, payload);
  }

  return {
    invoke,
    rendererEvents,
    dependencies
  };
}

test("E2E IPC screenshot: captura e fila", async () => {
  const harness = createHarness();

  const capture = await harness.invoke("screenshot:capture", { source: "full" });
  assert.equal(capture.captureId, "cap-1");

  const queue = await harness.invoke("screenshot:queue:get");
  assert.equal(queue.items.length, 1);

  const cleared = await harness.invoke("screenshot:queue:clear");
  assert.equal(cleared.items.length, 0);
});

test("E2E IPC audio: transcricao retorna payload do adapter", async () => {
  const harness = createHarness();
  const response = await harness.invoke("audio:transcribe", {
    sessionId: "s-1",
    chunkBase64: "YWFhYWFhYQ==",
    language: "pt"
  });

  assert.equal(response.text, "ok");
  assert.equal(response.isFinal, false);
});

test("E2E IPC stealth: emite evento de estado para renderer", async () => {
  const harness = createHarness();
  const response = await harness.invoke("stealth:set-mode", { enabled: true });

  assert.equal(response.enabled, true);
  const event = harness.rendererEvents.find((item) => item.channel === "stealth:state-changed");
  assert.ok(event);
  assert.equal(event.payload.enabled, true);
});

test("E2E IPC chat: aceita request e emite stream started/completed", async () => {
  const harness = createHarness();

  const accepted = await harness.invoke("chat:ask", {
    sessionId: "session-1",
    ask: "Analise a interface",
    screenshotIds: ["cap-1"],
    presetId: "ui-analysis"
  });

  assert.equal(accepted.status, "accepted");
  await new Promise((resolve) => setTimeout(resolve, 5));

  const chatEvents = harness.rendererEvents
    .filter((item) => item.channel === "chat:stream-event")
    .map((item) => item.payload.status);

  assert.ok(chatEvents.includes("started"));
  assert.ok(chatEvents.includes("completed"));
});
