// Generated by GitHub Copilot
const { ipcMain, app, BrowserWindow } = require("electron");
const { randomUUID } = require("node:crypto");
const { z } = require("zod");
const { getEnvironmentConfig } = require("./env-config.cjs");
const { resolveFeatureFlags } = require("./feature-flags.cjs");
const { buildPromptWithPreset, getPromptPresets } = require("./prompt-presets.cjs");

const pingRequestSchema = z.object({
  timestampIso: z.string().datetime().optional()
});

const screenshotCaptureRequestSchema = z.object({
  source: z.enum(["full", "region"])
});

const chatAskRequestSchema = z.object({
  sessionId: z.string().min(1),
  ask: z.string().min(1).max(10000),
  screenshotIds: z.array(z.string().min(1)).optional(),
  presetId: z.string().min(1).optional()
});

const audioTranscribeRequestSchema = z.object({
  sessionId: z.string().min(1),
  chunkBase64: z.string().min(8),
  language: z.string().min(2).max(12).optional()
});

const stealthSetModeRequestSchema = z.object({
  enabled: z.boolean()
});

const settingsSaveRequestSchema = z.object({
  language: z.string().min(2).max(20).optional(),
  selectedAudioInputDeviceId: z.string().max(256).nullable().optional(),
  shortcuts: z
    .object({
      captureScreen: z.string().min(3).max(40).optional(),
      pushToTalk: z.string().min(3).max(40).optional(),
      toggleStealth: z.string().min(3).max(40).optional()
    })
    .optional(),
  geminiApiKey: z.string().max(2048).nullable().optional()
});

const diagnosticsSetLogLevelRequestSchema = z.object({
  level: z.enum(["debug", "info", "warn", "error"])
});

const featureFlagsSaveRequestSchema = z.object({
  providerMode: z.enum(["cloud", "local", "hybrid"]).optional(),
  localProviderEnabled: z.boolean().optional(),
  forceLocalOnly: z.boolean().optional(),
  stealthHardening: z.enum(["off", "safe", "strict"]).optional()
});

const autoUpdateSaveConfigRequestSchema = z.object({
  enabled: z.boolean().optional(),
  feedUrl: z.string().max(2048).nullable().optional(),
  channel: z.enum(["stable", "beta"]).optional(),
  allowPrerelease: z.boolean().optional()
});

const autoUpdateRollbackRequestSchema = z.object({
  channel: z.enum(["stable", "beta"]).optional()
});

/**
 * Registra handlers IPC com validacao de payload para reduzir entrada invalida no main process.
 */
function createNoopLogger() {
  return {
    debug: () => {},
    info: () => {},
    warn: () => {},
    error: () => {},
    getLevel: () => "info",
    setLevel: () => "info",
    getLogFilePath: () => "",
    getRecentLines: () => []
  };
}

/**
 * Traduz erros técnicos em mensagens acionáveis para o usuário final.
 */
function toActionableChatError(error) {
  const rawMessage = error instanceof Error ? error.message : "Erro desconhecido";
  const message = rawMessage.toLowerCase();

  if (message.includes("api key") || message.includes("unauth") || message.includes("401")) {
    return {
      errorCode: "AUTH_INVALID_API_KEY",
      errorMessage: rawMessage,
      actionableMessage: "Valide a API key Gemini em Settings e tente novamente.",
      retryable: false
    };
  }

  if (message.includes("no longer available") || message.includes("model not found") || (message.includes("404") && message.includes("model"))) {
    return {
      errorCode: "MODEL_NOT_AVAILABLE",
      errorMessage: rawMessage,
      actionableMessage: "Modelo Gemini indisponível. Atualize GEMINI_MODEL em Settings ou no .env para gemini-2.5-flash.",
      retryable: false
    };
  }

  if (message.includes("429") || message.includes("quota") || message.includes("rate limit") || message.includes("resource_exhausted")) {
    return {
      errorCode: "RATE_LIMIT",
      errorMessage: rawMessage,
      actionableMessage: "Limite de requisições atingido. Aguarde alguns segundos e tente novamente.",
      retryable: true
    };
  }

  if (message.includes("timeout") || message.includes("timed out") || message.includes("deadline")) {
    return {
      errorCode: "TIMEOUT",
      errorMessage: rawMessage,
      actionableMessage: "A resposta demorou mais que o esperado. Reenvie com um ASK mais curto.",
      retryable: true
    };
  }

  if (message.includes("network") || message.includes("fetch") || message.includes("enotfound")) {
    return {
      errorCode: "NETWORK",
      errorMessage: rawMessage,
      actionableMessage: "Falha de rede. Verifique conexão com a internet e tente novamente.",
      retryable: true
    };
  }

  if (message.includes("500") || message.includes("503") || message.includes("internal")) {
    return {
      errorCode: "SERVER",
      errorMessage: rawMessage,
      actionableMessage: "Instabilidade temporária do serviço. Tente novamente em instantes.",
      retryable: true
    };
  }

  if (message.includes("local_only_privacy_mode_active") || message.includes("fallback cloud bloqueado")) {
    return {
      errorCode: "LOCAL_ONLY_PRIVACY_MODE_ACTIVE",
      errorMessage: rawMessage,
      actionableMessage: "Modo local-only ativo. Ajuste runtime local (modelo/binario) ou desative force local-only nas Feature flags.",
      retryable: false
    };
  }

  return {
    errorCode: "UNKNOWN",
    errorMessage: rawMessage,
    actionableMessage: "Erro inesperado. Revise Settings e tente novamente.",
    retryable: true
  };
}

function setupIpcHandlers(dependencies) {
  const logger = dependencies?.logger || createNoopLogger();
  const settingsStore = dependencies?.settingsStore;
  const screenshotService = dependencies?.screenshotService;
  const shortcutService = dependencies?.shortcutService;
  const providerRouter = dependencies?.providerRouter;
  const sttAdapter = dependencies?.sttAdapter;
  const autoUpdateService = dependencies?.autoUpdateService;
  const stealthWindowService = dependencies?.stealthWindowService;
  const getMainWindow = dependencies?.getMainWindow;
  const emitRendererEvent = dependencies?.emitRendererEvent;

  // Persiste a opacidade do modo stealth entre ativações
  let savedStealthOpacity = process.platform === "win32" ? 0.22 : 0.3;

  if (!settingsStore || !screenshotService || !providerRouter || !sttAdapter || !autoUpdateService || !stealthWindowService || !emitRendererEvent) {
    throw new Error("IPC dependencies not provided.");
  }

  ipcMain.handle("desktop:ping", async (_event, payload) => {
    const parsed = pingRequestSchema.parse(payload ?? {});
    logger.debug("IPC desktop:ping", parsed);
    return {
      ok: true,
      timestampIso: parsed.timestampIso || new Date().toISOString()
    };
  });

  ipcMain.handle("screenshot:capture", async (_event, payload) => {
    const parsed = screenshotCaptureRequestSchema.parse(payload);
    logger.info("IPC screenshot:capture", parsed);
    return screenshotService.captureScreenshot({
      source: parsed.source,
      trigger: "manual"
    });
  });

  ipcMain.handle("screenshot:queue:get", async () => {
    logger.debug("IPC screenshot:queue:get");
    return {
      items: screenshotService.getQueue()
    };
  });

  ipcMain.handle("screenshot:queue:clear", async () => {
    const items = screenshotService.clearQueue();
    return {
      items,
      clearedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("prompt:presets:get", async () => {
    return {
      presets: getPromptPresets()
    };
  });

  ipcMain.handle("chat:ask", async (_event, payload) => {
    const parsed = chatAskRequestSchema.parse(payload);
    const requestId = randomUUID();
    logger.info("IPC chat:ask accepted", {
      requestId,
      sessionId: parsed.sessionId,
      askLength: parsed.ask.length,
      screenshotCount: parsed.screenshotIds?.length || 0,
      presetId: parsed.presetId || "ui-analysis"
    });

    void (async () => {
      const env = getEnvironmentConfig();
      const resolvedFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env);

      const apiKey = settingsStore.getGeminiApiKey();
      if (
        !apiKey &&
        resolvedFlags.effective.providerMode === "cloud" &&
        !resolvedFlags.effective.localProviderEnabled &&
        !resolvedFlags.effective.forceLocalOnly
      ) {
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: "MISSING_API_KEY",
          errorMessage: "Gemini API key nao configurada nas Settings.",
          actionableMessage: "Abra Settings, informe a API key Gemini e clique em Salvar configuracoes.",
          retryable: false,
          createdAtIso: new Date().toISOString()
        });
        return;
      }

      const availableScreenshots = screenshotService.getQueue();
      const selectedScreenshots = parsed.screenshotIds?.length
        ? availableScreenshots.filter((item) => parsed.screenshotIds.includes(item.captureId))
        : [];

      const promptBuild = buildPromptWithPreset({
        ask: parsed.ask,
        presetId: parsed.presetId
      });

      if (!promptBuild.ok) {
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: promptBuild.errorCode,
          errorMessage: promptBuild.errorMessage,
          actionableMessage: promptBuild.actionableMessage,
          retryable: promptBuild.retryable,
          createdAtIso: new Date().toISOString()
        });
        return;
      }

      try {
        await providerRouter.streamAskResponse({
          requestId,
          apiKey: resolvedFlags.effective.forceLocalOnly ? "" : apiKey,
          effectiveFlags: resolvedFlags.effective,
          ask: promptBuild.prompt,
          screenshots: selectedScreenshots,
          onEvent: (streamEvent) => emitRendererEvent("chat:stream-event", streamEvent)
        });
      } catch (error) {
        const mappedError = toActionableChatError(error);
        logger.error("ProviderRouter streaming failed", {
          requestId,
          message: mappedError.errorMessage,
          code: mappedError.errorCode
        });
        emitRendererEvent("chat:stream-event", {
          requestId,
          status: "error",
          errorCode: mappedError.errorCode,
          errorMessage: mappedError.errorMessage,
          actionableMessage: mappedError.actionableMessage,
          retryable: mappedError.retryable,
          createdAtIso: new Date().toISOString()
        });
      }
    })();

    return {
      requestId,
      status: "accepted"
    };
  });

  ipcMain.handle("audio:transcribe", async (_event, payload) => {
    const parsed = audioTranscribeRequestSchema.parse(payload);
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    logger.debug("IPC audio:transcribe", {
      sessionId: parsed.sessionId,
      language: parsed.language || "auto",
      providerMode: effectiveFlags.providerMode,
      forceLocalOnly: effectiveFlags.forceLocalOnly
    });

    try {
      return await sttAdapter.transcribe({
        sessionId: parsed.sessionId,
        chunkBase64: parsed.chunkBase64,
        language: parsed.language,
        apiKey: effectiveFlags.forceLocalOnly ? "" : settingsStore.getGeminiApiKey(),
        effectiveFlags
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "Falha desconhecida no STT";
      logger.error("IPC audio:transcribe failed", {
        sessionId: parsed.sessionId,
        message
      });
      return {
        text: `Falha de transcricao: ${message}`,
        isFinal: false
      };
    }
  });

  ipcMain.handle("stealth:set-mode", async (_event, payload) => {
    const parsed = stealthSetModeRequestSchema.parse(payload);
    const env = getEnvironmentConfig();
    const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
    logger.info("IPC stealth:set-mode", {
      enabled: parsed.enabled,
      hardening: effectiveFlags.stealthHardening
    });

    const applied = stealthWindowService.setStealthMode({
      enabled: parsed.enabled,
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity
    });

    emitRendererEvent("stealth:state-changed", {
      enabled: applied.enabled,
      hardening: effectiveFlags.stealthHardening,
      opacity: savedStealthOpacity,
      source: "ipc",
      appliedAtIso: applied.appliedAtIso
    });

    return {
      enabled: applied.enabled,
      opacity: savedStealthOpacity,
      appliedAtIso: applied.appliedAtIso
    };
  });

  ipcMain.handle("settings:get", async () => {
    logger.debug("IPC settings:get");
    return {
      settings: settingsStore.getPublicSettings()
    };
  });

  ipcMain.handle("settings:save", async (_event, payload) => {
    const parsed = settingsSaveRequestSchema.parse(payload ?? {});
    const settings = settingsStore.savePartial(parsed);
    if (shortcutService) {
      shortcutService.refreshShortcuts();
    }
    logger.info("IPC settings:save", {
      language: settings.language,
      hasGeminiApiKey: settings.hasGeminiApiKey
    });
    return {
      settings,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("settings:reset", async () => {
    const settings = settingsStore.reset();
    if (shortcutService) {
      shortcutService.refreshShortcuts();
    }
    logger.warn("IPC settings:reset applied");
    return {
      settings,
      resetAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("diagnostics:get", async () => {
    logger.debug("IPC diagnostics:get");
    return {
      logLevel: logger.getLevel(),
      logFilePath: logger.getLogFilePath(),
      recentLines: logger.getRecentLines(80)
    };
  });

  ipcMain.handle("diagnostics:set-log-level", async (_event, payload) => {
    const parsed = diagnosticsSetLogLevelRequestSchema.parse(payload);
    const logLevel = logger.setLevel(parsed.level);
    return {
      logLevel,
      updatedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("feature-flags:get", async () => {
    const persisted = settingsStore.getFeatureFlags();
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.debug("IPC feature-flags:get", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return resolved;
  });

  ipcMain.handle("feature-flags:save", async (_event, payload) => {
    const parsed = featureFlagsSaveRequestSchema.parse(payload ?? {});
    const normalizedPayload = {
      ...parsed,
      providerMode: parsed.forceLocalOnly ? "local" : parsed.providerMode,
      localProviderEnabled: parsed.forceLocalOnly ? true : parsed.localProviderEnabled
    };
    const persisted = settingsStore.saveFeatureFlags(normalizedPayload);
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.info("IPC feature-flags:save", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return {
      ...resolved,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("feature-flags:reset", async () => {
    const persisted = settingsStore.resetFeatureFlags();
    const env = getEnvironmentConfig();
    const resolved = resolveFeatureFlags(persisted, env);
    logger.warn("IPC feature-flags:reset", {
      persisted,
      effective: resolved.effective,
      source: resolved.source
    });
    return {
      ...resolved,
      resetAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("env:get", async () => {
    const env = getEnvironmentConfig();
    logger.debug("IPC env:get", env);
    return {
      env
    };
  });

  ipcMain.handle("auto-update:get-state", async () => {
    logger.debug("IPC auto-update:get-state");
    return {
      state: autoUpdateService.getState()
    };
  });

  ipcMain.handle("auto-update:save-config", async (_event, payload) => {
    const parsed = autoUpdateSaveConfigRequestSchema.parse(payload ?? {});
    const state = autoUpdateService.saveConfig({
      ...parsed,
      feedUrl: parsed.feedUrl === null ? "" : parsed.feedUrl
    });
    logger.info("IPC auto-update:save-config", {
      enabled: state.config.enabled,
      channel: state.config.channel,
      hasFeedUrl: Boolean(state.config.feedUrl)
    });
    return {
      state,
      savedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:check", async () => {
    logger.info("IPC auto-update:check");
    const state = await autoUpdateService.checkForUpdates();
    return {
      state,
      checkedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:download", async () => {
    logger.info("IPC auto-update:download");
    const state = await autoUpdateService.downloadUpdate();
    return {
      state,
      startedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:install", async () => {
    logger.warn("IPC auto-update:install");
    autoUpdateService.installUpdate();
    return {
      accepted: true,
      appliedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:rollback", async (_event, payload) => {
    const parsed = autoUpdateRollbackRequestSchema.parse(payload ?? {});
    logger.warn("IPC auto-update:rollback", {
      channel: parsed.channel || "previous"
    });
    const state = await autoUpdateService.rollbackUpdate(parsed);
    return {
      state,
      acceptedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("auto-update:confirm-health", async () => {
    logger.info("IPC auto-update:confirm-health");
    const state = autoUpdateService.confirmHealth();
    return {
      state,
      confirmedAtIso: new Date().toISOString()
    };
  });

  ipcMain.handle("app:quit", () => {
    logger.info("IPC app:quit — encerrando aplicacao");
    // process.exit bypasses all event handlers and quits immediately
    setImmediate(() => process.exit(0));
  });

  ipcMain.handle("window:minimize", () => {
    const win = (getMainWindow && getMainWindow()) || BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0];
    if (win && !win.isDestroyed()) win.minimize();
    logger.debug("IPC window:minimize");
  });

  ipcMain.handle("window:set-opacity", (_event, payload) => {
    const opacity = z.number().min(0.05).max(1).parse(payload?.opacity ?? 1);
    // Persiste para re-usar na próxima ativação do stealth
    savedStealthOpacity = opacity;
    const win = (getMainWindow && getMainWindow()) || BrowserWindow.getFocusedWindow() || BrowserWindow.getAllWindows()[0];
    if (win && !win.isDestroyed()) win.setOpacity(opacity);
    logger.debug("IPC window:set-opacity", { opacity, hasWin: Boolean(win) });
    return { opacity };
  });
}

module.exports = {
  setupIpcHandlers
};
