// Generated by GitHub Copilot
const fs = require("node:fs");
const path = require("node:path");
const { app } = require("electron");

const LEVEL_ORDER = {
  debug: 10,
  info: 20,
  warn: 30,
  error: 40
};

const DEFAULT_MAX_FILE_SIZE_BYTES = 512 * 1024;
const DEFAULT_MAX_FILES = 5;

function redactSecrets(value) {
  if (typeof value === "string") {
    return value;
  }

  if (!value || typeof value !== "object") {
    return value;
  }

  const secretKeys = ["apikey", "apiKey", "token", "authorization", "password", "secret"];
  const clone = Array.isArray(value) ? [...value] : { ...value };

  Object.keys(clone).forEach((key) => {
    const current = clone[key];

    if (secretKeys.some((candidate) => key.toLowerCase().includes(candidate.toLowerCase()))) {
      clone[key] = "[REDACTED]";
      return;
    }

    if (current && typeof current === "object") {
      clone[key] = redactSecrets(current);
    }
  });

  return clone;
}

function createLocalLogger(options = {}) {
  const logsDir = path.join(app.getPath("userData"), "logs");
  const logFilePath = path.join(logsDir, "desktop.log");
  const maxFileSizeBytes = options.maxFileSizeBytes || DEFAULT_MAX_FILE_SIZE_BYTES;
  const maxFiles = options.maxFiles || DEFAULT_MAX_FILES;

  let currentLevel = (options.level || "info").toLowerCase();
  if (!LEVEL_ORDER[currentLevel]) {
    currentLevel = "info";
  }

  function ensureLogsDir() {
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }
  }

  function rotateIfNeeded() {
    if (!fs.existsSync(logFilePath)) {
      return;
    }

    const stats = fs.statSync(logFilePath);
    if (stats.size < maxFileSizeBytes) {
      return;
    }

    for (let index = maxFiles - 1; index >= 1; index -= 1) {
      const from = `${logFilePath}.${index}`;
      const to = `${logFilePath}.${index + 1}`;

      if (fs.existsSync(from)) {
        if (index + 1 > maxFiles) {
          fs.rmSync(from, { force: true });
        } else {
          fs.renameSync(from, to);
        }
      }
    }

    fs.renameSync(logFilePath, `${logFilePath}.1`);
  }

  function shouldLog(level) {
    return LEVEL_ORDER[level] >= LEVEL_ORDER[currentLevel];
  }

  function write(level, message, meta) {
    if (!shouldLog(level)) {
      return;
    }

    ensureLogsDir();
    rotateIfNeeded();

    const safeMeta = meta ? redactSecrets(meta) : undefined;
    const serializedMeta = safeMeta ? ` | ${JSON.stringify(safeMeta)}` : "";
    const line = `${new Date().toISOString()} | ${level.toUpperCase()} | ${message}${serializedMeta}\n`;

    fs.appendFileSync(logFilePath, line, "utf-8");
  }

  function getRecentLines(limit = 120) {
    if (!fs.existsSync(logFilePath)) {
      return [];
    }

    const lines = fs.readFileSync(logFilePath, "utf-8").split("\n").filter(Boolean);
    return lines.slice(-Math.max(1, Math.min(limit, 500)));
  }

  return {
    getLogFilePath: () => logFilePath,
    getLevel: () => currentLevel,
    setLevel: (level) => {
      const next = String(level || "").toLowerCase();
      if (!LEVEL_ORDER[next]) {
        throw new Error("Invalid log level");
      }
      currentLevel = next;
      write("info", "Log level updated", { level: currentLevel });
      return currentLevel;
    },
    getRecentLines,
    debug: (message, meta) => write("debug", message, meta),
    info: (message, meta) => write("info", message, meta),
    warn: (message, meta) => write("warn", message, meta),
    error: (message, meta) => write("error", message, meta)
  };
}

module.exports = {
  createLocalLogger
};
