// Generated by GitHub Copilot
const { app, BrowserWindow } = require("electron");
const path = require("node:path");
const { getEnvironmentConfig } = require("./env-config.cjs");
const { resolveFeatureFlags } = require("./feature-flags.cjs");
const { setupIpcHandlers } = require("./ipc.cjs");
const { createLocalLogger } = require("./logger.cjs");
const { createSettingsStore } = require("./settings-store.cjs");
const { createScreenshotService } = require("./screenshot-service.cjs");
const { createShortcutService } = require("./shortcut-service.cjs");
const { createGeminiProvider } = require("./gemini-provider.cjs");
const { createSttAdapter } = require("./stt-adapter.cjs");
const { createStealthWindowService } = require("./stealth-window-service.cjs");
const { createLocalProvider } = require("./local-provider.cjs");
const { createProviderRouter } = require("./provider-router.cjs");
const { createLlamaServerManager } = require("./llama-server-manager.cjs");
const { createWhisperCliManager } = require("./whisper-cli-manager.cjs");
const { createModelManager } = require("./model-manager.cjs");
const { createAutoUpdateService } = require("./auto-update-service.cjs");

let logger;
let shortcutService;
let mainWindowRef;
let llamaServerManager;
let whisperCliManager;
let modelManager;
let autoUpdateService;

function emitToAllWindows(channel, payload) {
  BrowserWindow.getAllWindows().forEach((windowRef) => {
    windowRef.webContents.send(channel, payload);
  });
}

/**
 * Cria a janela principal com isolamento de contexto habilitado.
 * Seguranca: nodeIntegration desabilitado para reduzir superficie de ataque no renderer.
 */
function createWindow() {
  logger.info("Creating main browser window");

  mainWindowRef = new BrowserWindow({
    width: 1280,
    height: 800,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true
    }
  });

  const url = process.env.VITE_DEV_SERVER_URL || "http://localhost:5173";
  logger.debug("Loading renderer URL", { url });
  mainWindowRef.loadURL(url);
  mainWindowRef.once("ready-to-show", () => {
    mainWindowRef.show();
  });
  mainWindowRef.on("closed", () => {
    mainWindowRef = undefined;
  });
}

app.whenReady().then(() => {
  logger = createLocalLogger({
    level: process.env.DESKTOP_LOG_LEVEL || "info"
  });
  const settingsStore = createSettingsStore();
  const envConfig = getEnvironmentConfig();
  const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), envConfig).effective;
  const screenshotService = createScreenshotService({
    logger,
    onQueueUpdated: (queue) => {
      emitToAllWindows("screenshot:queue-updated", { items: queue });
    }
  });

  const geminiProvider = createGeminiProvider({ logger });
  modelManager = createModelManager({
    logger,
    allowNetworkDownloads: !effectiveFlags.forceLocalOnly
  });
  void modelManager.ensureConfiguredModels();
  llamaServerManager = createLlamaServerManager({
    logger,
    modelManager
  });
  const localProvider = createLocalProvider({
    logger,
    llamaServerManager
  });
  const providerRouter = createProviderRouter({
    logger,
    geminiProvider,
    localProvider
  });
  whisperCliManager = createWhisperCliManager({
    logger,
    modelManager
  });
  const sttAdapter = createSttAdapter({
    logger,
    whisperCliManager
  });
  autoUpdateService = createAutoUpdateService({
    logger,
    app,
    settingsStore,
    emitRendererEvent: emitToAllWindows
  });
  const stealthWindowService = createStealthWindowService({
    logger,
    getMainWindow: () => mainWindowRef
  });
  shortcutService = createShortcutService({
    logger,
    settingsStore,
    screenshotService,
    stealthWindowService,
    emitRendererEvent: emitToAllWindows
  });

  logger.info("Application ready", {
    platform: process.platform,
    arch: process.arch,
    pid: process.pid
  });

  setupIpcHandlers({
    logger,
    settingsStore,
    screenshotService,
    shortcutService,
    providerRouter,
    sttAdapter,
    autoUpdateService,
    stealthWindowService,
    emitRendererEvent: emitToAllWindows
  });
  shortcutService.refreshShortcuts();
  createWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      logger.info("Recreating main window after activate");
      createWindow();
    }
  });
});

app.on("window-all-closed", () => {
  logger.info("All windows closed");
  if (process.platform !== "darwin") {
    if (llamaServerManager) {
      llamaServerManager.stop();
    }
    if (whisperCliManager) {
      whisperCliManager.stop();
    }
    if (shortcutService) {
      shortcutService.dispose();
    }
    logger.info("Quitting application");
    app.quit();
  }
});

app.on("render-process-gone", (_event, webContents, details) => {
  logger.error("Renderer process gone", {
    reason: details.reason,
    exitCode: details.exitCode,
    id: webContents.id
  });
});
