// Generated by GitHub Copilot
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const https = require("node:https");
const http = require("node:http");
const { app } = require("electron");
const {
  DEFAULT_WHISPER_BASE_URL,
  DEFAULT_WHISPER_SMALL_URL,
  DEFAULT_WHISPER_MEDIUM_URL
} = require("./transcription-packs.cjs");

function streamHashSha256(filePath) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash("sha256");
    const input = fs.createReadStream(filePath);
    input.on("error", reject);
    input.on("data", (chunk) => hash.update(chunk));
    input.on("end", () => resolve(hash.digest("hex")));
  });
}

function ensureDirectory(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function downloadToFile(url, destinationPath, onProgress) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const client = parsed.protocol === "http:" ? http : https;

    const request = client.get(parsed, (response) => {
      if (
        response.statusCode &&
        response.statusCode >= 300 &&
        response.statusCode < 400 &&
        response.headers.location
      ) {
        response.resume();
        downloadToFile(response.headers.location, destinationPath, onProgress)
          .then(resolve)
          .catch(reject);
        return;
      }

      if (response.statusCode !== 200) {
        response.resume();
        reject(new Error(`Download falhou com status ${response.statusCode || "desconhecido"}`));
        return;
      }

      const total = Number(response.headers["content-length"] || 0);
      let received = 0;
      const output = fs.createWriteStream(destinationPath);
      response.pipe(output);

      response.on("data", (chunk) => {
        received += chunk.length;
        if (typeof onProgress === "function") {
          const percent = total > 0 ? Math.min(99, Math.round((received / total) * 100)) : null;
          onProgress({
            receivedBytes: received,
            totalBytes: total || null,
            percent,
            message: total
              ? `Baixando… ${percent}%`
              : `Baixando… ${Math.round(received / (1024 * 1024))} MB`
          });
        }
      });

      output.on("finish", () => {
        output.close();
        if (typeof onProgress === "function") {
          onProgress({
            receivedBytes: received,
            totalBytes: total || received,
            percent: 100,
            message: "Download concluído"
          });
        }
        resolve();
      });

      output.on("error", (error) => {
        output.close();
        reject(error);
      });
    });

    request.on("error", reject);
  });
}

/**
 * Gerencia modelos locais (download, caminho efetivo e validação por checksum).
 */
function createModelManager(options) {
  const logger = options?.logger || {
    info: () => {},
    warn: () => {},
    error: () => {}
  };
  const allowNetworkDownloads = options?.allowNetworkDownloads !== false;

  const modelsDir = path.join(app.getPath("userData"), "runtime", "models");
  ensureDirectory(modelsDir);

  const registry = {
    llama: {
      key: "llama",
      fileName: "llama-model.gguf",
      configuredPath: process.env.LLAMA_MODEL_PATH || "",
      configuredUrl: process.env.LLAMA_MODEL_URL || "",
      configuredSha256: (process.env.LLAMA_MODEL_SHA256 || "").toLowerCase()
    },
    whisper: {
      key: "whisper",
      fileName: "ggml-base.bin",
      configuredPath: process.env.WHISPER_MODEL_PATH || "",
      configuredUrl: process.env.WHISPER_MODEL_URL || DEFAULT_WHISPER_BASE_URL,
      configuredSha256: (process.env.WHISPER_MODEL_SHA256 || "").toLowerCase()
    },
    "whisper-small": {
      key: "whisper-small",
      fileName: "ggml-small.bin",
      configuredPath: process.env.WHISPER_SMALL_MODEL_PATH || "",
      configuredUrl: process.env.WHISPER_SMALL_MODEL_URL || DEFAULT_WHISPER_SMALL_URL,
      configuredSha256: (process.env.WHISPER_SMALL_MODEL_SHA256 || "").toLowerCase()
    },
    "whisper-medium": {
      key: "whisper-medium",
      fileName: "ggml-medium.bin",
      configuredPath: process.env.WHISPER_MEDIUM_MODEL_PATH || "",
      configuredUrl: process.env.WHISPER_MEDIUM_MODEL_URL || DEFAULT_WHISPER_MEDIUM_URL,
      configuredSha256: (process.env.WHISPER_MEDIUM_MODEL_SHA256 || "").toLowerCase()
    }
  };

  const modelState = {
    llama: {
      state: "idle",
      filePath: "",
      sha256: "",
      lastValidatedAtIso: "",
      lastError: ""
    },
    whisper: {
      state: "idle",
      filePath: "",
      sha256: "",
      lastValidatedAtIso: "",
      lastError: ""
    },
    "whisper-small": {
      state: "idle",
      filePath: "",
      sha256: "",
      lastValidatedAtIso: "",
      lastError: ""
    },
    "whisper-medium": {
      state: "idle",
      filePath: "",
      sha256: "",
      lastValidatedAtIso: "",
      lastError: ""
    }
  };

  function getDefaultPath(modelKey) {
    return path.join(modelsDir, registry[modelKey].fileName);
  }

  function resolveConfiguredOrDefaultPath(modelKey) {
    const configuredPath = registry[modelKey].configuredPath;
    if (configuredPath && fs.existsSync(configuredPath)) {
      return configuredPath;
    }

    const defaultPath = getDefaultPath(modelKey);
    if (fs.existsSync(defaultPath)) {
      return defaultPath;
    }

    return configuredPath || defaultPath;
  }

  async function validateChecksum(modelKey, filePath) {
    const expected = registry[modelKey].configuredSha256;
    const actual = await streamHashSha256(filePath);

    if (expected && actual !== expected) {
      throw new Error(`Checksum invalido para ${modelKey}. expected=${expected} actual=${actual}`);
    }

    return actual;
  }

  async function ensureModel(modelKey, ensureOptions = {}) {
    const descriptor = registry[modelKey];
    if (!descriptor) {
      return {
        state: "error",
        filePath: "",
        sha256: "",
        lastValidatedAtIso: "",
        lastError: `Modelo desconhecido: ${modelKey}`,
        model: modelKey
      };
    }

    const state = modelState[modelKey];
    state.state = "checking";
    state.lastError = "";
    const onProgress = ensureOptions.onProgress;

    try {
      let filePath = resolveConfiguredOrDefaultPath(modelKey);
      const exists = fs.existsSync(filePath);

      if (!exists) {
        if (!allowNetworkDownloads) {
          state.state = "unavailable";
          state.filePath = filePath;
          state.lastError = `Modo local-only ativo: download de modelo ${modelKey} bloqueado por privacidade.`;
          return {
            ...state,
            model: modelKey
          };
        }

        if (!descriptor.configuredUrl) {
          state.state = "unavailable";
          state.filePath = filePath;
          state.lastError = `Modelo ${modelKey} nao encontrado e URL de download nao configurada.`;
          return {
            ...state,
            model: modelKey
          };
        }

        const destinationPath = descriptor.configuredPath || getDefaultPath(modelKey);
        ensureDirectory(path.dirname(destinationPath));
        state.state = "downloading";
        logger.info("Downloading model", {
          model: modelKey,
          url: descriptor.configuredUrl,
          destinationPath
        });
        await downloadToFile(descriptor.configuredUrl, destinationPath, onProgress);
        filePath = destinationPath;
      }

      const checksum = await validateChecksum(modelKey, filePath);
      state.state = "ready";
      state.filePath = filePath;
      state.sha256 = checksum;
      state.lastValidatedAtIso = new Date().toISOString();
      state.lastError = "";

      return {
        ...state,
        model: modelKey
      };
    } catch (error) {
      state.state = "error";
      state.lastError = error instanceof Error ? error.message : "Falha desconhecida";
      logger.error("Model manager failure", {
        model: modelKey,
        message: state.lastError
      });
      return {
        ...state,
        model: modelKey
      };
    }
  }

  async function ensureConfiguredModels() {
    const llama = await ensureModel("llama");
    // Whisper: no boot auto-download (UI de pacotes dispara o download).
    const whisperPath = resolveModelPath("whisper") || resolveModelPath("whisper-small");
    if (whisperPath) {
      const key = resolveModelPath("whisper") ? "whisper" : "whisper-small";
      await ensureModel(key);
    }
    return {
      llama,
      whisper: { ...modelState.whisper }
    };
  }

  function resolveModelPath(modelKey) {
    const state = modelState[modelKey];
    if (state?.filePath && fs.existsSync(state.filePath)) {
      return state.filePath;
    }

    if (!registry[modelKey]) {
      return "";
    }

    const resolved = resolveConfiguredOrDefaultPath(modelKey);
    return fs.existsSync(resolved) ? resolved : "";
  }

  function getStatus() {
    return {
      llama: { ...modelState.llama },
      whisper: { ...modelState.whisper },
      "whisper-small": { ...modelState["whisper-small"] },
      "whisper-medium": { ...modelState["whisper-medium"] }
    };
  }

  return {
    ensureModel,
    ensureConfiguredModels,
    resolveModelPath,
    getStatus
  };
}

module.exports = {
  createModelManager
};
