// Generated by GitHub Copilot
const { contextBridge, ipcRenderer } = require("electron");

const screenshotQueueUpdatedChannel = "screenshot:queue-updated";
const chatStreamEventChannel = "chat:stream-event";
const stealthStateChangedChannel = "stealth:state-changed";
const autoUpdateEventChannel = "auto-update:event";

/**
 * Exposicao controlada para o renderer.
 * Seguranca: apenas APIs explicitamente permitidas devem ser exportadas.
 */
contextBridge.exposeInMainWorld("desktopApi", {
  version: "0.1.0",
  ping: (payload) => ipcRenderer.invoke("desktop:ping", payload),
  captureScreenshot: (payload) => ipcRenderer.invoke("screenshot:capture", payload),
  getScreenshotQueue: () => ipcRenderer.invoke("screenshot:queue:get"),
  clearScreenshotQueue: () => ipcRenderer.invoke("screenshot:queue:clear"),
  getPromptPresets: () => ipcRenderer.invoke("prompt:presets:get"),
  submitAsk: (payload) => ipcRenderer.invoke("chat:ask", payload),
  onChatStreamEvent: (listener) => {
    const wrappedListener = (_event, payload) => listener(payload);
    ipcRenderer.on(chatStreamEventChannel, wrappedListener);
    return () => {
      ipcRenderer.removeListener(chatStreamEventChannel, wrappedListener);
    };
  },
  transcribeAudioChunk: (payload) => ipcRenderer.invoke("audio:transcribe", payload),
  setStealthMode: (payload) => ipcRenderer.invoke("stealth:set-mode", payload),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (payload) => ipcRenderer.invoke("settings:save", payload),
  resetSettings: () => ipcRenderer.invoke("settings:reset"),
  getDiagnostics: () => ipcRenderer.invoke("diagnostics:get"),
  setLogLevel: (payload) => ipcRenderer.invoke("diagnostics:set-log-level", payload),
  getFeatureFlags: () => ipcRenderer.invoke("feature-flags:get"),
  saveFeatureFlags: (payload) => ipcRenderer.invoke("feature-flags:save", payload),
  resetFeatureFlags: () => ipcRenderer.invoke("feature-flags:reset"),
  getEnvironment: () => ipcRenderer.invoke("env:get"),
  getAutoUpdateState: () => ipcRenderer.invoke("auto-update:get-state"),
  saveAutoUpdateConfig: (payload) => ipcRenderer.invoke("auto-update:save-config", payload),
  checkForAutoUpdate: () => ipcRenderer.invoke("auto-update:check"),
  downloadAutoUpdate: () => ipcRenderer.invoke("auto-update:download"),
  installAutoUpdate: () => ipcRenderer.invoke("auto-update:install"),
  rollbackAutoUpdate: (payload) => ipcRenderer.invoke("auto-update:rollback", payload),
  confirmAutoUpdateHealth: () => ipcRenderer.invoke("auto-update:confirm-health"),
  onScreenshotQueueUpdated: (listener) => {
    const wrappedListener = (_event, payload) => listener(payload);
    ipcRenderer.on(screenshotQueueUpdatedChannel, wrappedListener);
    return () => {
      ipcRenderer.removeListener(screenshotQueueUpdatedChannel, wrappedListener);
    };
  },
  onStealthStateChanged: (listener) => {
    const wrappedListener = (_event, payload) => listener(payload);
    ipcRenderer.on(stealthStateChangedChannel, wrappedListener);
    return () => {
      ipcRenderer.removeListener(stealthStateChangedChannel, wrappedListener);
    };
  },
  onAutoUpdateEvent: (listener) => {
    const wrappedListener = (_event, payload) => listener(payload);
    ipcRenderer.on(autoUpdateEventChannel, wrappedListener);
    return () => {
      ipcRenderer.removeListener(autoUpdateEventChannel, wrappedListener);
    };
  }
});
