// Generated by GitHub Copilot
const test = require("node:test");
const assert = require("node:assert/strict");
const { getPromptPresets, buildPromptWithPreset } = require("./prompt-presets.cjs");

test("getPromptPresets retorna metadados sem template", () => {
  const presets = getPromptPresets();
  assert.ok(Array.isArray(presets));
  assert.ok(presets.length > 0);
  assert.ok(!Object.prototype.hasOwnProperty.call(presets[0], "template"));
});

test("buildPromptWithPreset bloqueia segredo em texto puro", () => {
  const result = buildPromptWithPreset({
    ask: "api_key=abcdef123",
    presetId: "ui-analysis"
  });

  assert.equal(result.ok, false);
  assert.equal(result.errorCode, "PROMPT_GUARDRAIL_BLOCKED");
});

test("buildPromptWithPreset aplica preset default quando id não existe", () => {
  const result = buildPromptWithPreset({
    ask: "Analise esta interface",
    presetId: "inexistente"
  });

  assert.equal(result.ok, true);
  assert.equal(result.presetId, "code-solver");
  assert.match(result.prompt, /Regras globais/);
});

test("buildPromptWithPreset aceita ask vazio para analise de captura", () => {
  const result = buildPromptWithPreset({
    ask: "",
    presetId: "screenshot-analysis",
    hasScreenshots: true,
    hasAudio: false,
    defaultCodeLanguage: "java"
  });

  assert.equal(result.ok, true);
  assert.equal(result.presetId, "screenshot-analysis");
  assert.match(result.prompt, /captura de tela/i);
  assert.match(result.prompt, /LeetCode/i);
  assert.match(result.prompt, /LINGUAGEM PARA CODIGO/i);
  assert.match(result.prompt, /use java \(configuracao padrao do app\)/i);
});

test("buildPromptWithPreset resolve preset de audio sem texto do usuario", () => {
  const result = buildPromptWithPreset({
    ask: "",
    hasScreenshots: false,
    hasAudio: true
  });

  assert.equal(result.ok, true);
  assert.equal(result.presetId, "audio-analysis");
  assert.match(result.prompt, /audio gravado/i);
});
