// Generated by GitHub Copilot

const PROMPT_PRESETS = [
  {
    id: "code-solver",
    title: "Resolver problema de codigo",
    description: "Fornece solucao otimizada para problemas de algoritmo (LeetCode, HackerRank etc.).",
    template:
      "Voce e um assistente tecnico. Analise a imagem e identifique o conteudo principal.\n" +
      "- Se for um problema de ALGORITMO ou CODIGO (LeetCode, HackerRank, entrevista etc.): escreva APENAS a solucao em codigo completo e funcional (use a linguagem visivel ou Python). Depois, em 1 linha, informe a complexidade (ex: 'O(n) tempo, O(1) espaco'). NAO descreva a tela. NAO mencione login. NAO analise a interface.\n" +
      "- Se for uma QUESTAO de multipla escolha: responda somente a letra correta e 1 linha de justificativa.\n" +
      "- Se for uma PERGUNTA DISCURSIVA: responda em no maximo 3 linhas objetivas.\n" +
      "Responda sempre no idioma da questao. Contexto adicional do usuario (pode estar vazio): {{ASK}}"
  },
  {
    id: "ui-analysis",
    title: "Analise de UI",
    description: "Avalia clareza visual, problemas de UX e melhorias objetivas.",
    template:
      "Analise a interface mostrada na(s) imagem(ns) e responda em 3 blocos: 1) Achados principais, 2) Riscos de UX, 3) Acoes recomendadas de curto prazo. Contexto adicional do usuario: {{ASK}}"
  },
  {
    id: "error-diagnosis",
    title: "Diagnostico de erro",
    description: "Foca em causa raiz, hipótese e próximos passos de depuração.",
    template:
      "Com base na(s) imagem(ns), faca diagnostico tecnico do problema em formato: 1) Sintoma observado, 2) Causas provaveis (ordem de prioridade), 3) Checklist de verificacao. Contexto adicional do usuario: {{ASK}}"
  },
  {
    id: "concise-summary",
    title: "Resumo conciso",
    description: "Gera resumo enxuto para leitura rápida.",
    template:
      "Resuma o conteudo da(s) imagem(ns) em ate 8 bullets objetivos, destacando informacoes acionaveis. Contexto adicional do usuario: {{ASK}}"
  }
];

const DEFAULT_PRESET_ID = "code-solver";

function getPromptPresets() {
  return PROMPT_PRESETS.map((item) => ({
    id: item.id,
    title: item.title,
    description: item.description
  }));
}

/**
 * Bloqueia prompts que tentem incluir segredos em claro.
 */
function validatePromptGuardrails(ask) {
  const normalized = String(ask || "").trim();

  if (normalized.length < 3) {
    return {
      ok: false,
      errorCode: "PROMPT_GUARDRAIL_BLOCKED",
      errorMessage: "Instrucao ASK muito curta para analise confiavel.",
      actionableMessage: "Descreva melhor o objetivo da analise antes de enviar.",
      retryable: false
    };
  }

  const secretPattern = /(api[_-]?key|password|token|secret)\s*[:=]\s*\S+/i;
  if (secretPattern.test(normalized)) {
    return {
      ok: false,
      errorCode: "PROMPT_GUARDRAIL_BLOCKED",
      errorMessage: "Prompt parece conter segredo em texto puro.",
      actionableMessage: "Remova credenciais do texto e tente novamente.",
      retryable: true
    };
  }

  return { ok: true };
}

/**
 * Aplica preset e guardrails para gerar prompt final enviado ao provider.
 */
function buildPromptWithPreset(input) {
  const guardrailResult = validatePromptGuardrails(input.ask);
  if (!guardrailResult.ok) {
    return guardrailResult;
  }

  const preset =
    PROMPT_PRESETS.find((item) => item.id === input.presetId) ||
    PROMPT_PRESETS.find((item) => item.id === DEFAULT_PRESET_ID);

  const ask = String(input.ask || "").trim();
  const prompt =
    "Regras de resposta: seja objetivo, nao invente dados, explicite incertezas e nunca exponha segredos.\n\n" +
    preset.template.replace("{{ASK}}", ask);

  return {
    ok: true,
    prompt,
    presetId: preset.id
  };
}

module.exports = {
  getPromptPresets,
  buildPromptWithPreset
};
