// Generated by GitHub Copilot
const { DEFAULT_CODE_LANGUAGE, normalizeCodeLanguage } = require("./code-language-options.cjs");

const PROMPT_PRESETS = [
  {
    id: "code-solver",
    title: "Resolver problema de codigo",
    description: "Foco em algoritmos e questoes tecnicas com codigo.",
    template:
      "Analise a imagem com foco em programacao/algoritmos.\n" +
      "LINGUAGEM PADRAO PARA CODIGO: {{DEFAULT_CODE_LANGUAGE}}.\n" +
      "- LeetCode/HackerRank/entrevista: duas solucoes em {{DEFAULT_CODE_LANGUAGE}} (simples + eficiente), comentarios nas decisoes, Big-O tempo e espaco para cada.\n" +
      "- Multipla escolha: letra correta + justificativa em 1-2 frases.\n" +
      "- Dissertativa tecnica: tema + resposta breve e correta.\n" +
      "Priorize corretude. Nao descreva a UI do app AIGA. Contexto do usuario: {{ASK}}"
  },
  {
    id: "ui-analysis",
    title: "Analise de UI",
    description: "Avalia clareza visual, problemas de UX e melhorias objetivas.",
    template:
      "Analise a interface na captura de tela. Estrutura obrigatoria:\n" +
      "1) Contexto (tipo de tela/produto em 1-2 frases)\n" +
      "2) Achados principais (bullets objetivos)\n" +
      "3) Riscos de UX ou acessibilidade\n" +
      "4) Acoes recomendadas priorizadas (curto prazo)\n" +
      "Baseie-se apenas no visivel. Nao invente elementos. Contexto do usuario: {{ASK}}"
  },
  {
    id: "error-diagnosis",
    title: "Diagnostico de erro",
    description: "Foca em causa raiz, hipótese e próximos passos de depuração.",
    template:
      "Diagnostico tecnico a partir da captura (erro, log, console, build, IDE):\n" +
      "1) Sintoma observado (literal do que aparece)\n" +
      "2) Causas provaveis (ordenadas por probabilidade)\n" +
      "3) Passos de verificacao/correcao (checklist acionavel)\n" +
      "4) Prevencao (1-2 linhas, se aplicavel)\n" +
      "Se codigo de exemplo for necessario, use {{DEFAULT_CODE_LANGUAGE}}. Contexto do usuario: {{ASK}}"
  },
  {
    id: "concise-summary",
    title: "Resumo conciso",
    description: "Gera resumo enxuto para leitura rápida.",
    template:
      "Resuma o conteudo visivel na captura em ate 8 bullets:\n" +
      "- Fatos e numeros relevantes\n" +
      "- Decisoes ou pendencias\n" +
      "- Proximo passo sugerido (1 bullet final)\n" +
      "Sem narrativa longa. Contexto do usuario: {{ASK}}"
  },
  {
    id: "screenshot-analysis",
    title: "Analise de captura rapida",
    description: "Captura rapida (Ctrl+E): responde ao que o usuario esta vendo na tela.",
    template:
      "Voce analisa uma CAPTURA DE TELA enviada pelo usuario (captura rapida). O objetivo e ajudar com o que ele esta vendo AGORA.\n\n" +
      "LINGUAGEM PARA CODIGO — ordem de prioridade:\n" +
      "1) Se a captura ja indicar linguagem (seletor no LeetCode/HackerRank/Codeforces, aba ativa no editor, syntax highlighting, nome de arquivo .java/.py etc.), use ESSA linguagem nas solucoes.\n" +
      "2) Caso contrario, use {{DEFAULT_CODE_LANGUAGE}} (configuracao padrao do app).\n" +
      "3) Se o enunciado exigir linguagem explicita, respeite o enunciado acima de tudo.\n" +
      "Inicie a resposta de codigo com 1 linha informando qual linguagem foi escolhida e por que.\n\n" +
      "PASSO 1 — Classifique o conteudo (uma categoria principal):\n" +
      "A) Problema de algoritmo/codigo (LeetCode, HackerRank, Codeforces, entrevista, editor com enunciado)\n" +
      "B) Questao objetiva (multipla escolha, V/F, quiz)\n" +
      "C) Questao dissertativa/teorica (prova, forum, documentacao)\n" +
      "D) Erro tecnico (stack trace, console, build, runtime, IDE)\n" +
      "E) Interface/UI (layout, UX, produto)\n" +
      "F) Texto/documento generico (email, chat, slide, planilha)\n" +
      "G) Outro (descreva em 1 linha)\n\n" +
      "PASSO 2 — Responda conforme a categoria:\n\n" +
      "A) ALGORITMO / LEETCODE:\n" +
      "- Extraia o enunciado visivel na captura.\n" +
      "- Entregue DUAS solucoes completas na linguagem escolhida (regra acima):\n" +
      "  1) Solucao mais SIMPLES (clareza e corretude primeiro), com comentarios nas decisoes importantes.\n" +
      "  2) Solucao mais EFICIENTE (melhor complexidade pratica), com comentarios nas decisoes importantes.\n" +
      "- Para CADA solucao: complexidade de TEMPO e de ESPACO (Big-O).\n" +
      "- Valide restricoes do enunciado; nao invente casos de teste ocultos.\n\n" +
      "B) QUESTAO OBJETIVA:\n" +
      "- Resposta: letra/opcao correta (ou 'incerto' se ilegivel).\n" +
      "- Justificativa precisa em 1-2 frases.\n\n" +
      "C) QUESTAO DISSERTATIVA/TEORICA:\n" +
      "- Identifique o tema com precisao.\n" +
      "- Resposta objetiva, CORRETA e breve (priorize acerto sobre extensao).\n" +
      "- Maximo 5-8 linhas, salvo pedido contrario no contexto do usuario.\n\n" +
      "D) ERRO TECNICO:\n" +
      "- Sintoma, causa provavel, correcao em passos.\n\n" +
      "E) UI/UX:\n" +
      "- Achados, riscos, acoes recomendadas (formato curto).\n\n" +
      "F/G) GENERICO:\n" +
      "- O que importa na tela + resposta direta ao pedido implicito do usuario.\n\n" +
      "REGRAS GERAIS:\n" +
      "- Priorize CORRETUDE; declare incerteza se faltar evidencia na imagem.\n" +
      "- Nao descreva login, chrome da aplicacao AIGA ou elementos irrelevantes.\n" +
      "- Use apenas texto e elementos visiveis na captura.\n" +
      "- Responda no idioma do enunciado/pergunta na imagem.\n\n" +
      "Contexto adicional do usuario (pode estar vazio): {{ASK}}"
  },
  {
    id: "audio-analysis",
    title: "Analise de audio",
    description: "Interpreta gravacao de voz e responde perguntas ou pedidos do usuario.",
    template:
      "Voce recebeu um audio gravado pelo usuario.\n" +
      "1) Compreenda perguntas, pedidos e contexto falado.\n" +
      "2) Responda de forma direta e util (solucao, explicacao ou resumo).\n" +
      "3) Se for duvida tecnica com codigo, use {{DEFAULT_CODE_LANGUAGE}}.\n" +
      "4) Se ambiguo ou incompleto, indique lacunas e a melhor hipotese.\n" +
      "Priorize corretude e objetividade. Contexto adicional do usuario: {{ASK}}"
  }
];

const DEFAULT_PRESET_ID = "code-solver";
const MEDIA_PRESET_IDS = new Set(["screenshot-analysis", "audio-analysis"]);
const MEDIA_ONLY_ASK_PLACEHOLDER = "(sem contexto adicional — use apenas o anexo)";

const GLOBAL_RESPONSE_RULES =
  "Regras globais: seja objetivo, priorize corretude, nao invente dados, explicite incertezas, nunca exponha segredos.\n\n";

function getPromptPresets() {
  return PROMPT_PRESETS.map((item) => ({
    id: item.id,
    title: item.title,
    description: item.description
  }));
}

function isMediaOnlyPreset(presetId) {
  return MEDIA_PRESET_IDS.has(presetId);
}

function validatePromptGuardrails(ask, options) {
  const normalized = String(ask || "").trim();
  if (options?.allowEmptyAsk) {
    return { ok: true };
  }

  if (normalized.length < 3) {
    return {
      ok: false,
      errorCode: "PROMPT_GUARDRAIL_BLOCKED",
      errorMessage: "Instrucao ASK muito curta para analise confiavel.",
      actionableMessage: "Descreva melhor o objetivo da analise antes de enviar.",
      retryable: false
    };
  }

  const secretPattern = /(api[_-]?key|password|token|secret)\s*[:=]\s*\S+/i;
  if (secretPattern.test(normalized)) {
    return {
      ok: false,
      errorCode: "PROMPT_GUARDRAIL_BLOCKED",
      errorMessage: "Prompt parece conter segredo em texto puro.",
      actionableMessage: "Remova credenciais do texto e tente novamente.",
      retryable: true
    };
  }

  return { ok: true };
}

function resolvePresetId(input) {
  if (input.presetId) {
    return input.presetId;
  }
  if (input.hasAudio && !input.hasScreenshots) {
    return "audio-analysis";
  }
  if (input.hasScreenshots) {
    return "screenshot-analysis";
  }
  return DEFAULT_PRESET_ID;
}

function applyTemplateVariables(template, variables) {
  let result = template;
  Object.entries(variables).forEach(([key, value]) => {
    result = result.split(`{{${key}}}`).join(String(value));
  });
  return result;
}

function buildPromptWithPreset(input) {
  const presetId = resolvePresetId(input);
  const mediaOnly = isMediaOnlyPreset(presetId);
  const guardrailResult = validatePromptGuardrails(input.ask, { allowEmptyAsk: mediaOnly });
  if (!guardrailResult.ok) {
    return guardrailResult;
  }

  const preset =
    PROMPT_PRESETS.find((item) => item.id === presetId) ||
    PROMPT_PRESETS.find((item) => item.id === DEFAULT_PRESET_ID);

  const userAsk = String(input.ask || "").trim();
  const ask = userAsk || (mediaOnly ? MEDIA_ONLY_ASK_PLACEHOLDER : "");
  const defaultCodeLanguage = normalizeCodeLanguage(
    input.defaultCodeLanguage || DEFAULT_CODE_LANGUAGE
  );

  const body = applyTemplateVariables(preset.template, {
    ASK: ask,
    DEFAULT_CODE_LANGUAGE: defaultCodeLanguage
  });

  const prompt = GLOBAL_RESPONSE_RULES + body;

  return {
    ok: true,
    prompt,
    presetId: preset.id
  };
}

module.exports = {
  getPromptPresets,
  buildPromptWithPreset,
  resolvePresetId,
  isMediaOnlyPreset,
  MEDIA_ONLY_ASK_PLACEHOLDER
};
