// Generated by GitHub Copilot

/**
 * Roteia requests de chat entre providers cloud e local conforme flags efetivas.
 */
function createProviderRouter(dependencies) {
  const logger = dependencies?.logger || {
    info: () => {},
    warn: () => {}
  };
  const geminiProvider = dependencies?.geminiProvider;
  const localProvider = dependencies?.localProvider;

  if (!geminiProvider || !localProvider) {
    throw new Error("ProviderRouter requires geminiProvider and localProvider.");
  }

  function resolveStrategy(effectiveFlags, hasApiKey) {
    if (effectiveFlags.forceLocalOnly) {
      return "local-only";
    }

    if (effectiveFlags.providerMode === "local") {
      return "local-only";
    }

    if (effectiveFlags.providerMode === "hybrid") {
      if (effectiveFlags.localProviderEnabled) {
        return hasApiKey ? "prefer-local-fallback-cloud" : "local-only";
      }

      return hasApiKey ? "cloud-only" : "local-only";
    }

    if (hasApiKey) {
      return "cloud-only";
    }

    return effectiveFlags.localProviderEnabled ? "local-only" : "cloud-only";
  }

  /**
   * Encaminha streaming para o provider adequado e aplica fallback quando permitido.
   */
  async function streamAskResponse(input) {
    const hasApiKey = Boolean(input.apiKey);
    const strategy = resolveStrategy(input.effectiveFlags, hasApiKey);

    logger.info("ProviderRouter resolved strategy", {
      requestId: input.requestId,
      strategy,
      providerMode: input.effectiveFlags.providerMode,
      forceLocalOnly: input.effectiveFlags.forceLocalOnly,
      localProviderEnabled: input.effectiveFlags.localProviderEnabled,
      hasApiKey
    });

    if (strategy === "local-only") {
      if (!localProvider.isAvailable()) {
        throw new Error("LOCAL_ONLY_PRIVACY_MODE_ACTIVE: provider local indisponivel e fallback cloud bloqueado por privacidade.");
      }
      return localProvider.streamAskResponse(input);
    }

    if (strategy === "cloud-only") {
      if (!hasApiKey) {
        throw new Error("Gemini API key nao configurada nas Settings.");
      }

      return geminiProvider.streamAskResponse(input);
    }

    try {
      return await localProvider.streamAskResponse(input);
    } catch (error) {
      logger.warn("Local provider failed, falling back to cloud", {
        requestId: input.requestId,
        message: error instanceof Error ? error.message : "Unknown error"
      });

      if (!hasApiKey) {
        throw error;
      }

      return geminiProvider.streamAskResponse(input);
    }
  }

  return {
    streamAskResponse
  };
}

module.exports = {
  createProviderRouter
};
