// Generated by GitHub Copilot
const test = require("node:test");
const assert = require("node:assert/strict");
const { createProviderRouter } = require("./provider-router.cjs");

function createDependencies(overrides) {
  const calls = {
    local: 0,
    cloud: 0
  };

  const localProvider = {
    isAvailable: () => true,
    streamAskResponse: async () => {
      calls.local += 1;
      return "local";
    }
  };

  const geminiProvider = {
    streamAskResponse: async () => {
      calls.cloud += 1;
      return "cloud";
    }
  };

  return {
    deps: {
      logger: { info: () => {}, warn: () => {} },
      localProvider,
      geminiProvider,
      ...(overrides || {})
    },
    calls
  };
}

test("ProviderRouter usa local-only quando forceLocalOnly=true", async () => {
  const { deps, calls } = createDependencies();
  const router = createProviderRouter(deps);

  await router.streamAskResponse({
    requestId: "r-1",
    apiKey: "",
    effectiveFlags: {
      providerMode: "cloud",
      localProviderEnabled: false,
      forceLocalOnly: true
    }
  });

  assert.equal(calls.local, 1);
  assert.equal(calls.cloud, 0);
});

test("ProviderRouter usa cloud-only quando provider=cloud e apiKey presente", async () => {
  const { deps, calls } = createDependencies();
  const router = createProviderRouter(deps);

  await router.streamAskResponse({
    requestId: "r-2",
    apiKey: "secret-key",
    effectiveFlags: {
      providerMode: "cloud",
      localProviderEnabled: false,
      forceLocalOnly: false
    }
  });

  assert.equal(calls.local, 0);
  assert.equal(calls.cloud, 1);
});

test("ProviderRouter em hybrid faz fallback para cloud quando local falha e apiKey existe", async () => {
  const { deps, calls } = createDependencies({
    localProvider: {
      isAvailable: () => true,
      streamAskResponse: async () => {
        calls.local += 1;
        throw new Error("local failure");
      }
    }
  });
  const router = createProviderRouter(deps);

  await router.streamAskResponse({
    requestId: "r-3",
    apiKey: "secret-key",
    effectiveFlags: {
      providerMode: "hybrid",
      localProviderEnabled: true,
      forceLocalOnly: false
    }
  });

  assert.equal(calls.local, 1);
  assert.equal(calls.cloud, 1);
});

test("ProviderRouter bloqueia fallback cloud quando local-only e provider local indisponivel", async () => {
  const { deps } = createDependencies({
    localProvider: {
      isAvailable: () => false,
      streamAskResponse: async () => "unused"
    }
  });
  const router = createProviderRouter(deps);

  await assert.rejects(
    () =>
      router.streamAskResponse({
        requestId: "r-4",
        apiKey: "secret-key",
        effectiveFlags: {
          providerMode: "local",
          localProviderEnabled: true,
          forceLocalOnly: true
        }
      }),
    /LOCAL_ONLY_PRIVACY_MODE_ACTIVE/
  );
});
