// Generated by GitHub Copilot
const fs = require("node:fs");
const path = require("node:path");
const { randomUUID } = require("node:crypto");
const { app, desktopCapturer, screen } = require("electron");

const MAX_QUEUE_LENGTH = 10;

function createScreenshotService(options) {
  const logger = options.logger;
  const onQueueUpdated = options.onQueueUpdated;
  const queue = [];
  const capturesDir = path.join(app.getPath("userData"), "captures");

  function ensureCapturesDir() {
    if (!fs.existsSync(capturesDir)) {
      fs.mkdirSync(capturesDir, { recursive: true });
    }
  }

  function emitQueueUpdated() {
    onQueueUpdated([...queue]);
  }

  async function captureScreenshot(payload = {}) {
    ensureCapturesDir();

    const primaryDisplay = screen.getPrimaryDisplay();
    const thumbnailSize = {
      width: Math.max(1, primaryDisplay.size.width),
      height: Math.max(1, primaryDisplay.size.height)
    };

    const sources = await desktopCapturer.getSources({
      types: ["screen"],
      thumbnailSize
    });

    const preferredSource =
      sources.find((source) => source.display_id === String(primaryDisplay.id)) || sources[0];

    if (!preferredSource) {
      throw new Error("No screen source available for capture.");
    }

    const captureId = randomUUID();
    const createdAtIso = new Date().toISOString();
    const imagePath = path.join(capturesDir, `${captureId}.png`);
    const pngBuffer = preferredSource.thumbnail.toPNG();

    fs.writeFileSync(imagePath, pngBuffer);

    const item = {
      captureId,
      imagePath,
      createdAtIso,
      source: payload.source || "full",
      trigger: payload.trigger || "manual",
      previewDataUrl: preferredSource.thumbnail.toDataURL()
    };

    queue.unshift(item);
    while (queue.length > MAX_QUEUE_LENGTH) {
      const removed = queue.pop();
      if (removed && fs.existsSync(removed.imagePath)) {
        fs.rmSync(removed.imagePath, { force: true });
      }
    }

    logger.info("Screenshot captured", {
      captureId: item.captureId,
      trigger: item.trigger,
      source: item.source,
      queueSize: queue.length
    });

    emitQueueUpdated();
    return item;
  }

  function getQueue() {
    return [...queue];
  }

  function clearQueue() {
    while (queue.length > 0) {
      const item = queue.pop();
      if (item && fs.existsSync(item.imagePath)) {
        fs.rmSync(item.imagePath, { force: true });
      }
    }

    logger.warn("Screenshot queue cleared");
    emitQueueUpdated();
    return [];
  }

  return {
    captureScreenshot,
    getQueue,
    clearQueue
  };
}

module.exports = {
  createScreenshotService
};
