// Generated by GitHub Copilot
const fs = require("node:fs");
const path = require("node:path");
const { app, safeStorage } = require("electron");

const DEFAULT_SETTINGS = {
  language: "pt-BR",
  selectedAudioInputDeviceId: "",
  shortcuts: {
    captureScreen: "Ctrl+E",
    pushToTalk: "Ctrl+D",
    toggleStealth: "Ctrl+B"
  },
  geminiApiKeyEncrypted: "",
  autoUpdate: {
    enabled: false,
    feedUrl: "",
    channel: "stable",
    allowPrerelease: false,
    pendingVersion: "",
    previousVersion: "",
    previousChannel: "stable",
    pendingHealthConfirmation: false
  },
  featureFlags: {
    providerMode: "cloud",
    localProviderEnabled: false,
    forceLocalOnly: false,
    stealthHardening: "safe"
  }
};

/**
 * Cria um repositório de configurações em arquivo JSON no userData do Electron.
 */
function createSettingsStore() {
  const settingsDir = path.join(app.getPath("userData"), "config");
  const settingsPath = path.join(settingsDir, "settings.json");

  /**
   * Garante a existência do diretório e arquivo de configurações.
   */
  function ensureStore() {
    if (!fs.existsSync(settingsDir)) {
      fs.mkdirSync(settingsDir, { recursive: true });
    }

    if (!fs.existsSync(settingsPath)) {
      fs.writeFileSync(settingsPath, JSON.stringify(DEFAULT_SETTINGS, null, 2), "utf-8");
    }
  }

  /**
   * Lê as configurações persistidas, aplicando fallback seguro para defaults.
   */
  function readRaw() {
    ensureStore();

    try {
      const fileContent = fs.readFileSync(settingsPath, "utf-8");
      const parsed = JSON.parse(fileContent);
      return {
        ...DEFAULT_SETTINGS,
        ...parsed,
        shortcuts: {
          ...DEFAULT_SETTINGS.shortcuts,
          ...(parsed.shortcuts || {})
        },
        autoUpdate: {
          ...DEFAULT_SETTINGS.autoUpdate,
          ...(parsed.autoUpdate || {})
        },
        featureFlags: {
          ...DEFAULT_SETTINGS.featureFlags,
          ...(parsed.featureFlags || {})
        }
      };
    } catch {
      return { ...DEFAULT_SETTINGS };
    }
  }

  /**
   * Persiste configurações em disco de forma síncrona para simplificar consistência do MVP.
   */
  function writeRaw(next) {
    ensureStore();
    fs.writeFileSync(settingsPath, JSON.stringify(next, null, 2), "utf-8");
  }

  /**
   * Retorna visão segura das configurações para o renderer sem expor segredo em claro.
   */
  function getPublicSettings() {
    const raw = readRaw();
    return {
      language: raw.language,
      selectedAudioInputDeviceId: raw.selectedAudioInputDeviceId || undefined,
      shortcuts: raw.shortcuts,
      hasGeminiApiKey: Boolean(raw.geminiApiKeyEncrypted)
    };
  }

  /**
   * Retorna a API key Gemini descriptografada somente no main process.
   * Seguranca: o segredo nunca e exposto ao renderer.
   */
  function getGeminiApiKey() {
    const raw = readRaw();
    if (!raw.geminiApiKeyEncrypted) {
      return "";
    }

    const encryptedBuffer = Buffer.from(raw.geminiApiKeyEncrypted, "base64");

    try {
      if (safeStorage.isEncryptionAvailable()) {
        return safeStorage.decryptString(encryptedBuffer);
      }
    } catch {
      return "";
    }

    return encryptedBuffer.toString("utf-8");
  }

  /**
   * Atualiza configurações com merge parcial e criptografa API key quando suportado.
   */
  function savePartial(partial) {
    const current = readRaw();
    const next = {
      ...current,
      ...partial,
      shortcuts: {
        ...current.shortcuts,
        ...(partial.shortcuts || {})
      },
      autoUpdate: {
        ...DEFAULT_SETTINGS.autoUpdate,
        ...(current.autoUpdate || {}),
        ...(partial.autoUpdate || {})
      }
    };

    if (Object.prototype.hasOwnProperty.call(partial, "geminiApiKey")) {
      if (!partial.geminiApiKey) {
        next.geminiApiKeyEncrypted = "";
      } else if (safeStorage.isEncryptionAvailable()) {
        next.geminiApiKeyEncrypted = safeStorage.encryptString(partial.geminiApiKey).toString("base64");
      } else {
        next.geminiApiKeyEncrypted = Buffer.from(partial.geminiApiKey, "utf-8").toString("base64");
      }
    }

    if (Object.prototype.hasOwnProperty.call(partial, "selectedAudioInputDeviceId")) {
      next.selectedAudioInputDeviceId = partial.selectedAudioInputDeviceId || "";
    }

    delete next.geminiApiKey;
    writeRaw(next);
    return getPublicSettings();
  }

  /**
   * Limpa configurações customizadas e restaura defaults.
   */
  function reset() {
    writeRaw({ ...DEFAULT_SETTINGS });
    return getPublicSettings();
  }

  /**
   * Retorna feature flags persistidas em disco.
   */
  function getFeatureFlags() {
    const raw = readRaw();
    return {
      ...DEFAULT_SETTINGS.featureFlags,
      ...(raw.featureFlags || {})
    };
  }

  /**
   * Atualiza feature flags com merge parcial.
   */
  function saveFeatureFlags(partial) {
    const current = readRaw();
    const next = {
      ...current,
      featureFlags: {
        ...DEFAULT_SETTINGS.featureFlags,
        ...(current.featureFlags || {}),
        ...(partial || {})
      }
    };

    writeRaw(next);
    return getFeatureFlags();
  }

  /**
   * Restaura feature flags para o default do produto.
   */
  function resetFeatureFlags() {
    const current = readRaw();
    const next = {
      ...current,
      featureFlags: {
        ...DEFAULT_SETTINGS.featureFlags
      }
    };

    writeRaw(next);
    return getFeatureFlags();
  }

  /**
   * Retorna configuracao persistida de auto-update sem incluir estado derivado do runtime.
   */
  function getAutoUpdateSettings() {
    const raw = readRaw();
    return {
      ...DEFAULT_SETTINGS.autoUpdate,
      ...(raw.autoUpdate || {})
    };
  }

  /**
   * Atualiza configuracao persistida de auto-update e metadados de rollback.
   */
  function saveAutoUpdateSettings(partial) {
    const current = readRaw();
    const next = {
      ...current,
      autoUpdate: {
        ...DEFAULT_SETTINGS.autoUpdate,
        ...(current.autoUpdate || {}),
        ...(partial || {})
      }
    };

    writeRaw(next);
    return getAutoUpdateSettings();
  }

  return {
    getPublicSettings,
    getGeminiApiKey,
    savePartial,
    reset,
    getFeatureFlags,
    saveFeatureFlags,
    resetFeatureFlags,
    getAutoUpdateSettings,
    saveAutoUpdateSettings
  };
}

module.exports = {
  createSettingsStore
};
