// Generated by GitHub Copilot
const { globalShortcut } = require("electron");
const { getEnvironmentConfig } = require("./env-config.cjs");
const { resolveFeatureFlags } = require("./feature-flags.cjs");

function createShortcutService(options) {
  const logger = options.logger;
  const settingsStore = options.settingsStore;
  const screenshotService = options.screenshotService;
  const stealthWindowService = options.stealthWindowService;
  const emitRendererEvent = options.emitRendererEvent;

  let registeredCaptureShortcut = null;
  let registeredStealthShortcut = null;

  async function handleCaptureShortcut() {
    try {
      await screenshotService.captureScreenshot({
        source: "full",
        trigger: "shortcut"
      });
    } catch (error) {
      logger.error("Global capture shortcut failed", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
    }
  }

  function emitStealthState(source, applied) {
    if (typeof emitRendererEvent === "function") {
      emitRendererEvent("stealth:state-changed", {
        enabled: applied.enabled,
        hardening: applied.hardening,
        source,
        appliedAtIso: applied.appliedAtIso
      });
    }
  }

  function handleStealthShortcut() {
    try {
      const env = getEnvironmentConfig();
      const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
      const applied = stealthWindowService.toggleStealthMode({
        hardening: effectiveFlags.stealthHardening
      });
      emitStealthState("shortcut", applied);
    } catch (error) {
      logger.error("Global stealth shortcut failed", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
    }
  }

  function registerCaptureShortcut() {
    const settings = settingsStore.getPublicSettings();
    const accelerator = settings.shortcuts.captureScreen;

    if (registeredCaptureShortcut) {
      globalShortcut.unregister(registeredCaptureShortcut);
      registeredCaptureShortcut = null;
    }

    const success = globalShortcut.register(accelerator, () => {
      void handleCaptureShortcut();
    });

    if (!success) {
      throw new Error(`Unable to register global shortcut: ${accelerator}`);
    }

    registeredCaptureShortcut = accelerator;
    logger.info("Registered global capture shortcut", { accelerator });
    return accelerator;
  }

  function registerStealthShortcut() {
    const settings = settingsStore.getPublicSettings();
    const accelerator = settings.shortcuts.toggleStealth;

    if (registeredStealthShortcut) {
      globalShortcut.unregister(registeredStealthShortcut);
      registeredStealthShortcut = null;
    }

    const success = globalShortcut.register(accelerator, () => {
      handleStealthShortcut();
    });

    if (!success) {
      throw new Error(`Unable to register global shortcut: ${accelerator}`);
    }

    registeredStealthShortcut = accelerator;
    logger.info("Registered global stealth shortcut", { accelerator });
    return accelerator;
  }

  function refreshShortcuts() {
    try {
      return {
        captureShortcut: registerCaptureShortcut(),
        stealthShortcut: registerStealthShortcut()
      };
    } catch (error) {
      logger.error("Failed to refresh shortcuts", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
      throw error;
    }
  }

  function refreshCaptureShortcut() {
    return refreshShortcuts();
  }

  function dispose() {
    globalShortcut.unregisterAll();
    registeredCaptureShortcut = null;
    registeredStealthShortcut = null;
    logger.info("Unregistered all global shortcuts");
  }

  return {
    refreshShortcuts,
    refreshCaptureShortcut,
    dispose
  };
}

module.exports = {
  createShortcutService
};
