// Generated by GitHub Copilot
const { globalShortcut } = require("electron");
const { getEnvironmentConfig } = require("./env-config.cjs");
const { resolveFeatureFlags } = require("./feature-flags.cjs");

function createShortcutService(options) {
  const logger = options.logger;
  const settingsStore = options.settingsStore;
  const screenshotService = options.screenshotService;
  const stealthWindowService = options.stealthWindowService;
  const emitRendererEvent = options.emitRendererEvent;

  let registeredCaptureShortcut = null;
  let registeredFullStealthShortcut = null;
  let registeredPushToTalkShortcut = null;

  function emitStealthState(source, state) {
    if (typeof emitRendererEvent !== "function") {
      return;
    }
    emitRendererEvent("stealth:state-changed", {
      enabled: state.enabled,
      fullStealth: Boolean(state.fullStealth),
      hardening: state.hardening,
      opacity: state.opacity,
      source,
      appliedAtIso: state.appliedAtIso || new Date().toISOString()
    });
  }

  /**
   * Antes de qualquer outro atalho: sai do full stealth e volta ao stealth visível.
   */
  function restoreStealthVisibility(source) {
    if (settingsStore.getNonStealthModeEnabled()) {
      return stealthWindowService.getState();
    }
    const result = stealthWindowService.exitFullStealthIfActive();
    if (result.changed) {
      emitStealthState(source, result);
    }
    return result;
  }

  function wrapWithStealthRestore(handler, source) {
    return () => {
      restoreStealthVisibility(source);
      handler();
    };
  }

  async function handleCaptureShortcut() {
    try {
      const item = await screenshotService.captureScreenshot({
        source: "full",
        trigger: "shortcut"
      });
      if (typeof emitRendererEvent === "function") {
        const items = Array.isArray(item.items) && item.items.length > 0 ? item.items : [item];
        emitRendererEvent("screenshot:quick-analyze", {
          captureId: item.captureId,
          previewDataUrl: item.previewDataUrl,
          captureIds: items.map((entry) => entry.captureId),
          previewDataUrls: items.map((entry) => entry.previewDataUrl)
        });
      }
    } catch (error) {
      logger.error("Global capture shortcut failed", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
    }
  }

  function handleFullStealthShortcut() {
    if (settingsStore.getNonStealthModeEnabled()) {
      return;
    }
    try {
      const env = getEnvironmentConfig();
      const effectiveFlags = resolveFeatureFlags(settingsStore.getFeatureFlags(), env).effective;
      const state = stealthWindowService.getState();
      const applied = stealthWindowService.toggleFullStealthMode({
        hardening: effectiveFlags.stealthHardening,
        opacity: state.opacity
      });
      emitStealthState("shortcut", applied);
    } catch (error) {
      logger.error("Global full stealth shortcut failed", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
    }
  }

  function handlePushToTalkShortcut() {
    if (typeof emitRendererEvent === "function") {
      emitRendererEvent("shortcut:push-to-talk", {
        triggeredAtIso: new Date().toISOString()
      });
    }
  }

  function registerShortcut(accelerator, handler, label) {
    const success = globalShortcut.register(accelerator, handler);
    if (!success) {
      throw new Error(`Unable to register global shortcut (${label}): ${accelerator}`);
    }
    logger.info("Registered global shortcut", { label, accelerator });
    return accelerator;
  }

  function unregisterIfRegistered(current) {
    if (current) {
      globalShortcut.unregister(current);
    }
    return null;
  }

  function registerCaptureShortcut() {
    const settings = settingsStore.getPublicSettings();
    const accelerator = settings.shortcuts.captureScreen;
    registeredCaptureShortcut = unregisterIfRegistered(registeredCaptureShortcut);
    registeredCaptureShortcut = registerShortcut(
      accelerator,
      () => {
        void handleCaptureShortcut();
      },
      "capture"
    );
    return registeredCaptureShortcut;
  }

  function registerFullStealthShortcut() {
    const settings = settingsStore.getPublicSettings();
    const accelerator = settings.shortcuts.toggleFullStealth || "Ctrl+Shift+H";
    registeredFullStealthShortcut = unregisterIfRegistered(registeredFullStealthShortcut);
    registeredFullStealthShortcut = registerShortcut(
      accelerator,
      handleFullStealthShortcut,
      "toggle-full-stealth"
    );
    return registeredFullStealthShortcut;
  }

  function registerPushToTalkShortcut() {
    const settings = settingsStore.getPublicSettings();
    const accelerator = settings.shortcuts.pushToTalk || "Ctrl+D";
    registeredPushToTalkShortcut = unregisterIfRegistered(registeredPushToTalkShortcut);
    registeredPushToTalkShortcut = registerShortcut(
      accelerator,
      wrapWithStealthRestore(handlePushToTalkShortcut, "shortcut"),
      "push-to-talk"
    );
    return registeredPushToTalkShortcut;
  }

  function refreshShortcuts() {
    try {
      return {
        captureShortcut: registerCaptureShortcut(),
        fullStealthShortcut: registerFullStealthShortcut(),
        pushToTalkShortcut: registerPushToTalkShortcut()
      };
    } catch (error) {
      logger.error("Failed to refresh shortcuts", {
        message: error instanceof Error ? error.message : "Unknown error"
      });
      throw error;
    }
  }

  function refreshCaptureShortcut() {
    return refreshShortcuts();
  }

  function dispose() {
    globalShortcut.unregisterAll();
    registeredCaptureShortcut = null;
    registeredFullStealthShortcut = null;
    registeredPushToTalkShortcut = null;
    logger.info("Unregistered all global shortcuts");
  }

  return {
    refreshShortcuts,
    refreshCaptureShortcut,
    restoreStealthVisibility,
    dispose
  };
}

module.exports = {
  createShortcutService
};
