// Generated by GitHub Copilot

/**
 * Determina se o perfil stealth deve estar ativo (padrão do produto).
 */
function shouldEnableStealthMode(settingsStore, effectiveFlags) {
  if (settingsStore.getNonStealthModeEnabled()) {
    return false;
  }
  const hardening = effectiveFlags?.stealthHardening ?? "safe";
  return hardening !== "off";
}

/**
 * Aplica stealth ou modo normal conforme configurações e feature flags.
 */
function applyStealthFromSettings({ settingsStore, stealthWindowService, effectiveFlags, opacity }) {
  const enabled = shouldEnableStealthMode(settingsStore, effectiveFlags);
  return stealthWindowService.setStealthMode({
    enabled,
    hardening: effectiveFlags.stealthHardening,
    opacity
  });
}

module.exports = {
  shouldEnableStealthMode,
  applyStealthFromSettings
};
