// Generated by GitHub Copilot

/**
 * Cria adapter de STT com roteamento cloud/local sem acoplar o renderer ao provider.
 */
function createSttAdapter(dependencies) {
  const logger = dependencies?.logger || {
    debug: () => {},
    warn: () => {},
    error: () => {}
  };
  const whisperCliManager = dependencies?.whisperCliManager;

  /**
   * Simula transcrição cloud com retorno incremental para manter o contrato do MVP.
   */
  async function transcribeWithCloud(params) {
    const byteLength = Buffer.byteLength(params.chunkBase64 || "", "base64");
    const language = params.language || "auto";
    const hasApiKey = Boolean(params.apiKey);

    if (!hasApiKey) {
      throw new Error("Cloud STT requer API key configurada.");
    }

    return {
      text: `[cloud:${language}] chunk ${Math.max(1, Math.round(byteLength / 1024))}KB recebido para sessao ${params.sessionId}.`,
      isFinal: false
    };
  }

  /**
   * Simula transcrição local para preparar migração futura para whisper local.
   */
  async function transcribeWithLocal(params) {
    const byteLength = Buffer.byteLength(params.chunkBase64 || "", "base64");
    const language = params.language || "auto";

    if (!whisperCliManager) {
      return {
        text: `[local:${language}] whisper manager nao configurado - chunk ${Math.max(1, Math.round(byteLength / 1024))}KB.`,
        isFinal: false
      };
    }

    try {
      const result = await whisperCliManager.transcribeChunk({
        chunkBase64: params.chunkBase64,
        language
      });

      if (result.text) {
        return {
          text: result.text,
          isFinal: result.isFinal
        };
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Falha desconhecida no whisper-cli";
      logger.warn("Local STT runtime fallback to stub", {
        message,
        sessionId: params.sessionId
      });
      return {
        text: `[local:${language}] fallback stub - ${message}`,
        isFinal: false
      };
    }

    return {
      text: `[local:${language}] pipeline local ativo (stub) - chunk ${Math.max(1, Math.round(byteLength / 1024))}KB.`,
      isFinal: false
    };
  }

  /**
   * Decide provider de transcrição com base em feature flags efetivas.
   */
  async function transcribe(params) {
    const effective = params.effectiveFlags || {};
    const forceLocalOnly = Boolean(effective.forceLocalOnly);
    const providerMode = effective.providerMode || "cloud";
    const localProviderEnabled = Boolean(effective.localProviderEnabled);

    const shouldUseLocal =
      forceLocalOnly ||
      providerMode === "local" ||
      (providerMode === "hybrid" && localProviderEnabled);

    if (shouldUseLocal) {
      logger.debug("STT adapter: using local provider", {
        sessionId: params.sessionId,
        providerMode,
        forceLocalOnly
      });
      return transcribeWithLocal(params);
    }

    logger.debug("STT adapter: using cloud provider", {
      sessionId: params.sessionId,
      providerMode,
      forceLocalOnly
    });

    return transcribeWithCloud(params);
  }

  return {
    transcribe
  };
}

module.exports = {
  createSttAdapter
};
