// Generated by GitHub Copilot
import { useEffect, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import type {
  ChatStreamEvent,
  ScreenshotQueueItem,
  StealthStateChangedEvent,
} from "@clone-perssua/shared-types";
import { MeetingModePanel } from "./components/MeetingModePanel";
import { SettingsPage, type SettingsTabId } from "./components/SettingsPage";
import { TranslationModePanel } from "./components/TranslationModePanel";

// ─── Constantes ─────────────────────────────────────────────────────────────

const DEFAULT_SCREENSHOT_PROMPT = "analise a tela";

// ─── Types ───────────────────────────────────────────────────────────────────

interface ChatMessage {
  id: string;
  requestId: string;
  role: "user" | "assistant";
  content: string;
  createdAtIso: string;
  status: "pending" | "streaming" | "completed" | "error";
  errorCode?: string;
  actionableMessage?: string;
  retryable?: boolean;
  linkedScreenshotIds: string[];
  linkedScreenshotPreviewUrls: string[];
  linkedAudioDuration?: number;
}

type AppMode = "chat" | "meeting" | "translation";

// ─── Design tokens (dark theme) ─────────────────────────────────────────────

const C = {
  bg: "#0f0f0f",
  surface: "#1a1a1a",
  surface2: "#242424",
  border: "#2e2e2e",
  accent: "#6366f1",
  text: "#e5e5e5",
  textMuted: "#888",
  textDim: "#555",
  error: "#ef4444",
  success: "#22c55e",
} as const;

// ─── Style helpers ───────────────────────────────────────────────────────────

function iconBtn(active?: boolean, danger?: boolean): React.CSSProperties {
  return {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    borderRadius: 6,
    color: danger ? C.error : active ? C.accent : C.textMuted,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  };
}

// ─── App component ───────────────────────────────────────────────────────────

export function App(): JSX.Element {
  const sessionId = useRef(globalThis.crypto.randomUUID()).current;

  // ── Chat state ──────────────────────────────────────────────────────────
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [askText, setAskText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const [autoScroll, setAutoScroll] = useState(true);

  // ── Screenshot state ────────────────────────────────────────────────────
  const [screenshotQueue, setScreenshotQueue] = useState<ScreenshotQueueItem[]>([]);
  const [pendingScreenshotIds, setPendingScreenshotIds] = useState<string[]>([]);
  const [quickAnalysis, setQuickAnalysis] = useState(true);

  // ── Stealth + LLM + opacity ─────────────────────────────────────────────
  const [stealthEnabled, setStealthEnabled] = useState(true);
  const [hasLlm, setHasLlm] = useState(false);
  const [opacity, setOpacity] = useState(0.8);
  const [opacityOpen, setOpacityOpen] = useState(false);

  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settingsTab, setSettingsTab] = useState<SettingsTabId>("general");
  const [appMode, setAppMode] = useState<AppMode>("chat");
  const [chatExpanded, setChatExpanded] = useState(false);

  // ── Settings — Resources ─────────────────────────────────────────────────
  const [selectToPrompt, setSelectToPrompt] = useState(false);

  // ── Settings — Shortcuts ─────────────────────────────────────────────────
  const [captureShortcut, setCaptureShortcut] = useState("Ctrl+E");
  const [pushToTalkShortcut, setPushToTalkShortcut] = useState("Ctrl+D");

  // ── Audio recording ────────────────────────────────────────────────────────────────────────
  const [audioReady, setAudioReady] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [recordingSeconds, setRecordingSeconds] = useState(0);
  const [pendingAudioId, setPendingAudioId] = useState<string | null>(null);
  const [pendingAudioDuration, setPendingAudioDuration] = useState(0);
  const activeStreamRef = useRef<MediaStream | null>(null);
  const activeRecorderRef = useRef<MediaRecorder | null>(null);
  const recordingTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const recordingStartRef = useRef(0);

  // ── Init ────────────────────────────────────────────────────────────────

  useEffect(() => {
    void loadSettings();
    void loadScreenshotQueue();

    const unsubQ = window.desktopApi.onScreenshotQueueUpdated((p) => {
      setScreenshotQueue(p.items);
    });
    const unsubChat = window.desktopApi.onChatStreamEvent(handleChatStreamEvent);
    const unsubStealth = window.desktopApi.onStealthStateChanged(handleStealthStateChanged);
    const unsubQuick = window.desktopApi.onQuickAnalyze((p) => {
      const captureIds =
        Array.isArray(p.captureIds) && p.captureIds.length > 0 ? p.captureIds : [p.captureId];
      const previewDataUrls =
        Array.isArray(p.previewDataUrls) && p.previewDataUrls.length > 0
          ? p.previewDataUrls
          : [p.previewDataUrl];
      void submitAsk(DEFAULT_SCREENSHOT_PROMPT, captureIds, previewDataUrls);
    });

    // Probe de dispositivos de audio sem solicitar permissao
    void globalThis.navigator.mediaDevices.enumerateDevices()
      .then((devices) => {
        if (devices.some((d) => d.kind === "audioinput")) {
          setAudioReady(true);
        }
      })
      .catch(() => {});

    return () => {
      unsubQ();
      unsubChat();
      unsubStealth();
      unsubQuick();
      stopRecording();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-scroll to latest message
  useEffect(() => {
    if (autoScroll && chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages, autoScroll]);

  // Select-to-prompt: Ctrl+C with selected text
  useEffect(() => {
    if (!selectToPrompt) return;
    const onKey = (e: globalThis.KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "c") {
        const sel = globalThis.window.getSelection()?.toString().trim();
        if (sel && sel.length > 2) {
          setAskText(`Analise o seguinte trecho e forneça insights: "${sel}"`);
        }
      }
    };
    globalThis.addEventListener("keydown", onKey);
    return () => globalThis.removeEventListener("keydown", onKey);
  }, [selectToPrompt]);

  // Close opacity popover when clicking outside
  useEffect(() => {
    if (!opacityOpen) return;
    const onDown = () => setOpacityOpen(false);
    // Small delay so the button click that opened it doesn't immediately close it
    const timer = globalThis.setTimeout(() => {
      globalThis.addEventListener("mousedown", onDown, { once: true });
    }, 50);
    return () => {
      globalThis.clearTimeout(timer);
      globalThis.removeEventListener("mousedown", onDown);
    };
  }, [opacityOpen]);

  useEffect(() => {
    if (settingsOpen) {
      void window.desktopApi.setWindowLayout("settings");
      return;
    }
    void window.desktopApi.setWindowLayout(chatExpanded ? "expanded" : "chat");
  }, [settingsOpen, chatExpanded]);

  // ── IPC loaders ─────────────────────────────────────────────────────────

  async function loadSettings(): Promise<void> {
    try {
      const r = await window.desktopApi.getSettings();
      setCaptureShortcut(r.settings.shortcuts.captureScreen);
      setPushToTalkShortcut(r.settings.shortcuts.pushToTalk);
      setHasLlm(r.settings.hasGeminiApiKey);
    } catch { /* silent */ }
  }

  async function loadScreenshotQueue(): Promise<void> {
    try {
      const r = await window.desktopApi.getScreenshotQueue();
      setScreenshotQueue(r.items);
    } catch { /* silent */ }
  }

  // ── IPC event handlers ───────────────────────────────────────────────────

  function handleStealthStateChanged(p: StealthStateChangedEvent): void {
    setStealthEnabled(p.enabled);
    // Sync slider with the actual opacity the main process used
    if (p.enabled && typeof p.opacity === "number") {
      setOpacity(p.opacity);
    } else if (!p.enabled) {
      setOpacityOpen(false);
    }
  }

  function handleChatStreamEvent(payload: ChatStreamEvent): void {
    setChatMessages((current) => {
      const idx = current.findIndex(
        (m) => m.requestId === payload.requestId && m.role === "assistant"
      );
      if (idx === -1) {
        return [
          ...current,
          {
            id: `${payload.requestId}-assistant`,
            requestId: payload.requestId,
            role: "assistant",
            content: payload.fullText || payload.deltaText || "",
            createdAtIso: payload.createdAtIso,
            status: payload.status === "completed" ? "completed" : payload.status === "error" ? "error" : "streaming",
            errorCode: payload.errorCode,
            actionableMessage: payload.actionableMessage,
            retryable: payload.retryable,
            linkedScreenshotIds: [],
            linkedScreenshotPreviewUrls: [],
          },
        ];
      }
      return current.map((m, i) =>
        i !== idx
          ? m
          : {
              ...m,
              content: payload.fullText || m.content,
              status:
                payload.status === "completed"
                  ? "completed"
                  : payload.status === "error"
                  ? "error"
                  : "streaming",
              errorCode: payload.errorCode,
              actionableMessage: payload.actionableMessage,
              retryable: payload.retryable,
            }
      );
    });
    if (payload.status === "completed" || payload.status === "error") {
      setIsSubmitting(false);
    }
  }

  // ── Screenshot ────────────────────────────────────────────────────────────

  async function handleCapture(): Promise<void> {
    try {
      const r = await window.desktopApi.captureScreenshot({ source: "full" });
      setScreenshotQueue((q) =>
        [r, ...q.filter((x) => x.captureId !== r.captureId)].slice(0, 10)
      );
      if (quickAnalysis) {
        await submitAsk(DEFAULT_SCREENSHOT_PROMPT, [r.captureId], [r.previewDataUrl]);
      } else {
        setPendingScreenshotIds((ids) => [...ids, r.captureId]);
        setAskText(DEFAULT_SCREENSHOT_PROMPT);
      }
    } catch { /* silent */ }
  }

  function removeScreenshot(captureId: string): void {
    setPendingScreenshotIds((ids) => ids.filter((id) => id !== captureId));
  }

  // ── Audio recording ────────────────────────────────────────────────────────────────────────

  function getSupportedAudioMimeType(): string {
    const candidates = [
      "audio/webm;codecs=opus",
      "audio/webm",
      "audio/ogg;codecs=opus",
      "audio/ogg",
    ];
    return candidates.find((t) => MediaRecorder.isTypeSupported(t)) ?? "";
  }

  function formatAudioDuration(seconds: number): string {
    const m = Math.floor(seconds / 60);
    const s = Math.round(seconds % 60);
    return `${m}:${String(s).padStart(2, "0")}`;
  }

  async function toggleRecording(): Promise<void> {
    if (isRecording) {
      stopRecording();
      return;
    }

    if (!audioReady) {
      setSettingsTab("microphone");
      setSettingsOpen(true);
      return;
    }

    try {
      const settingsRes = await window.desktopApi.getSettings();
      const micId = settingsRes.settings.selectedAudioInputDeviceId;
      const audioConstraint: MediaTrackConstraints = {
        channelCount: 1,
        sampleRate: 16000,
        echoCancellation: true,
        noiseSuppression: true,
        ...(micId ? { deviceId: { exact: micId } } : {}),
      };
      const stream = await globalThis.navigator.mediaDevices.getUserMedia({ audio: audioConstraint });
      activeStreamRef.current = stream;

      const mimeType = getSupportedAudioMimeType();
      const recorderOptions: MediaRecorderOptions = { audioBitsPerSecond: 16000 };
      if (mimeType) recorderOptions.mimeType = mimeType;

      const recorder = new MediaRecorder(stream, recorderOptions);
      activeRecorderRef.current = recorder;
      const chunks: BlobPart[] = [];
      const prevPendingId = pendingAudioId;

      recorder.ondataavailable = (e) => {
        if (e.data?.size > 0) chunks.push(e.data);
      };

      recorder.onstop = async () => {
        stream.getTracks().forEach((t) => t.stop());
        activeStreamRef.current = null;
        if (recordingTimerRef.current) {
          clearInterval(recordingTimerRef.current);
          recordingTimerRef.current = null;
        }
        const duration = (Date.now() - recordingStartRef.current) / 1000;
        setIsRecording(false);
        setRecordingSeconds(0);
        activeRecorderRef.current = null;

        if (!chunks.length) return;

        const effectiveMime = mimeType || "audio/webm";
        const blob = new Blob(chunks, { type: effectiveMime });

        const b64 = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            const result = reader.result as string;
            resolve(result.split(",")[1] ?? "");
          };
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        });

        try {
          const added = await window.desktopApi.addAudio({
            audioBase64: b64,
            mimeType: effectiveMime,
            durationSeconds: duration,
          });
          if (prevPendingId) {
            void window.desktopApi.removeAudio({ audioId: prevPendingId });
          }
          setPendingAudioId(added.audioId);
          setPendingAudioDuration(duration);
        } catch { /* silent */ }
      };

      recordingStartRef.current = Date.now();
      recorder.start(1000);
      setIsRecording(true);
      setRecordingSeconds(0);

      recordingTimerRef.current = setInterval(() => {
        setRecordingSeconds((s) => s + 1);
      }, 1000);
    } catch {
      setIsRecording(false);
      if (recordingTimerRef.current) {
        clearInterval(recordingTimerRef.current);
        recordingTimerRef.current = null;
      }
    }
  }

  function stopRecording(): void {
    if (recordingTimerRef.current) {
      clearInterval(recordingTimerRef.current);
      recordingTimerRef.current = null;
    }
    if (activeRecorderRef.current && activeRecorderRef.current.state !== "inactive") {
      activeRecorderRef.current.stop();
    }
    if (activeStreamRef.current) {
      activeStreamRef.current.getTracks().forEach((t) => t.stop());
      activeStreamRef.current = null;
    }
    setIsRecording(false);
    setRecordingSeconds(0);
  }

  function removePendingAudio(): void {
    if (pendingAudioId) {
      void window.desktopApi.removeAudio({ audioId: pendingAudioId });
      setPendingAudioId(null);
      setPendingAudioDuration(0);
    }
  }

  // ── Submit ASK ────────────────────────────────────────────────────────────

  async function submitAsk(
    text: string,
    screenshotIds: string[],
    previewUrls?: string[],
    audioIds?: string[]
  ): Promise<void> {
    const ask = text.trim();
    if (!ask && !audioIds?.length) return;
    const effectiveAsk = ask || "analise o audio";
    setIsSubmitting(true);
    const tempId = globalThis.crypto.randomUUID();
    const userMsg: ChatMessage = {
      id: tempId,
      requestId: "",
      role: "user",
      content: effectiveAsk,
      createdAtIso: new Date().toISOString(),
      status: "completed",
      linkedScreenshotIds: [...screenshotIds],
      linkedScreenshotPreviewUrls: previewUrls ?? [],
      linkedAudioDuration: audioIds?.length ? pendingAudioDuration : undefined,
    };
    setChatMessages((m) => [...m, userMsg]);
    try {
      const r = await window.desktopApi.submitAsk({
        sessionId,
        ask: effectiveAsk,
        screenshotIds: screenshotIds.length > 0 ? screenshotIds : undefined,
        audioIds: audioIds?.length ? audioIds : undefined,
        presetId: undefined,
      });
      // Patch requestId on the user message
      setChatMessages((m) =>
        m.map((msg) => (msg.id === tempId ? { ...msg, requestId: r.requestId } : msg))
      );
      setPendingScreenshotIds([]);
      setAskText("");
      if (audioIds?.length) {
        for (const id of audioIds) {
          void window.desktopApi.removeAudio({ audioId: id });
        }
        setPendingAudioId(null);
        setPendingAudioDuration(0);
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Erro ao enviar.";
      setChatMessages((m) => [
        ...m,
        {
          id: globalThis.crypto.randomUUID(),
          requestId: "",
          role: "assistant",
          content: "",
          createdAtIso: new Date().toISOString(),
          status: "error",
          actionableMessage: msg,
          linkedScreenshotIds: [],
          linkedScreenshotPreviewUrls: [],
        },
      ]);
      setIsSubmitting(false);
    }
  }

  async function handleSendAsk(): Promise<void> {
    const previewUrls = pendingScreenshotIds.map(
      (id) => screenshotQueue.find((x) => x.captureId === id)?.previewDataUrl ?? ""
    );
    const audioIds = pendingAudioId ? [pendingAudioId] : [];
    await submitAsk(askText, pendingScreenshotIds, previewUrls, audioIds);
  }

  function handleAskKeyDown(e: KeyboardEvent<HTMLTextAreaElement>): void {
    if (e.ctrlKey && e.key === "Enter") {
      e.preventDefault();
      void handleSendAsk();
    }
  }

  // ── Settings: save ───────────────────────────────────────────────────────

  async function handleSetOpacity(value: number): Promise<void> {
    setOpacity(value);
    try {
      await window.desktopApi.setWindowOpacity(value);
    } catch { /* silent */ }
  }

  function handleQuit(): void {
    void window.desktopApi.quitApp();
  }

  function handleMinimize(): void {
    void window.desktopApi.minimizeWindow();
  }

  // ── Derived ──────────────────────────────────────────────────────────────

  const pendingItems = screenshotQueue.filter((q) =>
    pendingScreenshotIds.includes(q.captureId)
  );

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <>
      {/* ── Main window ──────────────────────────────────────────────── */}
      <div
        style={{
          width: "100vw",
          height: "100vh",
          background: C.bg,
          color: C.text,
          display: "flex",
          flexDirection: "column",
          fontFamily: "'Segoe UI', system-ui, sans-serif",
          fontSize: 13,
          overflow: "hidden",
          userSelect: "none",
        }}
      >
        {/* ── Topbar / drag region ──────────────────────────────────── */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "6px 10px",
            background: C.surface,
            borderBottom: `1px solid ${C.border}`,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            WebkitAppRegion: "drag",
          } as React.CSSProperties}
        >
          {/* Drag handle + logo */}
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <span
              style={{
                fontSize: 14,
                cursor: "grab",
                color: C.textDim,
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                WebkitAppRegion: "drag",
              } as React.CSSProperties}
            >
              ⠿
            </span>
            <span
              style={{
                fontWeight: 700,
                fontSize: 13,
                letterSpacing: "0.05em",
                color: C.accent,
              }}
            >
              AIGA
            </span>
          </div>

          {/* Icon bar */}
          <div
            style={{
              display: "flex",
              gap: 2,
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              WebkitAppRegion: "no-drag",
            } as React.CSSProperties}
          >
            {/* LLM status */}
            <button
              type="button"
              title={hasLlm ? "LLM configurado" : "Nenhuma LLM configurada — clique para configurar"}
              style={iconBtn()}
              onClick={() => {
                setSettingsTab("ia");
                setSettingsOpen(true);
              }}
            >
              <span
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: hasLlm ? C.success : C.error,
                  border: `1px solid ${hasLlm ? C.success : C.error}`,
                  borderRadius: 4,
                  padding: "1px 4px",
                  lineHeight: 1.4,
                }}
              >
                LLM
              </span>
            </button>

            {/* Screenshot */}
            <button
              type="button"
              title={`Capturar tela (${captureShortcut})`}
              style={iconBtn()}
              onClick={() => void handleCapture()}
            >
              📷
            </button>

            {/* Microphone — only in chat (reunião/entrevista usam captura de sistema) */}
            {appMode === "chat" && (
              !audioReady ? (
                <button
                  type="button"
                  title="Microfone não configurado — clique para configurar"
                  style={{ ...iconBtn(), opacity: 0.4 }}
                  onClick={() => { setSettingsTab("microphone"); setSettingsOpen(true); }}
                >
                  🎤️
                </button>
              ) : isRecording ? (
                <button
                  type="button"
                  title="Parar gravação"
                  style={{ ...iconBtn(), display: "flex", alignItems: "center", gap: 3, color: C.error }}
                  onClick={() => stopRecording()}
                >
                  <span style={{ fontSize: 10 }}>🔴</span>
                  <span style={{ fontSize: 11, fontVariantNumeric: "tabular-nums" }}>
                    {String(Math.floor(recordingSeconds / 60)).padStart(2, "0")}:{String(recordingSeconds % 60).padStart(2, "0")}
                  </span>
                </button>
              ) : (
                <button
                  type="button"
                  title={`Gravar áudio (${pushToTalkShortcut})`}
                  style={iconBtn()}
                  onClick={() => void toggleRecording()}
                >
                  🎤️
                </button>
              )
            )}

            {/* Modo reunião */}
            <button
              type="button"
              title="Modo reunião"
              style={iconBtn(appMode === "meeting")}
              onClick={() => {
                setAppMode("meeting");
                setSettingsOpen(false);
              }}
            >
              📋
            </button>

            {/* Modo tradução ao vivo */}
            <button
              type="button"
              title="Tradução ao vivo"
              style={iconBtn(appMode === "translation")}
              onClick={() => {
                setAppMode("translation");
                setSettingsOpen(false);
              }}
            >
              🌐
            </button>

            {/* Chat */}
            <button
              type="button"
              title="Modo chat"
              style={iconBtn(appMode === "chat")}
              onClick={() => setAppMode("chat")}
            >
              💬
            </button>

            {/* Opacity control — visible only in stealth mode */}
            {stealthEnabled && (
            <div style={{ position: "relative" }}>
              <button
                type="button"
                title={`Opacidade: ${Math.round(opacity * 100)}%`}
                style={{ ...iconBtn(opacityOpen), fontSize: 14 }}
                onClick={() => setOpacityOpen((o) => !o)}
              >
                ◑
              </button>
              {opacityOpen && (
                <div
                  onMouseDown={(e) => e.stopPropagation()}
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    right: 0,
                    background: C.surface,
                    border: `1px solid ${C.border}`,
                    borderRadius: 8,
                    padding: "10px 12px",
                    width: 160,
                    zIndex: 200,
                    display: "flex",
                    flexDirection: "column",
                    gap: 6,
                  }}
                >
                  <span style={{ fontSize: 11, color: C.textMuted, marginBottom: 2 }}>
                    Opacidade — {Math.round(opacity * 100)}%
                  </span>
                  <input
                    type="range"
                    min={5}
                    max={100}
                    step={5}
                    value={Math.round(opacity * 100)}
                    onChange={(e) => void handleSetOpacity(Number(e.target.value) / 100)}
                    style={{ width: "100%", accentColor: C.accent, cursor: "pointer" }}
                  />
                  <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: C.textDim }}>
                    <span>5%</span>
                    <span>100%</span>
                  </div>
                </div>
              )}
            </div>
            )}

            {/* Maximize / restore — same size as settings, for reading agent answers */}
            {!settingsOpen && (
              <button
                type="button"
                title={chatExpanded ? "Modo normal" : "Maximizar tela de resposta"}
                style={iconBtn(chatExpanded)}
                onClick={() => setChatExpanded((v) => !v)}
              >
                {chatExpanded ? "❐" : "⛶"}
              </button>
            )}

            {/* Settings */}
            <button
              type="button"
              title={settingsOpen ? "Voltar ao chat" : "Configurações"}
              style={iconBtn(settingsOpen)}
              onClick={() => {
                if (settingsOpen) {
                  setSettingsOpen(false);
                } else {
                  setSettingsOpen(true);
                }
              }}
            >
              ⚙️
            </button>

            {/* Separator */}
            <span style={{ width: 1, background: C.border, alignSelf: "stretch", margin: "4px 2px" }} />

            {/* Minimize — hidden in stealth mode (window cannot be recovered after minimize) */}
            {!stealthEnabled && (
            <button
              type="button"
              title="Minimizar"
              style={iconBtn()}
              onClick={handleMinimize}
            >
              ─
            </button>
            )}

            {/* Quit */}
            <button
              type="button"
              title="Fechar AIGA"
              style={iconBtn(false, true)}
              onClick={handleQuit}
            >
              ⏻
            </button>
          </div>
        </div>

        {settingsOpen ? (
          <SettingsPage
            initialTab={settingsTab}
            onClose={() => setSettingsOpen(false)}
            opacity={opacity}
            onOpacityChange={(v) => void handleSetOpacity(v)}
            autoScroll={autoScroll}
            onAutoScrollChange={setAutoScroll}
            selectToPrompt={selectToPrompt}
            onSelectToPromptChange={setSelectToPrompt}
            quickAnalysis={quickAnalysis}
            onQuickAnalysisChange={setQuickAnalysis}
            onSettingsChanged={() => void loadSettings()}
          />
        ) : appMode === "meeting" ? (
          <div
            style={{
              flex: 1,
              overflowY: "auto",
              padding: chatExpanded ? "16px 20px" : "10px 12px",
              display: "flex",
              flexDirection: "column",
              minHeight: 0,
            }}
          >
            <MeetingModePanel stealthEnabled={stealthEnabled} expanded={chatExpanded} />
          </div>
        ) : appMode === "translation" ? (
          <div
            style={{
              flex: 1,
              overflowY: "auto",
              padding: chatExpanded ? "16px 20px" : "10px 12px",
              display: "flex",
              flexDirection: "column",
              minHeight: 0,
            }}
          >
            <TranslationModePanel stealthEnabled={stealthEnabled} expanded={chatExpanded} />
          </div>
        ) : (
        <>
        {/* ── Chat timeline ─────────────────────────────────────────── */}
        <div
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "10px 12px",
            display: "flex",
            flexDirection: "column",
            gap: 8,
          }}
          onScroll={(e) => {
            const el = e.currentTarget;
            const atBottom =
              el.scrollHeight - el.scrollTop - el.clientHeight < 40;
            setAutoScroll(atBottom);
          }}
        >
          {chatMessages.length === 0 && (
            <div
              style={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: C.textDim,
                flexDirection: "column",
                gap: 6,
              }}
            >
              <span style={{ fontSize: 28 }}>🤖</span>
              <span style={{ fontSize: 12 }}>
                Faça uma pergunta ou capture a tela
              </span>
            </div>
          )}

          {chatMessages.map((msg) => (
            <div
              key={msg.id}
              style={{
                alignSelf: msg.role === "user" ? "flex-end" : "flex-start",
                maxWidth: "88%",
                background:
                  msg.role === "user" ? C.accent : C.surface2,
                borderRadius:
                  msg.role === "user"
                    ? "12px 12px 2px 12px"
                    : "12px 12px 12px 2px",
                padding: "8px 12px",
                lineHeight: 1.55,
                fontSize: 13,
                userSelect: "text",
              }}
            >
              {msg.status === "error" ? (
                <span style={{ color: C.error }}>
                  {msg.actionableMessage || "Erro desconhecido."}
                </span>
              ) : (
                <>
                  {msg.role === "user" && msg.linkedAudioDuration != null && (
                    <div style={{
                      display: "flex", alignItems: "center", gap: 4,
                      background: "rgba(255,255,255,0.12)", borderRadius: 4,
                      padding: "3px 8px", marginBottom: 6, fontSize: 11
                    }}>
                      <span>🔊</span>
                      <span>{formatAudioDuration(msg.linkedAudioDuration)} de áudio</span>
                    </div>
                  )}
                  {msg.role === "user" && msg.linkedScreenshotPreviewUrls.length > 0 && (
                    <div style={{ display: "flex", gap: 4, marginBottom: 6, flexWrap: "wrap" }}>
                      {msg.linkedScreenshotPreviewUrls.filter(Boolean).map((url, i) => (
                        <img
                          key={i}
                          src={url}
                          alt="screenshot enviado"
                          style={{
                            maxWidth: 120,
                            maxHeight: 80,
                            borderRadius: 4,
                            objectFit: "cover",
                            border: `1px solid rgba(255,255,255,0.12)`,
                          }}
                        />
                      ))}
                    </div>
                  )}
                  <span style={{ whiteSpace: "pre-wrap", color: C.text }}>
                    {msg.content ||
                      (msg.status === "pending" || msg.status === "streaming"
                        ? ""
                        : "")}
                  </span>
                  {(msg.status === "pending" ||
                    msg.status === "streaming") && (
                    <span
                      style={{ color: C.textMuted, marginLeft: 2 }}
                    >
                      ▌
                    </span>
                  )}
                </>
              )}
            </div>
          ))}
          <div ref={chatEndRef} />
        </div>

        {/* ── Pending attachments (screenshots + audio) ──────────────────── */}
        {(pendingItems.length > 0 || !!pendingAudioId) && (
          <div
            style={{
              display: "flex",
              gap: 6,
              padding: "6px 12px",
              borderTop: `1px solid ${C.border}`,
              flexWrap: "wrap",
              alignItems: "center",
            }}
          >
            {pendingItems.map((item) => (
              <div
                key={item.captureId}
                style={{ position: "relative", width: 56, height: 40 }}
              >
                <div
                  style={{
                    width: 56,
                    height: 40,
                    background: C.surface2,
                    border: `1px solid ${C.border}`,
                    borderRadius: 4,
                    overflow: "hidden",
                  }}
                >
                  <img
                    src={item.previewDataUrl}
                    alt="screenshot"
                    style={{ width: "100%", height: "100%", objectFit: "cover" }}
                  />
                </div>
                <button
                  type="button"
                  aria-label="Remover screenshot"
                  onClick={() => removeScreenshot(item.captureId)}
                  style={{
                    position: "absolute",
                    top: -6,
                    right: -6,
                    background: C.error,
                    border: "none",
                    borderRadius: "50%",
                    color: "#fff",
                    width: 16,
                    height: 16,
                    fontSize: 10,
                    cursor: "pointer",
                    padding: 0,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  ✕
                </button>
              </div>
            ))}

            {/* Audio pendente */}
            {pendingAudioId && (
              <div style={{ position: "relative" }}>
                <div
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 5,
                    background: C.surface2,
                    border: `1px solid ${C.border}`,
                    borderRadius: 6,
                    padding: "4px 10px",
                    fontSize: 12,
                    color: C.text,
                    height: 40,
                    boxSizing: "border-box",
                  }}
                >
                  <span style={{ fontSize: 16 }}>🔊</span>
                  <span style={{ fontVariantNumeric: "tabular-nums", color: C.textMuted }}>
                    {formatAudioDuration(pendingAudioDuration)}
                  </span>
                </div>
                <button
                  type="button"
                  aria-label="Remover áudio"
                  onClick={() => removePendingAudio()}
                  style={{
                    position: "absolute",
                    top: -6,
                    right: -6,
                    background: C.error,
                    border: "none",
                    borderRadius: "50%",
                    color: "#fff",
                    width: 16,
                    height: 16,
                    fontSize: 10,
                    cursor: "pointer",
                    padding: 0,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  ✕
                </button>
              </div>
            )}
          </div>
        )}

        {/* ── Input bar ─────────────────────────────────────────────── */}
        <div
          style={{
            padding: chatExpanded ? "12px 20px" : "8px 12px",
            borderTop: `1px solid ${C.border}`,
            display: "flex",
            gap: 8,
            alignItems: "stretch",
            background: C.surface,
          }}
        >
          <textarea
            value={askText}
            onChange={(e) => setAskText(e.target.value)}
            onKeyDown={handleAskKeyDown}
            placeholder="Digite sua pergunta… (Ctrl+Enter para enviar)"
            rows={chatExpanded ? 4 : 2}
            style={{
              flex: 1,
              background: C.surface2,
              border: `1px solid ${C.border}`,
              borderRadius: 8,
              color: C.text,
              padding: "8px 10px",
              fontSize: 13,
              resize: "none",
              outline: "none",
              fontFamily: "inherit",
              lineHeight: 1.5,
              userSelect: "text",
              minHeight: chatExpanded ? 96 : 56,
            }}
          />
          <button
            type="button"
            title="Enviar (Ctrl+Enter)"
            disabled={isSubmitting || !askText.trim()}
            onClick={() => void handleSendAsk()}
            style={{
              background:
                isSubmitting || !askText.trim() ? C.surface2 : C.accent,
              border: "none",
              borderRadius: 8,
              color:
                isSubmitting || !askText.trim() ? C.textMuted : "#fff",
              padding: "0 16px",
              minWidth: 52,
              alignSelf: "stretch",
              cursor:
                isSubmitting || !askText.trim() ? "not-allowed" : "pointer",
              fontSize: 20,
              lineHeight: 1,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            {isSubmitting ? "⟳" : "⏎"}
          </button>
        </div>
        </>
        )}
      </div>
    </>
  );
}
