// Generated by GitHub Copilot
import { useEffect, useMemo, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import type {
  AutoUpdateChannel,
  AutoUpdateEvent,
  AutoUpdateState,
  ChatStreamEvent,
  FeatureFlags,
  LogLevel,
  PromptPreset,
  ProviderMode,
  ScreenshotQueueItem,
  StealthStateChangedEvent,
  StealthHardening
} from "@clone-perssua/shared-types";

interface AskSubmissionItem {
  requestId: string;
  ask: string;
  screenshotIds: string[];
  createdAtIso: string;
  status: "accepted" | "started" | "chunk" | "completed" | "error";
  responseText: string;
  errorCode?: ChatStreamEvent["errorCode"];
  errorMessage?: string;
  actionableMessage?: string;
  retryable?: boolean;
}

interface ChatTimelineItem {
  id: string;
  requestId: string;
  role: "user" | "assistant";
  content: string;
  createdAtIso: string;
  status: "pending" | "streaming" | "completed" | "error";
  linkedScreenshotIds: string[];
  errorCode?: ChatStreamEvent["errorCode"];
  errorMessage?: string;
  actionableMessage?: string;
  retryable?: boolean;
}

interface AudioInputDeviceItem {
  deviceId: string;
  label: string;
}

interface AudioTranscriptItem {
  id: string;
  source: "manual" | "auto";
  isFinal: boolean;
  text: string;
  createdAtIso: string;
}

interface VadDecision {
  rms: number;
  activeFrames: number;
  frames: number;
  hasVoiceActivity: boolean;
}

interface MeetingValidationScenario {
  id: string;
  platform: "Zoom" | "Google Meet" | "Microsoft Teams";
  shareMode: "window" | "fullscreen" | "secondary-monitor";
  expectedBehavior: string;
}

interface SelfCheckDefinition {
  id: string;
  label: string;
  guidance: string;
}

// Generated by GitHub Copilot
const MEETING_VALIDATION_SCENARIOS: MeetingValidationScenario[] = [
  {
    id: "zoom-window",
    platform: "Zoom",
    shareMode: "window",
    expectedBehavior: "Janela principal nao deve exibir previews ou timeline detalhada em stealth."
  },
  {
    id: "zoom-secondary",
    platform: "Zoom",
    shareMode: "secondary-monitor",
    expectedBehavior: "Hotkey Ctrl+B deve manter controle sem trazer a janela para o monitor compartilhado."
  },
  {
    id: "meet-window",
    platform: "Google Meet",
    shareMode: "window",
    expectedBehavior: "Content protection e supressao visual devem reduzir exposicao da UI principal."
  },
  {
    id: "meet-fullscreen",
    platform: "Google Meet",
    shareMode: "fullscreen",
    expectedBehavior: "Usuario deve validar fallback seguro, pois stealth total nao e garantido em tela inteira."
  },
  {
    id: "teams-window",
    platform: "Microsoft Teams",
    shareMode: "window",
    expectedBehavior: "Atalho global deve alternar stealth sem perder recuperacao da janela."
  },
  {
    id: "teams-secondary",
    platform: "Microsoft Teams",
    shareMode: "secondary-monitor",
    expectedBehavior: "Janela deve permanecer fora do fluxo visual compartilhado quando strict estiver ativo."
  }
];

// Generated by GitHub Copilot
const STEALTH_SELF_CHECKS: SelfCheckDefinition[] = [
  {
    id: "shortcut-tested",
    label: "Atalho global de stealth testado",
    guidance: "Acione Ctrl+B duas vezes e confirme ida/volta da janela."
  },
  {
    id: "sharing-mode-reviewed",
    label: "Modo de compartilhamento revisado",
    guidance: "Prefira compartilhamento de janela ou monitor secundario; tela inteira exige cautela."
  },
  {
    id: "sensitive-panels-hidden",
    label: "Paineis sensiveis suprimidos",
    guidance: "Confirme que previews, logs e timeline detalhada estao ocultos em stealth."
  },
  {
    id: "windows-recovery-known",
    label: "Recuperacao no Windows validada",
    guidance: "Em strict no Windows, confirme que o mesmo atalho restaura a janela oculta."
  },
  {
    id: "microphone-ready",
    label: "Microfone e permissao revisados",
    guidance: "Valide que o microfone correto esta selecionado antes da apresentacao."
  },
  {
    id: "notifications-reviewed",
    label: "Sinais visuais revisados",
    guidance: "Sem flash de janela, sem progress bar e sem detalhes visuais desnecessarios."
  }
];

/**
 * Remove overlap de sufixo/prefixo entre duas strings para reduzir duplicações de chunks.
 */
function mergeTextWithOverlap(baseText: string, incomingText: string): { merged: string; removedChars: number } {
  const base = baseText.trim();
  const incoming = incomingText.trim();

  if (!base) {
    return { merged: incoming, removedChars: 0 };
  }

  if (!incoming) {
    return { merged: base, removedChars: 0 };
  }

  const normalizedBase = base.toLowerCase();
  const normalizedIncoming = incoming.toLowerCase();
  const maxOverlap = Math.min(normalizedBase.length, normalizedIncoming.length, 180);
  let overlapLength = 0;

  for (let size = 8; size <= maxOverlap; size += 1) {
    const suffix = normalizedBase.slice(-size);
    const prefix = normalizedIncoming.slice(0, size);
    if (suffix === prefix) {
      overlapLength = size;
    }
  }

  if (overlapLength === 0) {
    return {
      merged: `${base} ${incoming}`.trim(),
      removedChars: 0
    };
  }

  return {
    merged: `${base}${incoming.slice(overlapLength)}`.trim(),
    removedChars: overlapLength
  };
}

/**
 * Tela inicial do MVP.
 * Seguranca: nao renderiza segredos e prepara ponto de entrada para fluxos com validacao no main process.
 * Acessibilidade: usa landmark principal e heading para navegacao assistiva.
 */
export function App(): JSX.Element {
  const status = useMemo(() => "Bootstrap concluido: shell pronta para evolucao.", []);
  const sessionId = useMemo(() => globalThis.crypto.randomUUID(), []);
  const [pingStatus, setPingStatus] = useState("Nao testado");
  const [stealthEnabled, setStealthEnabled] = useState(false);
  const [stealthStatus, setStealthStatus] = useState("Stealth inativo");
  const [settingsStatus, setSettingsStatus] = useState("Nao carregado");
  const [language, setLanguage] = useState("pt-BR");
  const [selectedAudioInputDeviceId, setSelectedAudioInputDeviceId] = useState("");
  const [audioPermissionStatus, setAudioPermissionStatus] = useState("Nao solicitado");
  const [audioDevicesStatus, setAudioDevicesStatus] = useState("Nao carregado");
  const [audioInputDevices, setAudioInputDevices] = useState<AudioInputDeviceItem[]>([]);
  const [captureShortcut, setCaptureShortcut] = useState("Ctrl+E");
  const [pushToTalkShortcut, setPushToTalkShortcut] = useState("Ctrl+D");
  const [toggleStealthShortcut, setToggleStealthShortcut] = useState("Ctrl+B");
  const [geminiApiKey, setGeminiApiKey] = useState("");
  const [hasGeminiApiKey, setHasGeminiApiKey] = useState(false);
  const [logLevel, setLogLevel] = useState<LogLevel>("info");
  const [logFilePath, setLogFilePath] = useState("");
  const [recentLogs, setRecentLogs] = useState<string[]>([]);
  const [diagnosticsStatus, setDiagnosticsStatus] = useState("Nao carregado");
  const [autoUpdateStatus, setAutoUpdateStatus] = useState("Nao carregado");
  const [autoUpdateFeedUrl, setAutoUpdateFeedUrl] = useState("");
  const [autoUpdateChannel, setAutoUpdateChannel] = useState<AutoUpdateChannel>("stable");
  const [autoUpdateEnabled, setAutoUpdateEnabled] = useState(false);
  const [autoUpdateAllowPrerelease, setAutoUpdateAllowPrerelease] = useState(false);
  const [autoUpdateState, setAutoUpdateState] = useState<AutoUpdateState | null>(null);
  const [autoUpdateLastMessage, setAutoUpdateLastMessage] = useState("");
  const [featureStatus, setFeatureStatus] = useState("Nao carregado");
  const [envStatus, setEnvStatus] = useState("Nao carregado");
  const [providerMode, setProviderMode] = useState<ProviderMode>("cloud");
  const [localProviderEnabled, setLocalProviderEnabled] = useState(false);
  const [forceLocalOnly, setForceLocalOnly] = useState(false);
  const [stealthHardening, setStealthHardening] = useState<StealthHardening>("safe");
  const [effectiveFlags, setEffectiveFlags] = useState<FeatureFlags | null>(null);
  const [featureSourceText, setFeatureSourceText] = useState("");
  const [envSnapshotText, setEnvSnapshotText] = useState("");
  const [screenshotStatus, setScreenshotStatus] = useState("Nao carregado");
  const [screenshotQueue, setScreenshotQueue] = useState<ScreenshotQueueItem[]>([]);
  const [askText, setAskText] = useState("");
  const [askStatus, setAskStatus] = useState("Nao enviado");
  const [askGuidance, setAskGuidance] = useState("");
  const [selectedScreenshotIds, setSelectedScreenshotIds] = useState<string[]>([]);
  const [promptPresets, setPromptPresets] = useState<PromptPreset[]>([]);
  const [selectedPresetId, setSelectedPresetId] = useState("ui-analysis");
  const [askHistory, setAskHistory] = useState<AskSubmissionItem[]>([]);
  const [chatTimeline, setChatTimeline] = useState<ChatTimelineItem[]>([]);
  const [isWindowsHost] = useState(() =>
    String(globalThis.navigator?.userAgent || "").toLowerCase().includes("windows")
  );
  const [isManualRecording, setIsManualRecording] = useState(false);
  const [isAutoRecordingEnabled, setIsAutoRecordingEnabled] = useState(false);
  const [autoRecordIntervalSec, setAutoRecordIntervalSec] = useState(12);
  const [audioCaptureStatus, setAudioCaptureStatus] = useState("Inativo");
  const [audioCaptureHint, setAudioCaptureHint] = useState("");
  const [audioTranscripts, setAudioTranscripts] = useState<AudioTranscriptItem[]>([]);
  const [vadThresholdRms, setVadThresholdRms] = useState(0.015);
  const [vadWindowSize, setVadWindowSize] = useState(4);
  const [vadRecentScores, setVadRecentScores] = useState<number[]>([]);
  const [vadStatus, setVadStatus] = useState("VAD inativo");
  const [audioConsolidatedText, setAudioConsolidatedText] = useState("");
  const [audioDedupeStatus, setAudioDedupeStatus] = useState("Dedupe inativo");
  const [meetingValidationResults, setMeetingValidationResults] = useState<Record<string, "pending" | "pass" | "risk" | "fail">>({});
  const [meetingValidationNotes, setMeetingValidationNotes] = useState<Record<string, string>>({});
  const [selfCheckState, setSelfCheckState] = useState<Record<string, boolean>>({});
  const activeStreamRef = useRef<MediaStream | null>(null);
  const activeRecorderRef = useRef<MediaRecorder | null>(null);
  const autoRecordTimerRef = useRef<ReturnType<typeof globalThis.setInterval> | null>(null);
  const vadScoresRef = useRef<number[]>([]);
  const isStealthVisualSuppressionActive = stealthEnabled && stealthHardening !== "off";
  const stealthBannerText = isStealthVisualSuppressionActive
    ? "Modo stealth ativo: previews, timeline detalhada, diagnostico e transcricoes detalhadas estao suprimidos."
    : "Modo stealth inativo: interface completa visivel.";
  const isPrivacyLocalOnlyActive = Boolean(effectiveFlags?.forceLocalOnly);
  const completedSelfChecks = STEALTH_SELF_CHECKS.filter((item) => selfCheckState[item.id]).length;
  const validationCompletedCount = MEETING_VALIDATION_SCENARIOS.filter(
    (item) => meetingValidationResults[item.id] && meetingValidationResults[item.id] !== "pending"
  ).length;

  useEffect(() => {
    void loadSettings();
    void loadDiagnostics();
    void loadAutoUpdateState();
    void loadFeatureFlags();
    void loadEnvironment();
    void loadScreenshotQueue();
    void loadPromptPresets();
    void loadAudioInputDevices();

    const unsubscribe = window.desktopApi.onScreenshotQueueUpdated((payload) => {
      setScreenshotQueue(payload.items);
      setScreenshotStatus(`Fila atualizada com ${payload.items.length} item(ns)`);
    });
    const unsubscribeChat = window.desktopApi.onChatStreamEvent((payload) => {
      handleChatStreamEvent(payload);
    });
    const unsubscribeStealth = window.desktopApi.onStealthStateChanged((payload) => {
      handleStealthStateChanged(payload);
    });
    const unsubscribeAutoUpdate = window.desktopApi.onAutoUpdateEvent((payload) => {
      handleAutoUpdateEvent(payload);
    });

    return () => {
      unsubscribe();
      unsubscribeChat();
      unsubscribeStealth();
      unsubscribeAutoUpdate();

      if (autoRecordTimerRef.current !== null) {
        globalThis.clearInterval(autoRecordTimerRef.current);
        autoRecordTimerRef.current = null;
      }

      if (activeRecorderRef.current && activeRecorderRef.current.state !== "inactive") {
        activeRecorderRef.current.stop();
      }

      if (activeStreamRef.current) {
        activeStreamRef.current.getTracks().forEach((track) => track.stop());
        activeStreamRef.current = null;
      }
    };
  }, []);

  useEffect(() => {
    const onWindowKeyDown = (event: globalThis.KeyboardEvent) => {
      if (event.ctrlKey && (event.key === "d" || event.key === "D")) {
        event.preventDefault();
        void handleManualRecordToggle();
      }
    };

    globalThis.addEventListener("keydown", onWindowKeyDown);
    return () => {
      globalThis.removeEventListener("keydown", onWindowKeyDown);
    };
  });

  /**
   * Mantém o estado de stealth sincronizado quando o toggle ocorre por IPC ou hotkey global.
   */
  function handleStealthStateChanged(payload: StealthStateChangedEvent): void {
    setStealthEnabled(payload.enabled);
    setStealthStatus(
      payload.enabled
        ? `Stealth ativo via ${payload.source} (${payload.hardening}) em ${payload.appliedAtIso}`
        : `Stealth desativado via ${payload.source} em ${payload.appliedAtIso}`
    );
  }

  /**
   * Mantem renderer sincronizado com os eventos do updater emitidos pelo main process.
   */
  function handleAutoUpdateEvent(payload: AutoUpdateEvent): void {
    setAutoUpdateState(payload.state);
    setAutoUpdateEnabled(payload.state.config.enabled);
    setAutoUpdateFeedUrl(payload.state.config.feedUrl || "");
    setAutoUpdateChannel(payload.state.config.channel);
    setAutoUpdateAllowPrerelease(payload.state.config.allowPrerelease);
    setAutoUpdateStatus(`${payload.kind}: ${payload.message}`);
    setAutoUpdateLastMessage(payload.message);
  }

  /**
   * Atualiza resultado manual da matriz de validacao de reuniao.
   */
  function handleMeetingValidationResultChange(
    scenarioId: string,
    status: "pending" | "pass" | "risk" | "fail"
  ): void {
    setMeetingValidationResults((current) => ({
      ...current,
      [scenarioId]: status
    }));
  }

  /**
   * Atualiza anotacoes operacionais para a matriz de validacao.
   */
  function handleMeetingValidationNoteChange(scenarioId: string, note: string): void {
    setMeetingValidationNotes((current) => ({
      ...current,
      [scenarioId]: note
    }));
  }

  /**
   * Marca ou desmarca item do self-check pre-apresentacao.
   */
  function handleSelfCheckToggle(checkId: string): void {
    setSelfCheckState((current) => ({
      ...current,
      [checkId]: !current[checkId]
    }));
  }

  /**
   * Atualiza a timeline local com os eventos de stream recebidos do main process.
   */
  function handleChatStreamEvent(payload: ChatStreamEvent): void {
    setAskHistory((current) =>
      current.map((item) => {
        if (item.requestId !== payload.requestId) {
          return item;
        }

        return {
          ...item,
          status: payload.status,
          responseText: payload.fullText || item.responseText,
          errorCode: payload.errorCode,
          errorMessage: payload.errorMessage,
          actionableMessage: payload.actionableMessage,
          retryable: payload.retryable
        };
      })
    );

    setChatTimeline((current) => {
      const existingIndex = current.findIndex(
        (item) => item.requestId === payload.requestId && item.role === "assistant"
      );

      if (existingIndex === -1) {
        return [
          {
            id: `${payload.requestId}-assistant`,
            requestId: payload.requestId,
            role: "assistant",
            content: payload.fullText || payload.deltaText || "",
            createdAtIso: payload.createdAtIso,
            status:
              payload.status === "completed"
                ? "completed"
                : payload.status === "error"
                  ? "error"
                  : "streaming",
            linkedScreenshotIds: [],
            errorCode: payload.errorCode,
            errorMessage: payload.errorMessage
            ,
            actionableMessage: payload.actionableMessage,
            retryable: payload.retryable
          },
          ...current
        ];
      }

      return current.map((item, index) => {
        if (index !== existingIndex) {
          return item;
        }

        return {
          ...item,
          content: payload.fullText || item.content || payload.deltaText || "",
          status:
            payload.status === "completed"
              ? "completed"
              : payload.status === "error"
                ? "error"
                : "streaming",
          errorCode: payload.errorCode,
          errorMessage: payload.errorMessage,
          actionableMessage: payload.actionableMessage,
          retryable: payload.retryable,
          createdAtIso: payload.createdAtIso || item.createdAtIso
        };
      });
    });

    if (payload.status === "error") {
      setAskStatus(`Falha no stream: ${payload.errorMessage || "Erro desconhecido"}`);
      setAskGuidance(payload.actionableMessage || "Revise Settings e tente novamente.");
    }

    if (payload.status === "completed") {
      setAskStatus(`Resposta concluida para ${payload.requestId}`);
      setAskGuidance("");
    }
  }

  useEffect(() => {
    setSelectedScreenshotIds((current) =>
      current.filter((captureId) => screenshotQueue.some((item) => item.captureId === captureId))
    );
  }, [screenshotQueue]);

  /**
   * Solicita permissao de microfone, passo principal para liberar labels de device no Windows.
   */
  async function requestMicrophonePermission(): Promise<void> {
    try {
      const stream = await globalThis.navigator.mediaDevices.getUserMedia({ audio: true });
      stream.getTracks().forEach((track) => track.stop());
      setAudioPermissionStatus("Permissao concedida");
      await loadAudioInputDevices();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAudioPermissionStatus(`Permissao negada: ${message}`);
      setAudioDevicesStatus(
        "No Windows, habilite acesso ao microfone em Configuracoes > Privacidade e seguranca > Microfone."
      );
    }
  }

  /**
   * Carrega dispositivos de entrada de audio disponiveis no host.
   */
  async function loadAudioInputDevices(): Promise<void> {
    if (!globalThis.navigator?.mediaDevices?.enumerateDevices) {
      setAudioDevicesStatus("API de dispositivos de midia indisponivel neste ambiente.");
      return;
    }

    try {
      const devices = await globalThis.navigator.mediaDevices.enumerateDevices();
      const inputs = devices
        .filter((device) => device.kind === "audioinput")
        .map((device, index) => ({
          deviceId: device.deviceId,
          label: device.label || `Microfone ${index + 1} (conceda permissao para ver o nome)`
        }));

      setAudioInputDevices(inputs);
      setAudioDevicesStatus(`Encontrado(s) ${inputs.length} dispositivo(s) de entrada.`);

      if (inputs.length > 0 && !inputs.some((item) => item.deviceId === selectedAudioInputDeviceId)) {
        setSelectedAudioInputDeviceId(inputs[0].deviceId);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAudioDevicesStatus(`Falha ao listar dispositivos: ${message}`);
    }
  }

  /**
   * Testa captura rapida no dispositivo selecionado para validacao local.
   */
  async function testSelectedMicrophone(): Promise<void> {
    try {
      const audioConstraint = selectedAudioInputDeviceId
        ? { deviceId: { exact: selectedAudioInputDeviceId } }
        : true;
      const stream = await globalThis.navigator.mediaDevices.getUserMedia({
        audio: audioConstraint
      });

      stream.getTracks().forEach((track) => track.stop());
      setAudioDevicesStatus("Teste de microfone concluido com sucesso.");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAudioDevicesStatus(`Falha no teste de microfone: ${message}`);
    }
  }

  /**
   * Converte blob de áudio para base64 para transporte por IPC.
   */
  async function blobToBase64(blob: Blob): Promise<string> {
    const buffer = await blob.arrayBuffer();
    const bytes = new Uint8Array(buffer);
    let binary = "";

    for (let index = 0; index < bytes.length; index += 1) {
      binary += String.fromCharCode(bytes[index]);
    }

    return globalThis.btoa(binary);
  }

  /**
   * Estima energia RMS do áudio para VAD simples baseado em limiar.
   */
  async function calculateAudioRms(blob: Blob): Promise<number> {
    const AudioContextClass = globalThis.AudioContext || (globalThis as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!AudioContextClass) {
      return 1;
    }

    const context = new AudioContextClass();
    try {
      const arrayBuffer = await blob.arrayBuffer();
      const decoded = await context.decodeAudioData(arrayBuffer);
      const channelData = decoded.getChannelData(0);

      if (channelData.length === 0) {
        return 0;
      }

      let sumSquares = 0;
      for (let index = 0; index < channelData.length; index += 1) {
        const sample = channelData[index];
        sumSquares += sample * sample;
      }

      return Math.sqrt(sumSquares / channelData.length);
    } finally {
      await context.close();
    }
  }

  /**
   * Aplica janela deslizante para decidir se há atividade de voz suficiente.
   */
  function evaluateVadWindow(rms: number): VadDecision {
    const normalizedWindow = Math.max(2, Math.min(8, vadWindowSize));
    const nextScores = [...vadScoresRef.current, rms].slice(-normalizedWindow);
    vadScoresRef.current = nextScores;
    setVadRecentScores(nextScores);

    const activeFrames = nextScores.filter((score) => score >= vadThresholdRms).length;
    const minFramesForSpeech = Math.max(1, Math.ceil(nextScores.length / 2));
    const hasVoiceActivity = activeFrames >= minFramesForSpeech;

    setVadStatus(
      `RMS atual ${rms.toFixed(4)} | ativos ${activeFrames}/${nextScores.length} | limiar ${vadThresholdRms.toFixed(4)}`
    );

    return {
      rms,
      activeFrames,
      frames: nextScores.length,
      hasVoiceActivity
    };
  }

  /**
   * Executa uma captura única de áudio e envia para transcrição.
   */
  async function recordSingleAudioChunk(source: "manual" | "auto", maxDurationMs: number): Promise<void> {
    if (activeRecorderRef.current && activeRecorderRef.current.state !== "inactive") {
      setAudioCaptureStatus("Aguardando gravacao atual terminar...");
      return;
    }

    try {
      const audioConstraint = selectedAudioInputDeviceId
        ? { deviceId: { exact: selectedAudioInputDeviceId } }
        : true;

      const stream = await globalThis.navigator.mediaDevices.getUserMedia({ audio: audioConstraint });
      activeStreamRef.current = stream;

      const recorder = new MediaRecorder(stream, { mimeType: "audio/webm" });
      activeRecorderRef.current = recorder;
      const chunks: BlobPart[] = [];

      recorder.ondataavailable = (event) => {
        if (event.data && event.data.size > 0) {
          chunks.push(event.data);
        }
      };

      recorder.onerror = (event) => {
        setAudioCaptureStatus(`Erro no recorder: ${event.error?.message || "desconhecido"}`);
      };

      recorder.onstop = async () => {
        try {
          stream.getTracks().forEach((track) => track.stop());
          activeStreamRef.current = null;

          if (chunks.length === 0) {
            setAudioCaptureStatus("Nenhum audio coletado no intervalo.");
            return;
          }

          const audioBlob = new Blob(chunks, { type: "audio/webm" });
          const rms = await calculateAudioRms(audioBlob);
          const vadDecision = evaluateVadWindow(rms);

          if (!vadDecision.hasVoiceActivity) {
            setAudioCaptureStatus(
              `Silencio dominante detectado (${vadDecision.activeFrames}/${vadDecision.frames}); chunk descartado.`
            );
            setAudioCaptureHint("Ajuste limiar/janela do VAD se sua voz estiver baixa ou distante do microfone.");
            return;
          }

          const chunkBase64 = await blobToBase64(audioBlob);
          const transcription = await window.desktopApi.transcribeAudioChunk({
            sessionId,
            chunkBase64,
            language
          });

          let removedOverlapChars = 0;
          let dedupedChunkText = transcription.text;

          setAudioConsolidatedText((current) => {
            const merged = mergeTextWithOverlap(current, transcription.text);
            removedOverlapChars = merged.removedChars;
            dedupedChunkText = transcription.text.trim() && merged.removedChars > 0
              ? transcription.text.slice(merged.removedChars).trim() || transcription.text
              : transcription.text;
            return merged.merged;
          });

          setAudioDedupeStatus(
            removedOverlapChars > 0
              ? `Overlap removido: ${removedOverlapChars} caractere(s) no ultimo chunk.`
              : "Sem overlap relevante no ultimo chunk."
          );

          setAudioTranscripts((current) => [
            {
              id: globalThis.crypto.randomUUID(),
              source,
              isFinal: transcription.isFinal,
              text: dedupedChunkText,
              createdAtIso: new Date().toISOString()
            },
            ...current
          ].slice(0, 20));

          setAudioCaptureStatus(
            source === "manual"
              ? "Gravacao manual concluida e enviada para transcricao."
              : "Ciclo automatico concluido e enviado para transcricao."
          );
          setAudioCaptureHint(
            `VAD aprovou o chunk com RMS ${vadDecision.rms.toFixed(4)} (${vadDecision.activeFrames}/${vadDecision.frames} frames ativos).`
          );
        } catch (error) {
          const message = error instanceof Error ? error.message : "Erro desconhecido";
          setAudioCaptureStatus(`Falha na transcricao: ${message}`);
          setAudioCaptureHint(
            "No Windows, valide permissao de microfone e se outro aplicativo nao monopolizou o dispositivo."
          );
        } finally {
          activeRecorderRef.current = null;
          if (source === "manual") {
            setIsManualRecording(false);
          }
        }
      };

      recorder.start();
      if (source === "manual") {
        setIsManualRecording(true);
        setAudioCaptureStatus("Gravando manualmente...");
      } else {
        setAudioCaptureStatus("Gravando ciclo automatico...");
      }

      globalThis.setTimeout(() => {
        if (recorder.state !== "inactive") {
          recorder.stop();
        }
      }, maxDurationMs);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAudioCaptureStatus(`Falha ao iniciar gravacao: ${message}`);
      setAudioCaptureHint(
        "No Windows, habilite acesso ao microfone em Configuracoes > Privacidade e seguranca > Microfone."
      );
      setIsManualRecording(false);
    }
  }

  /**
   * Alterna gravação manual (atalho Ctrl+D também disponível).
   */
  async function handleManualRecordToggle(): Promise<void> {
    if (isManualRecording && activeRecorderRef.current && activeRecorderRef.current.state !== "inactive") {
      activeRecorderRef.current.stop();
      setAudioCaptureStatus("Encerrando gravacao manual...");
      return;
    }

    await recordSingleAudioChunk("manual", 8000);
  }

  /**
   * Alterna modo automático por intervalo configurável (10-20s).
   */
  function handleAutoRecordToggle(): void {
    if (isAutoRecordingEnabled) {
      setIsAutoRecordingEnabled(false);
      if (autoRecordTimerRef.current !== null) {
        globalThis.clearInterval(autoRecordTimerRef.current);
        autoRecordTimerRef.current = null;
      }
      setAudioCaptureStatus("Modo automatico desativado.");
      return;
    }

    const clamped = Math.max(10, Math.min(20, autoRecordIntervalSec));
    setAutoRecordIntervalSec(clamped);
    setIsAutoRecordingEnabled(true);
    setAudioCaptureStatus(`Modo automatico ativo a cada ${clamped}s.`);

    autoRecordTimerRef.current = globalThis.setInterval(() => {
      void recordSingleAudioChunk("auto", 6000);
    }, clamped * 1000);
  }

  /**
   * Carrega presets de prompt disponíveis no main process.
   */
  async function loadPromptPresets(): Promise<void> {
    try {
      const response = await window.desktopApi.getPromptPresets();
      setPromptPresets(response.presets);

      if (response.presets.length > 0 && !response.presets.some((item) => item.id === selectedPresetId)) {
        setSelectedPresetId(response.presets[0].id);
      }
    } catch {
      setPromptPresets([]);
    }
  }

  /**
   * Carrega a fila atual de screenshots do main process.
   */
  async function loadScreenshotQueue(): Promise<void> {
    try {
      const response = await window.desktopApi.getScreenshotQueue();
      setScreenshotQueue(response.items);
      setScreenshotStatus(`Fila carregada com ${response.items.length} item(ns)`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setScreenshotStatus(`Falha ao carregar fila: ${message}`);
    }
  }

  /**
   * Dispara captura manual de screenshot para validar o pipeline de B1.
   */
  async function handleCaptureScreenshot(): Promise<void> {
    try {
      const response = await window.desktopApi.captureScreenshot({ source: "full" });
      setScreenshotStatus(`Screenshot capturada em ${response.createdAtIso}`);
      setScreenshotQueue((current) => [response, ...current.filter((item) => item.captureId !== response.captureId)].slice(0, 10));
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setScreenshotStatus(`Falha na captura: ${message}`);
    }
  }

  /**
   * Limpa a fila e remove os arquivos temporários correspondentes.
   */
  async function handleClearScreenshotQueue(): Promise<void> {
    try {
      const response = await window.desktopApi.clearScreenshotQueue();
      setScreenshotQueue(response.items);
      setSelectedScreenshotIds([]);
      setScreenshotStatus(`Fila limpa em ${response.clearedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setScreenshotStatus(`Falha ao limpar fila: ${message}`);
    }
  }

  /**
   * Carrega estado de variáveis de ambiente efetivas para o runtime.
   */
  async function loadEnvironment(): Promise<void> {
    try {
      const response = await window.desktopApi.getEnvironment();
      setEnvSnapshotText(JSON.stringify(response.env, null, 2));
      setEnvStatus("Ambiente carregado");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setEnvStatus(`Falha ao ler ambiente: ${message}`);
    }
  }

  /**
   * Carrega feature flags persistidas e efetivas (com override de env).
   */
  async function loadFeatureFlags(): Promise<void> {
    try {
      const response = await window.desktopApi.getFeatureFlags();
      setProviderMode(response.persisted.providerMode);
      setLocalProviderEnabled(response.persisted.localProviderEnabled);
      setForceLocalOnly(response.persisted.forceLocalOnly);
      setStealthHardening(response.persisted.stealthHardening);
      setEffectiveFlags(response.effective);
      setFeatureSourceText(JSON.stringify(response.source));
      setFeatureStatus("Feature flags carregadas");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setFeatureStatus(`Falha ao carregar flags: ${message}`);
    }
  }

  /**
   * Persiste alterações de feature flags no main process.
   */
  async function handleSaveFeatureFlags(): Promise<void> {
    try {
      const response = await window.desktopApi.saveFeatureFlags({
        providerMode,
        localProviderEnabled,
        forceLocalOnly,
        stealthHardening
      });

      setEffectiveFlags(response.effective);
      setFeatureSourceText(JSON.stringify(response.source));
      setFeatureStatus(`Feature flags salvas em ${response.savedAtIso}`);
      await loadEnvironment();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setFeatureStatus(`Falha ao salvar flags: ${message}`);
    }
  }

  /**
   * Restaura feature flags persistidas para default.
   */
  async function handleResetFeatureFlags(): Promise<void> {
    try {
      const response = await window.desktopApi.resetFeatureFlags();
      setProviderMode(response.persisted.providerMode);
      setLocalProviderEnabled(response.persisted.localProviderEnabled);
      setForceLocalOnly(response.persisted.forceLocalOnly);
      setStealthHardening(response.persisted.stealthHardening);
      setEffectiveFlags(response.effective);
      setFeatureSourceText(JSON.stringify(response.source));
      setFeatureStatus(`Feature flags resetadas em ${response.resetAtIso}`);
      await loadEnvironment();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setFeatureStatus(`Falha ao resetar flags: ${message}`);
    }
  }

  /**
   * Carrega dados de diagnóstico para observabilidade local.
   */
  async function loadDiagnostics(): Promise<void> {
    try {
      const response = await window.desktopApi.getDiagnostics();
      setLogLevel(response.logLevel);
      setLogFilePath(response.logFilePath);
      setRecentLogs(response.recentLines);
      setDiagnosticsStatus("Diagnostico carregado");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setDiagnosticsStatus(`Falha no diagnostico: ${message}`);
    }
  }

  /**
   * Carrega snapshot atual do auto-update e hidrata o formulario local.
   */
  async function loadAutoUpdateState(): Promise<void> {
    try {
      const response = await window.desktopApi.getAutoUpdateState();
      setAutoUpdateState(response.state);
      setAutoUpdateEnabled(response.state.config.enabled);
      setAutoUpdateFeedUrl(response.state.config.feedUrl || "");
      setAutoUpdateChannel(response.state.config.channel);
      setAutoUpdateAllowPrerelease(response.state.config.allowPrerelease);
      setAutoUpdateStatus(`Auto-update carregado (${response.state.status})`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao carregar auto-update: ${message}`);
    }
  }

  /**
   * Persiste configuracao de feed/canal sem disparar rede automaticamente.
   */
  async function handleSaveAutoUpdateConfig(): Promise<void> {
    try {
      const response = await window.desktopApi.saveAutoUpdateConfig({
        enabled: autoUpdateEnabled,
        feedUrl: autoUpdateFeedUrl.trim() || null,
        channel: autoUpdateChannel,
        allowPrerelease: autoUpdateAllowPrerelease
      });
      setAutoUpdateState(response.state);
      setAutoUpdateStatus(`Configuracao de auto-update salva em ${response.savedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao salvar auto-update: ${message}`);
    }
  }

  /**
   * Dispara verificacao remota de atualizacoes no canal configurado.
   */
  async function handleCheckForAutoUpdate(): Promise<void> {
    try {
      const response = await window.desktopApi.checkForAutoUpdate();
      setAutoUpdateState(response.state);
      setAutoUpdateStatus(`Check de update iniciado em ${response.checkedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao verificar update: ${message}`);
    }
  }

  /**
   * Baixa a atualizacao encontrada para aplicacao controlada no restart.
   */
  async function handleDownloadAutoUpdate(): Promise<void> {
    try {
      const response = await window.desktopApi.downloadAutoUpdate();
      setAutoUpdateState(response.state);
      setAutoUpdateStatus(`Download de update iniciado em ${response.startedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao baixar update: ${message}`);
    }
  }

  /**
   * Agenda a instalacao da versao baixada no encerramento do app.
   */
  async function handleInstallAutoUpdate(): Promise<void> {
    try {
      const response = await window.desktopApi.installAutoUpdate();
      setAutoUpdateStatus(`Instalacao agendada em ${response.appliedAtIso}; reinicie o app.`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao agendar instalacao: ${message}`);
    }
  }

  /**
   * Solicita rollback para o canal anterior com downgrade controlado.
   */
  async function handleRollbackAutoUpdate(): Promise<void> {
    try {
      const response = await window.desktopApi.rollbackAutoUpdate({
        channel: autoUpdateState?.rollbackChannel || "stable"
      });
      setAutoUpdateState(response.state);
      setAutoUpdateStatus(`Rollback solicitado em ${response.acceptedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao iniciar rollback: ${message}`);
    }
  }

  /**
   * Confirma que a versao atual passou no health check operacional apos update.
   */
  async function handleConfirmAutoUpdateHealth(): Promise<void> {
    try {
      const response = await window.desktopApi.confirmAutoUpdateHealth();
      setAutoUpdateState(response.state);
      setAutoUpdateStatus(`Saude confirmada em ${response.confirmedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAutoUpdateStatus(`Falha ao confirmar saude da versao: ${message}`);
    }
  }

  /**
   * Atualiza nível de log no processo principal para ajustar verbosidade em runtime.
   */
  async function handleLogLevelChange(nextLevel: LogLevel): Promise<void> {
    try {
      const response = await window.desktopApi.setLogLevel({ level: nextLevel });
      setLogLevel(response.logLevel);
      setDiagnosticsStatus(`Nivel de log atualizado em ${response.updatedAtIso}`);
      await loadDiagnostics();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setDiagnosticsStatus(`Falha ao atualizar nivel: ${message}`);
    }
  }

  /**
   * Carrega configurações persistidas no main process.
   */
  async function loadSettings(): Promise<void> {
    try {
      const response = await window.desktopApi.getSettings();
      setLanguage(response.settings.language);
      setSelectedAudioInputDeviceId(response.settings.selectedAudioInputDeviceId || "");
      setCaptureShortcut(response.settings.shortcuts.captureScreen);
      setPushToTalkShortcut(response.settings.shortcuts.pushToTalk);
      setToggleStealthShortcut(response.settings.shortcuts.toggleStealth);
      setHasGeminiApiKey(response.settings.hasGeminiApiKey);
      setSettingsStatus("Configuracoes carregadas");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setSettingsStatus(`Falha ao carregar: ${message}`);
    }
  }

  /**
   * Executa healthcheck via IPC para validar contrato tipado renderer/main.
   */
  async function handlePing(): Promise<void> {
    try {
      const response = await window.desktopApi.ping({});
      setPingStatus(`OK em ${response.timestampIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setPingStatus(`Falha: ${message}`);
    }
  }

  /**
   * Alterna modo stealth via IPC; resultado vem confirmado pelo main process.
   */
  async function handleToggleStealth(): Promise<void> {
    try {
      const nextEnabled = !stealthEnabled;
      const response = await window.desktopApi.setStealthMode({ enabled: nextEnabled });
      setStealthEnabled(response.enabled);
      setStealthStatus(
        response.enabled
          ? `Stealth ativado manualmente em ${response.appliedAtIso}`
          : `Stealth desativado manualmente em ${response.appliedAtIso}`
      );
    } catch {
      setPingStatus("Falha ao alternar stealth");
    }
  }

  /**
   * Salva preferências do usuário com persistência local no main process.
   */
  async function handleSaveSettings(): Promise<void> {
    try {
      const response = await window.desktopApi.saveSettings({
        language,
        selectedAudioInputDeviceId: selectedAudioInputDeviceId || null,
        shortcuts: {
          captureScreen: captureShortcut,
          pushToTalk: pushToTalkShortcut,
          toggleStealth: toggleStealthShortcut
        },
        geminiApiKey: geminiApiKey.trim() ? geminiApiKey.trim() : undefined
      });

      setHasGeminiApiKey(response.settings.hasGeminiApiKey);
      setGeminiApiKey("");
      setSettingsStatus(`Configuracoes salvas em ${response.savedAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setSettingsStatus(`Falha ao salvar: ${message}`);
    }
  }

  /**
   * Restaura configurações padrão do aplicativo.
   */
  async function handleResetSettings(): Promise<void> {
    try {
      const response = await window.desktopApi.resetSettings();
      setLanguage(response.settings.language);
      setSelectedAudioInputDeviceId(response.settings.selectedAudioInputDeviceId || "");
      setCaptureShortcut(response.settings.shortcuts.captureScreen);
      setPushToTalkShortcut(response.settings.shortcuts.pushToTalk);
      setToggleStealthShortcut(response.settings.shortcuts.toggleStealth);
      setHasGeminiApiKey(response.settings.hasGeminiApiKey);
      setGeminiApiKey("");
      setSettingsStatus(`Configuracoes resetadas em ${response.resetAtIso}`);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setSettingsStatus(`Falha ao resetar: ${message}`);
    }
  }

  /**
   * Alterna seleção da screenshot para envio no prompt ASK.
   */
  function handleToggleScreenshotSelection(captureId: string): void {
    setSelectedScreenshotIds((current) =>
      current.includes(captureId)
        ? current.filter((item) => item !== captureId)
        : [...current, captureId]
    );
  }

  /**
   * Envia o ASK atual com o subconjunto de screenshots selecionado.
   */
  async function handleSubmitAsk(): Promise<void> {
    const normalizedAsk = askText.trim();
    await submitAskPayload(normalizedAsk, selectedScreenshotIds);
  }

  /**
   * Envia um payload ASK explícito para evitar dependência de sincronização de state.
   */
  async function submitAskPayload(ask: string, screenshotIds: string[]): Promise<void> {
    const normalizedAsk = ask.trim();
    if (!normalizedAsk) {
      setAskStatus("Digite uma instrucao ASK antes de enviar.");
      return;
    }

    try {
      const response = await window.desktopApi.submitAsk({
        sessionId,
        ask: normalizedAsk,
        screenshotIds: screenshotIds.length > 0 ? screenshotIds : undefined,
        presetId: selectedPresetId
      });

      setAskHistory((current) => [
        {
          requestId: response.requestId,
          ask: normalizedAsk,
          screenshotIds: [...screenshotIds],
          createdAtIso: new Date().toISOString(),
          status: response.status,
          responseText: ""
        },
        ...current
      ].slice(0, 10));
      setChatTimeline((current) => {
        const nextEntries: ChatTimelineItem[] = [
          {
            id: `${response.requestId}-user`,
            requestId: response.requestId,
            role: "user",
            content: normalizedAsk,
            createdAtIso: new Date().toISOString(),
            status: "completed",
            linkedScreenshotIds: [...screenshotIds]
          },
          {
            id: `${response.requestId}-assistant`,
            requestId: response.requestId,
            role: "assistant",
            content: "",
            createdAtIso: new Date().toISOString(),
            status: "pending",
            linkedScreenshotIds: [...screenshotIds]
          }
        ];

        return [...nextEntries, ...current].slice(0, 24);
      });
      setAskStatus(`ASK aceita com request ${response.requestId}`);
      setAskGuidance("");
      setAskText("");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Erro desconhecido";
      setAskStatus(`Falha ao enviar ASK: ${message}`);
      setAskGuidance("Verifique sua conexão e as configuracoes da API key antes de tentar novamente.");
    }
  }

  /**
   * Reenvia o ultimo ASK com falha e marcado como retryable.
   */
  async function handleRetryLastFailedAsk(): Promise<void> {
    const lastFailed = askHistory.find((item) => item.status === "error" && item.retryable);
    if (!lastFailed) {
      setAskStatus("Nao ha ASK com falha e retry disponivel.");
      return;
    }

    setAskText(lastFailed.ask);
    setSelectedScreenshotIds(lastFailed.screenshotIds);
    await submitAskPayload(lastFailed.ask, lastFailed.screenshotIds);
  }

  /**
   * Atalho local de teclado para envio do ASK via Ctrl+Enter.
   */
  function handleAskKeyDown(event: KeyboardEvent<HTMLTextAreaElement>): void {
    if (event.ctrlKey && event.key === "Enter") {
      event.preventDefault();
      void handleSubmitAsk();
    }
  }

  return (
    <main style={{ fontFamily: "Segoe UI, sans-serif", padding: 24 }}>
      <h1>Clone Perssua</h1>
      <p>{status}</p>
      <section aria-label="Validacao de IPC" style={{ marginBottom: 20 }}>
        <h2>Validacao de IPC tipado</h2>
        <p>Status ping: {pingStatus}</p>
        <p>{stealthStatus}</p>
        <p>{stealthBannerText}</p>
        <button onClick={handlePing} type="button" style={{ marginRight: 8 }}>
          Testar ping
        </button>
        <button onClick={handleToggleStealth} type="button" aria-pressed={stealthEnabled}>
          Stealth: {stealthEnabled ? "Ativo" : "Inativo"}
        </button>
        <p style={{ marginTop: 8 }}>
          Hotkey global de stealth: {toggleStealthShortcut}. Em `strict` no Windows a janela pode ser ocultada e o mesmo atalho restaura a interface.
        </p>
      </section>
      <section aria-label="Fila de screenshots" style={{ marginBottom: 20 }}>
        <h2>Screenshots</h2>
        <p>{screenshotStatus}</p>
        <p>Atalho global configurado: {captureShortcut}</p>
        <button type="button" onClick={handleCaptureScreenshot} style={{ marginRight: 8 }}>
          Capturar agora
        </button>
        <button type="button" onClick={handleClearScreenshotQueue} style={{ marginRight: 8 }}>
          Limpar fila
        </button>
        <button type="button" onClick={() => void loadScreenshotQueue()}>
          Recarregar fila
        </button>
        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {screenshotQueue.length > 0 ? (
            screenshotQueue.map((item) => (
              <article
                key={item.captureId}
                style={{
                  display: "grid",
                  gap: 8,
                  border: "1px solid #d0d0d0",
                  borderRadius: 8,
                  padding: 12,
                  maxWidth: 520
                }}
              >
                <label>
                  <input
                    type="checkbox"
                    checked={selectedScreenshotIds.includes(item.captureId)}
                    onChange={() => handleToggleScreenshotSelection(item.captureId)}
                  />
                  Selecionar para ASK
                </label>
                <strong>{item.createdAtIso}</strong>
                <span>
                  Trigger: {item.trigger} | Source: {item.source}
                </span>
                {isStealthVisualSuppressionActive ? (
                  <p style={{ margin: 0 }}>
                    Preview e caminho ocultos em modo stealth. Capture ID: {item.captureId}
                  </p>
                ) : (
                  <>
                    <span>{item.imagePath}</span>
                    <img
                      src={item.previewDataUrl}
                      alt={`Preview da captura ${item.captureId}`}
                      style={{ width: "100%", maxWidth: 360, borderRadius: 6, border: "1px solid #ccc" }}
                    />
                  </>
                )}
              </article>
            ))
          ) : (
            <p>Nenhuma screenshot na fila.</p>
          )}
        </div>
      </section>
      <section aria-label="Composer ASK" style={{ marginBottom: 20 }}>
        <h2>ASK e envio</h2>
        <p>{askStatus}</p>
        {askGuidance ? <p>Acao recomendada: {askGuidance}</p> : null}
        <p>Sessao atual: {sessionId}</p>
        <p>Screenshots selecionadas: {selectedScreenshotIds.length}</p>
        <label style={{ display: "grid", gap: 8, maxWidth: 420, marginBottom: 10 }}>
          Preset de prompt
          <select
            value={selectedPresetId}
            onChange={(event) => setSelectedPresetId(event.target.value)}
          >
            {promptPresets.length > 0 ? (
              promptPresets.map((preset) => (
                <option key={preset.id} value={preset.id}>
                  {preset.title}
                </option>
              ))
            ) : (
              <option value="ui-analysis">Analise de UI</option>
            )}
          </select>
          {promptPresets.length > 0 ? (
            <small>
              {promptPresets.find((preset) => preset.id === selectedPresetId)?.description || ""}
            </small>
          ) : null}
        </label>
        <label style={{ display: "grid", gap: 8, maxWidth: 720 }}>
          Instrucao ASK
          <textarea
            value={askText}
            onChange={(event) => setAskText(event.target.value)}
            onKeyDown={handleAskKeyDown}
            rows={5}
            placeholder="Descreva o que deve ser analisado nesta captura..."
          />
        </label>
        <div style={{ marginTop: 10 }}>
          <button type="button" onClick={() => void handleSubmitAsk()} style={{ marginRight: 8 }}>
            Enviar ASK
          </button>
          <button type="button" onClick={() => setAskText("")} style={{ marginRight: 8 }}>
            Limpar texto
          </button>
          <button type="button" onClick={() => setSelectedScreenshotIds(screenshotQueue.map((item) => item.captureId))}>
            Selecionar todas as screenshots
          </button>
          <button type="button" onClick={() => void handleRetryLastFailedAsk()} style={{ marginLeft: 8 }}>
            Reenviar ultimo ASK com falha
          </button>
        </div>
        <p style={{ marginTop: 8 }}>Atalho local: Ctrl+Enter para enviar.</p>
        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {askHistory.length > 0 ? (
            askHistory.map((item) => (
              <article
                key={item.requestId}
                style={{
                  display: "grid",
                  gap: 6,
                  border: "1px solid #d0d0d0",
                  borderRadius: 8,
                  padding: 12,
                  maxWidth: 720
                }}
              >
                <strong>{item.createdAtIso}</strong>
                <span>Request ID: {item.requestId}</span>
                <span>Status: {item.status}</span>
                {item.errorCode ? <span>Codigo: {item.errorCode}</span> : null}
                <span>Screenshots vinculadas: {item.screenshotIds.length}</span>
                <p style={{ margin: 0, whiteSpace: "pre-wrap" }}>{item.ask}</p>
                <p style={{ margin: 0, whiteSpace: "pre-wrap" }}>
                  {item.responseText || "Aguardando resposta incremental..."}
                </p>
                {item.errorMessage ? <p style={{ margin: 0 }}>Erro: {item.errorMessage}</p> : null}
                {item.actionableMessage ? <p style={{ margin: 0 }}>Acao recomendada: {item.actionableMessage}</p> : null}
              </article>
            ))
          ) : (
            <p>Nenhum ASK enviado ainda.</p>
          )}
        </div>
      </section>
      <section aria-label="Timeline do chat" style={{ marginBottom: 20 }}>
        <h2>Timeline de resposta</h2>
        {isStealthVisualSuppressionActive ? (
          <p>Timeline detalhada temporariamente oculta em modo stealth. O streaming continua ativo em background.</p>
        ) : null}
        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {!isStealthVisualSuppressionActive && chatTimeline.length > 0 ? (
            chatTimeline.map((item) => (
              <article
                key={item.id}
                style={{
                  display: "grid",
                  gap: 6,
                  border: item.role === "assistant" ? "1px solid #9bb8ff" : "1px solid #d0d0d0",
                  background: item.role === "assistant" ? "#f7f9ff" : "#fafafa",
                  borderRadius: 8,
                  padding: 12,
                  maxWidth: 860
                }}
              >
                <strong>
                  {item.role === "assistant" ? "Assistente" : "Usuario"} | {item.createdAtIso}
                </strong>
                <span>Request ID: {item.requestId}</span>
                <span>Status: {item.status}</span>
                {item.errorCode ? <span>Codigo: {item.errorCode}</span> : null}
                <span>Screenshots vinculadas: {item.linkedScreenshotIds.length}</span>
                <p style={{ margin: 0, whiteSpace: "pre-wrap" }}>
                  {item.content || (item.role === "assistant" ? "Aguardando stream..." : "")}
                </p>
                {item.errorMessage ? <p style={{ margin: 0 }}>Erro: {item.errorMessage}</p> : null}
                {item.actionableMessage ? <p style={{ margin: 0 }}>Acao recomendada: {item.actionableMessage}</p> : null}
              </article>
            ))
          ) : (
            <p>{isStealthVisualSuppressionActive ? "Conteudo da timeline suprimido." : "Nenhuma mensagem na timeline ainda."}</p>
          )}
        </div>
      </section>
      <section aria-label="Proximos passos tecnicos">
        <h2>Audio input manager</h2>
        <p>{audioPermissionStatus}</p>
        <p>{audioDevicesStatus}</p>
        <p>
          Prioridade de compatibilidade: {isWindowsHost ? "Windows detectado" : "Host nao-Windows"}
        </p>
        {isWindowsHost ? (
          <p>
            Dica Windows: se o microfone nao aparecer, habilite o acesso em Configuracoes &gt;
            Privacidade e seguranca &gt; Microfone.
          </p>
        ) : null}
        <div style={{ display: "grid", gap: 8, maxWidth: 620 }}>
          <label>
            Dispositivo de entrada preferido
            <select
              value={selectedAudioInputDeviceId}
              onChange={(event) => setSelectedAudioInputDeviceId(event.target.value)}
              style={{ marginLeft: 8 }}
            >
              {audioInputDevices.length > 0 ? (
                audioInputDevices.map((device) => (
                  <option key={device.deviceId} value={device.deviceId}>
                    {device.label}
                  </option>
                ))
              ) : (
                <option value="">Nenhum dispositivo detectado</option>
              )}
            </select>
          </label>
        </div>
        <div style={{ marginTop: 10 }}>
          <button type="button" onClick={() => void requestMicrophonePermission()} style={{ marginRight: 8 }}>
            Solicitar permissao de microfone
          </button>
          <button type="button" onClick={() => void loadAudioInputDevices()} style={{ marginRight: 8 }}>
            Recarregar dispositivos
          </button>
          <button type="button" onClick={() => void testSelectedMicrophone()}>
            Testar dispositivo selecionado
          </button>
        </div>
      </section>
      <section aria-label="Audio capture manager" style={{ marginBottom: 20 }}>
        <h2>Audio capture manager</h2>
        <p>{audioCaptureStatus}</p>
        {audioCaptureHint ? <p>Acao recomendada: {audioCaptureHint}</p> : null}
        <p>{vadStatus}</p>
        <p>{audioDedupeStatus}</p>
        <p>
          Modo automatico: {isAutoRecordingEnabled ? "Ativo" : "Inativo"} | Intervalo: {autoRecordIntervalSec}s
        </p>
        <div style={{ display: "grid", gap: 8, maxWidth: 420 }}>
          <label>
            Intervalo automatico (10-20s)
            <input
              type="number"
              min={10}
              max={20}
              value={autoRecordIntervalSec}
              onChange={(event) => setAutoRecordIntervalSec(Number(event.target.value || 10))}
              style={{ marginLeft: 8 }}
            />
          </label>
          <label>
            Limiar VAD RMS (0.005-0.05)
            <input
              type="number"
              min={0.005}
              max={0.05}
              step={0.001}
              value={vadThresholdRms}
              onChange={(event) => setVadThresholdRms(Number(event.target.value || 0.015))}
              style={{ marginLeft: 8 }}
            />
          </label>
          <label>
            Janela deslizante VAD (2-8)
            <input
              type="number"
              min={2}
              max={8}
              value={vadWindowSize}
              onChange={(event) => setVadWindowSize(Number(event.target.value || 4))}
              style={{ marginLeft: 8 }}
            />
          </label>
        </div>
        <div style={{ marginTop: 10 }}>
          <button type="button" onClick={() => void handleManualRecordToggle()} style={{ marginRight: 8 }}>
            {isManualRecording ? "Parar gravacao manual" : "Gravar manual (Ctrl+D)"}
          </button>
          <button type="button" onClick={handleAutoRecordToggle} style={{ marginRight: 8 }}>
            {isAutoRecordingEnabled ? "Desativar auto" : "Ativar auto"}
          </button>
          <button type="button" onClick={() => void requestMicrophonePermission()}>
            Revalidar permissao
          </button>
        </div>
        <div style={{ display: "grid", gap: 10, marginTop: 12 }}>
          <p>
            Historico RMS: {vadRecentScores.length > 0 ? vadRecentScores.map((item) => item.toFixed(4)).join(" | ") : "sem amostras"}
          </p>
          {isStealthVisualSuppressionActive ? (
            <article
              style={{
                border: "1px solid #d0d0d0",
                borderRadius: 8,
                padding: 10,
                maxWidth: 760,
                background: "#f6f8fa"
              }}
            >
              <strong>Transcricao suprimida em modo stealth</strong>
              <p style={{ margin: "6px 0 0" }}>
                Chunks recebidos: {audioTranscripts.length} | Texto consolidado oculto.
              </p>
            </article>
          ) : (
            <article
              style={{
                border: "1px solid #d0d0d0",
                borderRadius: 8,
                padding: 10,
                maxWidth: 760,
                background: "#f6f8fa"
              }}
            >
              <strong>Transcricao consolidada (dedupe por overlap)</strong>
              <p style={{ margin: "6px 0 0", whiteSpace: "pre-wrap" }}>
                {audioConsolidatedText || "Nenhum texto consolidado ainda."}
              </p>
            </article>
          )}
          {!isStealthVisualSuppressionActive && audioTranscripts.length > 0 ? (
            audioTranscripts.map((item) => (
              <article
                key={item.id}
                style={{
                  border: "1px solid #d0d0d0",
                  borderRadius: 8,
                  padding: 10,
                  maxWidth: 760,
                  background: item.source === "auto" ? "#f8fafc" : "#fafafa"
                }}
              >
                <strong>{item.createdAtIso}</strong>
                <p style={{ margin: "6px 0" }}>
                  Origem: {item.source} | Final: {item.isFinal ? "sim" : "nao"}
                </p>
                <p style={{ margin: 0, whiteSpace: "pre-wrap" }}>{item.text}</p>
              </article>
            ))
          ) : (
            <p>
              {isStealthVisualSuppressionActive
                ? "Detalhes das transcricoes ocultos em modo stealth."
                : "Nenhuma transcricao de audio ainda."}
            </p>
          )}
        </div>
      </section>
      <section aria-label="Proximos passos tecnicos">
        <h2>Configuracoes</h2>
        <p>{settingsStatus}</p>
        <p>API key Gemini: {hasGeminiApiKey ? "Configurada" : "Nao configurada"}</p>
        <div style={{ display: "grid", gap: 8, maxWidth: 520, marginBottom: 16 }}>
          <label>
            Idioma
            <input value={language} onChange={(event) => setLanguage(event.target.value)} />
          </label>
          <label>
            Atalho captura de tela
            <input value={captureShortcut} onChange={(event) => setCaptureShortcut(event.target.value)} />
          </label>
          <label>
            Atalho push-to-talk
            <input
              value={pushToTalkShortcut}
              onChange={(event) => setPushToTalkShortcut(event.target.value)}
            />
          </label>
          <label>
            Atalho stealth
            <input
              value={toggleStealthShortcut}
              onChange={(event) => setToggleStealthShortcut(event.target.value)}
            />
          </label>
          <label>
            Nova API key Gemini
            <input
              type="password"
              value={geminiApiKey}
              onChange={(event) => setGeminiApiKey(event.target.value)}
            />
          </label>
        </div>
        <button type="button" onClick={handleSaveSettings} style={{ marginRight: 8 }}>
          Salvar configuracoes
        </button>
        <button type="button" onClick={handleResetSettings} style={{ marginRight: 8 }}>
          Resetar padrao
        </button>
        <button type="button" onClick={() => void loadSettings()}>
          Recarregar
        </button>
      </section>
      <section aria-label="Proximos passos tecnicos">
        <h2>Diagnostico</h2>
        <p>{diagnosticsStatus}</p>
        <p>Arquivo de log: {logFilePath || "Nao definido"}</p>
        <label>
          Nivel de log
          <select
            value={logLevel}
            onChange={(event) => void handleLogLevelChange(event.target.value as LogLevel)}
            style={{ marginLeft: 8 }}
          >
            <option value="debug">debug</option>
            <option value="info">info</option>
            <option value="warn">warn</option>
            <option value="error">error</option>
          </select>
        </label>
        <button type="button" onClick={() => void loadDiagnostics()} style={{ marginLeft: 8 }}>
          Atualizar logs
        </button>
        {isStealthVisualSuppressionActive ? (
          <p style={{ marginTop: 12 }}>Linhas de log suprimidas em modo stealth.</p>
        ) : (
          <pre
            aria-label="Linhas recentes de log"
            style={{
              marginTop: 12,
              maxHeight: 180,
              overflow: "auto",
              background: "#f3f3f3",
              padding: 10,
              borderRadius: 6
            }}
          >
            {recentLogs.length > 0 ? recentLogs.join("\n") : "Sem logs ainda."}
          </pre>
        )}
      </section>
      <section aria-label="Auto update seguro" style={{ marginBottom: 20 }}>
        <h2>Auto-update seguro</h2>
        <p>{autoUpdateStatus}</p>
        {autoUpdateLastMessage ? <p>Ultimo evento: {autoUpdateLastMessage}</p> : null}
        <p>
          Versao atual: {autoUpdateState?.currentVersion || "desconhecida"} | Status: {autoUpdateState?.status || "sem estado"}
        </p>
        <p>
          Ambiente: {autoUpdateState?.isPackaged ? "build instalada" : "dev/unpackaged"} | Rollback channel: {autoUpdateState?.rollbackChannel || "stable"}
        </p>
        {autoUpdateState?.lastError ? <p>Ultimo erro: {autoUpdateState.lastError}</p> : null}
        <div style={{ display: "grid", gap: 8, maxWidth: 720, marginBottom: 12 }}>
          <label>
            <input
              type="checkbox"
              checked={autoUpdateEnabled}
              onChange={(event) => setAutoUpdateEnabled(event.target.checked)}
            />
            Habilitar auto-update
          </label>
          <label>
            Feed HTTPS de updates
            <input
              type="url"
              value={autoUpdateFeedUrl}
              onChange={(event) => setAutoUpdateFeedUrl(event.target.value)}
              placeholder="https://updates.example.com/clone-perssua"
            />
          </label>
          <label>
            Canal
            <select
              value={autoUpdateChannel}
              onChange={(event) => setAutoUpdateChannel(event.target.value as AutoUpdateChannel)}
              style={{ marginLeft: 8 }}
            >
              <option value="stable">stable</option>
              <option value="beta">beta</option>
            </select>
          </label>
          <label>
            <input
              type="checkbox"
              checked={autoUpdateAllowPrerelease}
              onChange={(event) => setAutoUpdateAllowPrerelease(event.target.checked)}
            />
            Permitir prerelease
          </label>
        </div>
        <div style={{ marginBottom: 12 }}>
          <button type="button" onClick={() => void handleSaveAutoUpdateConfig()} style={{ marginRight: 8 }}>
            Salvar config update
          </button>
          <button type="button" onClick={() => void handleCheckForAutoUpdate()} style={{ marginRight: 8 }}>
            Verificar updates
          </button>
          <button
            type="button"
            onClick={() => void handleDownloadAutoUpdate()}
            style={{ marginRight: 8 }}
            disabled={!autoUpdateState?.canDownload}
          >
            Baixar update
          </button>
          <button
            type="button"
            onClick={() => void handleInstallAutoUpdate()}
            style={{ marginRight: 8 }}
            disabled={!autoUpdateState?.canInstall}
          >
            Aplicar no restart
          </button>
          <button
            type="button"
            onClick={() => void handleRollbackAutoUpdate()}
            style={{ marginRight: 8 }}
            disabled={!autoUpdateState?.canRollback}
          >
            Iniciar rollback
          </button>
          <button
            type="button"
            onClick={() => void handleConfirmAutoUpdateHealth()}
            disabled={!autoUpdateState?.requiresHealthConfirmation}
          >
            Confirmar saude da versao
          </button>
        </div>
        <p>
          Fluxo seguro: sem auto-download silencioso, sem install forcado e com health confirmation apos upgrade. O rollback usa downgrade controlado para o canal anterior.
        </p>
        {!isStealthVisualSuppressionActive ? (
          <pre
            aria-label="Estado do auto-update"
            style={{
              marginTop: 8,
              maxHeight: 220,
              overflow: "auto",
              background: "#f3f3f3",
              padding: 10,
              borderRadius: 6
            }}
          >
            {autoUpdateState ? JSON.stringify(autoUpdateState, null, 2) : "Sem snapshot de auto-update."}
          </pre>
        ) : (
          <p>Snapshot detalhado de auto-update suprimido em modo stealth.</p>
        )}
      </section>
      <section aria-label="Proximos passos tecnicos">
        <h2>Feature flags e ambiente</h2>
        <p>{featureStatus}</p>
        {isPrivacyLocalOnlyActive ? (
          <p>
            Privacidade local-only ativa: fallback cloud desativado e downloads de modelo por rede bloqueados no runtime.
          </p>
        ) : null}
        <div style={{ display: "grid", gap: 8, maxWidth: 520, marginBottom: 12 }}>
          <label>
            Provider mode
            <select
              value={providerMode}
              onChange={(event) => setProviderMode(event.target.value as ProviderMode)}
              style={{ marginLeft: 8 }}
            >
              <option value="cloud">cloud</option>
              <option value="local">local</option>
              <option value="hybrid">hybrid</option>
            </select>
          </label>
          <label>
            <input
              type="checkbox"
              checked={localProviderEnabled}
              onChange={(event) => setLocalProviderEnabled(event.target.checked)}
            />
            Local provider enabled
          </label>
          <label>
            <input
              type="checkbox"
              checked={forceLocalOnly}
              onChange={(event) => setForceLocalOnly(event.target.checked)}
            />
            Force local only
          </label>
          <label>
            Stealth hardening
            <select
              value={stealthHardening}
              onChange={(event) => setStealthHardening(event.target.value as StealthHardening)}
              style={{ marginLeft: 8 }}
            >
              <option value="off">off</option>
              <option value="safe">safe</option>
              <option value="strict">strict</option>
            </select>
          </label>
        </div>
        <button type="button" onClick={() => void handleSaveFeatureFlags()} style={{ marginRight: 8 }}>
          Salvar flags
        </button>
        <button type="button" onClick={() => void handleResetFeatureFlags()} style={{ marginRight: 8 }}>
          Resetar flags
        </button>
        <button type="button" onClick={() => void loadFeatureFlags()}>
          Recarregar flags
        </button>
        {isStealthVisualSuppressionActive ? (
          <p style={{ marginTop: 12 }}>Detalhes de flags e origem suprimidos em modo stealth.</p>
        ) : (
          <>
            <pre
              aria-label="Flags efetivas"
              style={{
                marginTop: 12,
                maxHeight: 180,
                overflow: "auto",
                background: "#f3f3f3",
                padding: 10,
                borderRadius: 6
              }}
            >
              {effectiveFlags ? JSON.stringify(effectiveFlags, null, 2) : "Sem flags carregadas."}
            </pre>
            <pre
              aria-label="Origem das flags"
              style={{
                marginTop: 12,
                maxHeight: 180,
                overflow: "auto",
                background: "#f9f9f9",
                padding: 10,
                borderRadius: 6
              }}
            >
              {featureSourceText || "Sem metadados de origem."}
            </pre>
          </>
        )}
        <p>{envStatus}</p>
        <button type="button" onClick={() => void loadEnvironment()}>
          Recarregar ambiente
        </button>
        {isStealthVisualSuppressionActive ? (
          <p style={{ marginTop: 12 }}>Snapshot de ambiente suprimido em modo stealth.</p>
        ) : (
          <pre
            aria-label="Snapshot de ambiente"
            style={{
              marginTop: 8,
              maxHeight: 180,
              overflow: "auto",
              background: "#f3f3f3",
              padding: 10,
              borderRadius: 6
            }}
          >
            {envSnapshotText || "Sem snapshot"}
          </pre>
        )}
      </section>
      <section aria-label="Matriz de validacao stealth" style={{ marginBottom: 20 }}>
        <h2>Matriz Zoom/Meet/Teams</h2>
        <p>
          Validacoes concluidas: {validationCompletedCount}/{MEETING_VALIDATION_SCENARIOS.length}. Esta etapa exige execucao manual nas plataformas reais.
        </p>
        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {MEETING_VALIDATION_SCENARIOS.map((scenario) => (
            <article
              key={scenario.id}
              style={{
                border: "1px solid #d0d0d0",
                borderRadius: 8,
                padding: 12,
                maxWidth: 860,
                background: "#fafafa"
              }}
            >
              <strong>
                {scenario.platform} | {scenario.shareMode}
              </strong>
              <p style={{ margin: "6px 0" }}>{scenario.expectedBehavior}</p>
              <label style={{ display: "block", marginBottom: 8 }}>
                Resultado
                <select
                  value={meetingValidationResults[scenario.id] || "pending"}
                  onChange={(event) =>
                    handleMeetingValidationResultChange(
                      scenario.id,
                      event.target.value as "pending" | "pass" | "risk" | "fail"
                    )
                  }
                  style={{ marginLeft: 8 }}
                >
                  <option value="pending">pending</option>
                  <option value="pass">pass</option>
                  <option value="risk">risk</option>
                  <option value="fail">fail</option>
                </select>
              </label>
              <label style={{ display: "grid", gap: 6 }}>
                Observacao
                <input
                  value={meetingValidationNotes[scenario.id] || ""}
                  onChange={(event) => handleMeetingValidationNoteChange(scenario.id, event.target.value)}
                  placeholder="Registrar evidencias, comportamento observado ou fallback necessario"
                />
              </label>
            </article>
          ))}
        </div>
      </section>
      <section aria-label="Checklist de self-check stealth" style={{ marginBottom: 20 }}>
        <h2>Self-check pre-apresentacao</h2>
        <p>
          Itens concluidos: {completedSelfChecks}/{STEALTH_SELF_CHECKS.length}
        </p>
        <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
          {STEALTH_SELF_CHECKS.map((item) => (
            <label
              key={item.id}
              style={{
                display: "grid",
                gap: 4,
                border: "1px solid #d0d0d0",
                borderRadius: 8,
                padding: 12,
                maxWidth: 860,
                background: selfCheckState[item.id] ? "#f0fff4" : "#fff"
              }}
            >
              <span>
                <input
                  type="checkbox"
                  checked={Boolean(selfCheckState[item.id])}
                  onChange={() => handleSelfCheckToggle(item.id)}
                  style={{ marginRight: 8 }}
                />
                {item.label}
              </span>
              <small>{item.guidance}</small>
            </label>
          ))}
        </div>
        <p style={{ marginTop: 12 }}>
          Pronto para call: {completedSelfChecks === STEALTH_SELF_CHECKS.length ? "sim" : "nao"}
        </p>
      </section>
      <section aria-label="Proximos passos tecnicos">
        <h2>Proximos passos</h2>
        <ul>
          <li>Expandir handlers IPC para captura real de screenshot e audio.</li>
          <li>Adicionar criptografia forte obrigatoria de segredos em todas as plataformas.</li>
          <li>Adicionar logs estruturados por correlacao de sessao/request.</li>
        </ul>
      </section>
    </main>
  );
}
