// Generated by GitHub Copilot
import { useEffect, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import type {
  ChatStreamEvent,
  LogLevel,
  ScreenshotQueueItem,
  StealthStateChangedEvent,
} from "@clone-perssua/shared-types";

// ─── Constantes ─────────────────────────────────────────────────────────────

const DEFAULT_SCREENSHOT_PROMPT = `Analise cuidadosamente tudo o que está visível nesta tela e responda de forma extremamente objetiva e direta.

REGRAS DE RESPOSTA:
- Se for uma questão de múltipla escolha: responda apenas a letra correta e uma justificativa em 1 linha.
- Se for um problema de código/algoritmo (LeetCode, HackerRank etc.): forneça a solução em código com complexidade otimizada e explique em 1-2 linhas.
- Se for uma pergunta discursiva: responda em no máximo 3 linhas, indo direto ao ponto.
- Se for um formulário, interface ou tela qualquer: descreva o que vê e sugira a ação mais útil.
- Nunca enrole. Seja cirúrgico. O usuário precisa da resposta agora.
- Responda sempre no idioma da questão apresentada na tela.`;

// ─── Types ───────────────────────────────────────────────────────────────────

interface ChatMessage {
  id: string;
  requestId: string;
  role: "user" | "assistant";
  content: string;
  createdAtIso: string;
  status: "pending" | "streaming" | "completed" | "error";
  errorCode?: string;
  actionableMessage?: string;
  retryable?: boolean;
  linkedScreenshotIds: string[];
}

type SettingsTab = "microphone" | "api" | "resources" | "shortcuts" | "logs";

// ─── Design tokens (dark theme) ─────────────────────────────────────────────

const C = {
  bg: "#0f0f0f",
  surface: "#1a1a1a",
  surface2: "#242424",
  border: "#2e2e2e",
  accent: "#6366f1",
  text: "#e5e5e5",
  textMuted: "#888",
  textDim: "#555",
  error: "#ef4444",
  success: "#22c55e",
} as const;

// ─── Style helpers ───────────────────────────────────────────────────────────

function iconBtn(active?: boolean, danger?: boolean): React.CSSProperties {
  return {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 6px",
    borderRadius: 6,
    color: danger ? C.error : active ? C.accent : C.textMuted,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  };
}

function inputStyle(): React.CSSProperties {
  return {
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 6,
    color: C.text,
    padding: "8px 10px",
    fontSize: 13,
    outline: "none",
    fontFamily: "inherit",
    width: "100%",
    boxSizing: "border-box",
  };
}

function primaryBtn(): React.CSSProperties {
  return {
    background: C.accent,
    border: "none",
    borderRadius: 6,
    color: "#fff",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    alignSelf: "flex-start",
  };
}

function secondaryBtn(): React.CSSProperties {
  return {
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: 6,
    color: C.text,
    padding: "8px 14px",
    cursor: "pointer",
    fontSize: 13,
    alignSelf: "flex-start",
  };
}

// ─── App component ───────────────────────────────────────────────────────────

export function App(): JSX.Element {
  const sessionId = useRef(globalThis.crypto.randomUUID()).current;

  // ── Chat state ──────────────────────────────────────────────────────────
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [askText, setAskText] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const [autoScroll, setAutoScroll] = useState(true);

  // ── Screenshot state ────────────────────────────────────────────────────
  const [screenshotQueue, setScreenshotQueue] = useState<ScreenshotQueueItem[]>([]);
  const [pendingScreenshotIds, setPendingScreenshotIds] = useState<string[]>([]);
  const [quickAnalysis, setQuickAnalysis] = useState(true);

  // ── Stealth + LLM + opacity ─────────────────────────────────────────────
  const [stealthEnabled, setStealthEnabled] = useState(false);
  const [hasLlm, setHasLlm] = useState(false);
  const [opacity, setOpacity] = useState(1);
  const [opacityOpen, setOpacityOpen] = useState(false);

  // ── Settings modal ──────────────────────────────────────────────────────
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settingsTab, setSettingsTab] = useState<SettingsTab>("api");

  // ── Settings — API ──────────────────────────────────────────────────────
  const [geminiApiKey, setGeminiApiKey] = useState("");
  const [hasGeminiApiKey, setHasGeminiApiKey] = useState(false);
  const [apiSaveStatus, setApiSaveStatus] = useState("");

  // ── Settings — Microphone ────────────────────────────────────────────────
  const [audioDevices, setAudioDevices] = useState<{ deviceId: string; label: string }[]>([]);
  const [selectedDeviceId, setSelectedDeviceId] = useState("");
  const [micStatus, setMicStatus] = useState("");

  // ── Settings — Resources ─────────────────────────────────────────────────
  const [selectToPrompt, setSelectToPrompt] = useState(false);

  // ── Settings — Shortcuts ─────────────────────────────────────────────────
  const [captureShortcut, setCaptureShortcut] = useState("Ctrl+E");
  const [pushToTalkShortcut, setPushToTalkShortcut] = useState("Ctrl+D");
  const [stealthShortcut, setStealthShortcut] = useState("Ctrl+B");
  const [shortcutSaveStatus, setShortcutSaveStatus] = useState("");

  // ── Settings — Logs ──────────────────────────────────────────────────────
  const [recentLogs, setRecentLogs] = useState<string[]>([]);
  const [logLevel, setLogLevel] = useState<LogLevel>("info");

  // ── Audio recording ──────────────────────────────────────────────────────
  const [isRecording, setIsRecording] = useState(false);
  const activeStreamRef = useRef<MediaStream | null>(null);
  const activeRecorderRef = useRef<MediaRecorder | null>(null);

  // ── Init ────────────────────────────────────────────────────────────────

  useEffect(() => {
    void loadSettings();
    void loadDiagnostics();
    void loadScreenshotQueue();

    const unsubQ = window.desktopApi.onScreenshotQueueUpdated((p) => {
      setScreenshotQueue(p.items);
    });
    const unsubChat = window.desktopApi.onChatStreamEvent(handleChatStreamEvent);
    const unsubStealth = window.desktopApi.onStealthStateChanged(handleStealthStateChanged);

    return () => {
      unsubQ();
      unsubChat();
      unsubStealth();
      stopRecording();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-scroll to latest message
  useEffect(() => {
    if (autoScroll && chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages, autoScroll]);

  // Select-to-prompt: Ctrl+C with selected text
  useEffect(() => {
    if (!selectToPrompt) return;
    const onKey = (e: globalThis.KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "c") {
        const sel = globalThis.window.getSelection()?.toString().trim();
        if (sel && sel.length > 2) {
          setAskText(`Analise o seguinte trecho e forneça insights: "${sel}"`);
        }
      }
    };
    globalThis.addEventListener("keydown", onKey);
    return () => globalThis.removeEventListener("keydown", onKey);
  }, [selectToPrompt]);

  // Close opacity popover when clicking outside
  useEffect(() => {
    if (!opacityOpen) return;
    const onDown = () => setOpacityOpen(false);
    // Small delay so the button click that opened it doesn't immediately close it
    const timer = globalThis.setTimeout(() => {
      globalThis.addEventListener("mousedown", onDown, { once: true });
    }, 50);
    return () => {
      globalThis.clearTimeout(timer);
      globalThis.removeEventListener("mousedown", onDown);
    };
  }, [opacityOpen]);

  // ── IPC loaders ─────────────────────────────────────────────────────────

  async function loadSettings(): Promise<void> {
    try {
      const r = await window.desktopApi.getSettings();
      setSelectedDeviceId(r.settings.selectedAudioInputDeviceId || "");
      setCaptureShortcut(r.settings.shortcuts.captureScreen);
      setPushToTalkShortcut(r.settings.shortcuts.pushToTalk);
      setStealthShortcut(r.settings.shortcuts.toggleStealth);
      setHasGeminiApiKey(r.settings.hasGeminiApiKey);
      setHasLlm(r.settings.hasGeminiApiKey);
    } catch { /* silent */ }
  }

  async function loadDiagnostics(): Promise<void> {
    try {
      const r = await window.desktopApi.getDiagnostics();
      setLogLevel(r.logLevel);
      setRecentLogs(r.recentLines);
    } catch { /* silent */ }
  }

  async function loadScreenshotQueue(): Promise<void> {
    try {
      const r = await window.desktopApi.getScreenshotQueue();
      setScreenshotQueue(r.items);
    } catch { /* silent */ }
  }

  async function loadAudioDevices(): Promise<void> {
    try {
      const stream = await globalThis.navigator.mediaDevices.getUserMedia({ audio: true });
      stream.getTracks().forEach((t) => t.stop());
      const devices = await globalThis.navigator.mediaDevices.enumerateDevices();
      const inputs = devices
        .filter((d) => d.kind === "audioinput")
        .map((d, i) => ({ deviceId: d.deviceId, label: d.label || `Microfone ${i + 1}` }));
      setAudioDevices(inputs);
      if (inputs.length > 0 && !inputs.some((d) => d.deviceId === selectedDeviceId)) {
        setSelectedDeviceId(inputs[0].deviceId);
      }
      setMicStatus(`${inputs.length} dispositivo(s) encontrado(s).`);
    } catch (e) {
      setMicStatus(`Permissão negada: ${e instanceof Error ? e.message : "erro"}`);
    }
  }

  // ── IPC event handlers ───────────────────────────────────────────────────

  function handleStealthStateChanged(p: StealthStateChangedEvent): void {
    setStealthEnabled(p.enabled);
    // Sync slider with the actual opacity the main process used
    if (p.enabled && typeof p.opacity === "number") {
      setOpacity(p.opacity);
    } else if (!p.enabled) {
      setOpacityOpen(false);
    }
  }

  function handleChatStreamEvent(payload: ChatStreamEvent): void {
    setChatMessages((current) => {
      const idx = current.findIndex(
        (m) => m.requestId === payload.requestId && m.role === "assistant"
      );
      if (idx === -1) {
        return [
          ...current,
          {
            id: `${payload.requestId}-assistant`,
            requestId: payload.requestId,
            role: "assistant",
            content: payload.fullText || payload.deltaText || "",
            createdAtIso: payload.createdAtIso,
            status: payload.status === "completed" ? "completed" : payload.status === "error" ? "error" : "streaming",
            errorCode: payload.errorCode,
            actionableMessage: payload.actionableMessage,
            retryable: payload.retryable,
            linkedScreenshotIds: [],
          },
        ];
      }
      return current.map((m, i) =>
        i !== idx
          ? m
          : {
              ...m,
              content: payload.fullText || m.content,
              status:
                payload.status === "completed"
                  ? "completed"
                  : payload.status === "error"
                  ? "error"
                  : "streaming",
              errorCode: payload.errorCode,
              actionableMessage: payload.actionableMessage,
              retryable: payload.retryable,
            }
      );
    });
    if (payload.status === "completed" || payload.status === "error") {
      setIsSubmitting(false);
    }
  }

  // ── Screenshot ────────────────────────────────────────────────────────────

  async function handleCapture(): Promise<void> {
    try {
      const r = await window.desktopApi.captureScreenshot({ source: "full" });
      setScreenshotQueue((q) =>
        [r, ...q.filter((x) => x.captureId !== r.captureId)].slice(0, 10)
      );
      if (quickAnalysis) {
        await submitAsk(DEFAULT_SCREENSHOT_PROMPT, [r.captureId]);
      } else {
        setPendingScreenshotIds((ids) => [...ids, r.captureId]);
        setAskText(DEFAULT_SCREENSHOT_PROMPT);
      }
    } catch { /* silent */ }
  }

  function removeScreenshot(captureId: string): void {
    setPendingScreenshotIds((ids) => ids.filter((id) => id !== captureId));
  }

  // ── Audio recording ──────────────────────────────────────────────────────

  async function toggleRecording(): Promise<void> {
    if (isRecording) {
      stopRecording();
      return;
    }
    try {
      const constraint: MediaTrackConstraints | boolean = selectedDeviceId
        ? { deviceId: { exact: selectedDeviceId } }
        : true;
      const stream = await globalThis.navigator.mediaDevices.getUserMedia({ audio: constraint });
      activeStreamRef.current = stream;
      const recorder = new MediaRecorder(stream, { mimeType: "audio/webm" });
      activeRecorderRef.current = recorder;
      const chunks: BlobPart[] = [];
      recorder.ondataavailable = (e) => {
        if (e.data?.size > 0) chunks.push(e.data);
      };
      recorder.onstop = async () => {
        stream.getTracks().forEach((t) => t.stop());
        activeStreamRef.current = null;
        if (!chunks.length) return;
        const blob = new Blob(chunks, { type: "audio/webm" });
        const buf = await blob.arrayBuffer();
        const bytes = new Uint8Array(buf);
        let bin = "";
        for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
        const b64 = globalThis.btoa(bin);
        try {
          const t = await window.desktopApi.transcribeAudioChunk({ sessionId, chunkBase64: b64 });
          if (t.text.trim()) {
            setAskText((prev) => (prev ? `${prev} ${t.text}` : t.text));
          }
        } catch { /* silent */ }
        setIsRecording(false);
        activeRecorderRef.current = null;
      };
      recorder.start();
      setIsRecording(true);
      globalThis.setTimeout(() => {
        if (recorder.state !== "inactive") recorder.stop();
      }, 8000);
    } catch {
      setIsRecording(false);
    }
  }

  function stopRecording(): void {
    if (activeRecorderRef.current && activeRecorderRef.current.state !== "inactive") {
      activeRecorderRef.current.stop();
    }
    if (activeStreamRef.current) {
      activeStreamRef.current.getTracks().forEach((t) => t.stop());
      activeStreamRef.current = null;
    }
    setIsRecording(false);
  }

  // ── Submit ASK ────────────────────────────────────────────────────────────

  async function submitAsk(text: string, screenshotIds: string[]): Promise<void> {
    const ask = text.trim();
    if (!ask) return;
    setIsSubmitting(true);
    const tempId = globalThis.crypto.randomUUID();
    const userMsg: ChatMessage = {
      id: tempId,
      requestId: "",
      role: "user",
      content: ask,
      createdAtIso: new Date().toISOString(),
      status: "completed",
      linkedScreenshotIds: [...screenshotIds],
    };
    setChatMessages((m) => [...m, userMsg]);
    try {
      const r = await window.desktopApi.submitAsk({
        sessionId,
        ask,
        screenshotIds: screenshotIds.length > 0 ? screenshotIds : undefined,
        presetId: "ui-analysis",
      });
      // Patch requestId on the user message
      setChatMessages((m) =>
        m.map((msg) => (msg.id === tempId ? { ...msg, requestId: r.requestId } : msg))
      );
      setPendingScreenshotIds([]);
      setAskText("");
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Erro ao enviar.";
      setChatMessages((m) => [
        ...m,
        {
          id: globalThis.crypto.randomUUID(),
          requestId: "",
          role: "assistant",
          content: "",
          createdAtIso: new Date().toISOString(),
          status: "error",
          actionableMessage: msg,
          linkedScreenshotIds: [],
        },
      ]);
      setIsSubmitting(false);
    }
  }

  async function handleSendAsk(): Promise<void> {
    await submitAsk(askText, pendingScreenshotIds);
  }

  function handleAskKeyDown(e: KeyboardEvent<HTMLTextAreaElement>): void {
    if (e.ctrlKey && e.key === "Enter") {
      e.preventDefault();
      void handleSendAsk();
    }
  }

  // ── Settings: save ───────────────────────────────────────────────────────

  async function handleSaveApi(): Promise<void> {
    try {
      const r = await window.desktopApi.saveSettings({
        geminiApiKey: geminiApiKey.trim() || undefined,
      });
      setHasGeminiApiKey(r.settings.hasGeminiApiKey);
      setHasLlm(r.settings.hasGeminiApiKey);
      setGeminiApiKey("");
      setApiSaveStatus("API key salva com sucesso.");
    } catch (e) {
      setApiSaveStatus(`Erro: ${e instanceof Error ? e.message : "desconhecido"}`);
    }
  }

  async function handleSaveShortcuts(): Promise<void> {
    try {
      await window.desktopApi.saveSettings({
        shortcuts: {
          captureScreen: captureShortcut,
          pushToTalk: pushToTalkShortcut,
          toggleStealth: stealthShortcut,
        },
      });
      setShortcutSaveStatus("Atalhos salvos.");
    } catch (e) {
      setShortcutSaveStatus(`Erro: ${e instanceof Error ? e.message : "desconhecido"}`);
    }
  }

  async function handleSaveMic(): Promise<void> {
    try {
      await window.desktopApi.saveSettings({
        selectedAudioInputDeviceId: selectedDeviceId || null,
      });
      setMicStatus("Microfone salvo.");
    } catch { /* silent */ }
  }

  async function handleToggleStealth(): Promise<void> {
    try {
      const r = await window.desktopApi.setStealthMode({ enabled: !stealthEnabled });
      setStealthEnabled(r.enabled);
      // Sync opacity slider with the value the main process applied
      if (r.enabled && typeof r.opacity === "number") {
        setOpacity(r.opacity);
      } else if (!r.enabled) {
        setOpacityOpen(false);
      }
    } catch { /* silent */ }
  }

  async function handleSetOpacity(value: number): Promise<void> {
    setOpacity(value);
    try {
      await window.desktopApi.setWindowOpacity(value);
    } catch { /* silent */ }
  }

  function handleQuit(): void {
    void window.desktopApi.quitApp();
  }

  function handleMinimize(): void {
    void window.desktopApi.minimizeWindow();
  }

  // ── Derived ──────────────────────────────────────────────────────────────

  const pendingItems = screenshotQueue.filter((q) =>
    pendingScreenshotIds.includes(q.captureId)
  );

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <>
      {/* ── Main window ──────────────────────────────────────────────── */}
      <div
        style={{
          width: "100vw",
          height: "100vh",
          background: C.bg,
          color: C.text,
          display: "flex",
          flexDirection: "column",
          fontFamily: "'Segoe UI', system-ui, sans-serif",
          fontSize: 13,
          overflow: "hidden",
          userSelect: "none",
        }}
      >
        {/* ── Topbar / drag region ──────────────────────────────────── */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            padding: "6px 10px",
            background: C.surface,
            borderBottom: `1px solid ${C.border}`,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            WebkitAppRegion: "drag",
          } as React.CSSProperties}
        >
          {/* Drag handle + logo */}
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <span
              style={{
                fontSize: 14,
                cursor: "grab",
                color: C.textDim,
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                WebkitAppRegion: "drag",
              } as React.CSSProperties}
            >
              ⠿
            </span>
            <span
              style={{
                fontWeight: 700,
                fontSize: 13,
                letterSpacing: "0.05em",
                color: C.accent,
              }}
            >
              AIGA
            </span>
          </div>

          {/* Icon bar */}
          <div
            style={{
              display: "flex",
              gap: 2,
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              WebkitAppRegion: "no-drag",
            } as React.CSSProperties}
          >
            {/* LLM status */}
            <button
              type="button"
              title={hasLlm ? "LLM configurado" : "Nenhuma LLM configurada — clique para configurar"}
              style={iconBtn()}
              onClick={() => {
                setSettingsTab("api");
                setSettingsOpen(true);
              }}
            >
              <span
                style={{
                  fontSize: 10,
                  fontWeight: 700,
                  color: hasLlm ? C.success : C.error,
                  border: `1px solid ${hasLlm ? C.success : C.error}`,
                  borderRadius: 4,
                  padding: "1px 4px",
                  lineHeight: 1.4,
                }}
              >
                LLM
              </span>
            </button>

            {/* Screenshot */}
            <button
              type="button"
              title={`Capturar tela (${captureShortcut})`}
              style={iconBtn()}
              onClick={() => void handleCapture()}
            >
              📷
            </button>

            {/* Microphone */}
            <button
              type="button"
              title={
                isRecording
                  ? "Parar gravação"
                  : `Gravar áudio (${pushToTalkShortcut})`
              }
              style={iconBtn(isRecording, isRecording)}
              onClick={() => void toggleRecording()}
            >
              🎙️
            </button>

            {/* Translation shortcut */}
            <button
              type="button"
              title="Preencher campo com pedido de tradução"
              style={iconBtn()}
              onClick={() => setAskText("Traduza para português: ")}
            >
              🌐
            </button>

            {/* Stealth toggle */}
            <button
              type="button"
              title={
                stealthEnabled
                  ? `Stealth ativo (${stealthShortcut}) — clique para desativar`
                  : `Stealth inativo (${stealthShortcut}) — clique para ativar`
              }
              style={iconBtn(stealthEnabled)}
              onClick={() => void handleToggleStealth()}
            >
              {stealthEnabled ? "👁️" : "🙈"}
            </button>

            {/* Opacity control — visible only in stealth mode */}
            {stealthEnabled && (
            <div style={{ position: "relative" }}>
              <button
                type="button"
                title={`Opacidade: ${Math.round(opacity * 100)}%`}
                style={{ ...iconBtn(opacityOpen), fontSize: 14 }}
                onClick={() => setOpacityOpen((o) => !o)}
              >
                ◑
              </button>
              {opacityOpen && (
                <div
                  onMouseDown={(e) => e.stopPropagation()}
                  style={{
                    position: "absolute",
                    top: "calc(100% + 6px)",
                    right: 0,
                    background: C.surface,
                    border: `1px solid ${C.border}`,
                    borderRadius: 8,
                    padding: "10px 12px",
                    width: 160,
                    zIndex: 200,
                    display: "flex",
                    flexDirection: "column",
                    gap: 6,
                  }}
                >
                  <span style={{ fontSize: 11, color: C.textMuted, marginBottom: 2 }}>
                    Opacidade — {Math.round(opacity * 100)}%
                  </span>
                  <input
                    type="range"
                    min={5}
                    max={100}
                    step={5}
                    value={Math.round(opacity * 100)}
                    onChange={(e) => void handleSetOpacity(Number(e.target.value) / 100)}
                    style={{ width: "100%", accentColor: C.accent, cursor: "pointer" }}
                  />
                  <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: C.textDim }}>
                    <span>5%</span>
                    <span>100%</span>
                  </div>
                </div>
              )}
            </div>
            )}

            {/* Settings */}
            <button
              type="button"
              title="Configurações"
              style={iconBtn()}
              onClick={() => setSettingsOpen(true)}
            >
              ⚙️
            </button>

            {/* Separator */}
            <span style={{ width: 1, background: C.border, alignSelf: "stretch", margin: "4px 2px" }} />

            {/* Minimize */}
            <button
              type="button"
              title="Minimizar"
              style={iconBtn()}
              onClick={handleMinimize}
            >
              ─
            </button>

            {/* Quit */}
            <button
              type="button"
              title="Fechar AIGA"
              style={iconBtn(false, true)}
              onClick={handleQuit}
            >
              ⏻
            </button>
          </div>
        </div>

        {/* ── Chat timeline ─────────────────────────────────────────── */}
        <div
          style={{
            flex: 1,
            overflowY: "auto",
            padding: "10px 12px",
            display: "flex",
            flexDirection: "column",
            gap: 8,
          }}
          onScroll={(e) => {
            const el = e.currentTarget;
            const atBottom =
              el.scrollHeight - el.scrollTop - el.clientHeight < 40;
            setAutoScroll(atBottom);
          }}
        >
          {chatMessages.length === 0 && (
            <div
              style={{
                flex: 1,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: C.textDim,
                flexDirection: "column",
                gap: 6,
              }}
            >
              <span style={{ fontSize: 28 }}>🤖</span>
              <span style={{ fontSize: 12 }}>
                Faça uma pergunta ou capture a tela
              </span>
            </div>
          )}

          {chatMessages.map((msg) => (
            <div
              key={msg.id}
              style={{
                alignSelf: msg.role === "user" ? "flex-end" : "flex-start",
                maxWidth: "88%",
                background:
                  msg.role === "user" ? C.accent : C.surface2,
                borderRadius:
                  msg.role === "user"
                    ? "12px 12px 2px 12px"
                    : "12px 12px 12px 2px",
                padding: "8px 12px",
                lineHeight: 1.55,
                fontSize: 13,
                userSelect: "text",
              }}
            >
              {msg.status === "error" ? (
                <span style={{ color: C.error }}>
                  {msg.actionableMessage || "Erro desconhecido."}
                </span>
              ) : (
                <>
                  <span style={{ whiteSpace: "pre-wrap", color: C.text }}>
                    {msg.content ||
                      (msg.status === "pending" || msg.status === "streaming"
                        ? ""
                        : "")}
                  </span>
                  {(msg.status === "pending" ||
                    msg.status === "streaming") && (
                    <span
                      style={{ color: C.textMuted, marginLeft: 2 }}
                    >
                      ▌
                    </span>
                  )}
                </>
              )}
            </div>
          ))}
          <div ref={chatEndRef} />
        </div>

        {/* ── Screenshot thumbnails ─────────────────────────────────── */}
        {pendingItems.length > 0 && (
          <div
            style={{
              display: "flex",
              gap: 6,
              padding: "6px 12px",
              borderTop: `1px solid ${C.border}`,
              flexWrap: "wrap",
            }}
          >
            {pendingItems.map((item) => (
              <div
                key={item.captureId}
                style={{ position: "relative", width: 56, height: 40 }}
              >
                <div
                  style={{
                    width: 56,
                    height: 40,
                    background: C.surface2,
                    border: `1px solid ${C.border}`,
                    borderRadius: 4,
                    overflow: "hidden",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: 18,
                  }}
                >
                  🖼️
                </div>
                <button
                  type="button"
                  aria-label="Remover screenshot"
                  onClick={() => removeScreenshot(item.captureId)}
                  style={{
                    position: "absolute",
                    top: -6,
                    right: -6,
                    background: C.error,
                    border: "none",
                    borderRadius: "50%",
                    color: "#fff",
                    width: 16,
                    height: 16,
                    fontSize: 10,
                    cursor: "pointer",
                    padding: 0,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  ✕
                </button>
              </div>
            ))}
          </div>
        )}

        {/* ── Input bar ─────────────────────────────────────────────── */}
        <div
          style={{
            padding: "8px 12px",
            borderTop: `1px solid ${C.border}`,
            display: "flex",
            gap: 8,
            alignItems: "flex-end",
            background: C.surface,
          }}
        >
          <textarea
            value={askText}
            onChange={(e) => setAskText(e.target.value)}
            onKeyDown={handleAskKeyDown}
            placeholder="Digite sua pergunta… (Ctrl+Enter para enviar)"
            rows={2}
            style={{
              flex: 1,
              background: C.surface2,
              border: `1px solid ${C.border}`,
              borderRadius: 8,
              color: C.text,
              padding: "8px 10px",
              fontSize: 13,
              resize: "none",
              outline: "none",
              fontFamily: "inherit",
              lineHeight: 1.5,
              userSelect: "text",
            }}
          />
          <button
            type="button"
            disabled={isSubmitting || !askText.trim()}
            onClick={() => void handleSendAsk()}
            style={{
              background:
                isSubmitting || !askText.trim() ? C.surface2 : C.accent,
              border: "none",
              borderRadius: 8,
              color:
                isSubmitting || !askText.trim() ? C.textMuted : "#fff",
              padding: "10px 14px",
              cursor:
                isSubmitting || !askText.trim() ? "not-allowed" : "pointer",
              fontSize: 18,
              lineHeight: 1,
            }}
          >
            {isSubmitting ? "⟳" : "↑"}
          </button>
        </div>
      </div>

      {/* ── Settings modal ────────────────────────────────────────────── */}
      {settingsOpen && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Configurações"
          onClick={(e) => {
            if (e.target === e.currentTarget) setSettingsOpen(false);
          }}
          style={{
            position: "fixed",
            inset: 0,
            background: "rgba(0,0,0,0.72)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
          }}
        >
          <div
            style={{
              background: C.surface,
              border: `1px solid ${C.border}`,
              borderRadius: 12,
              width: 520,
              maxWidth: "95vw",
              maxHeight: "82vh",
              display: "flex",
              flexDirection: "column",
              overflow: "hidden",
            }}
          >
            {/* Modal header */}
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "14px 18px",
                borderBottom: `1px solid ${C.border}`,
              }}
            >
              <span style={{ fontWeight: 700, fontSize: 14, color: C.text }}>
                Configurações — AIGA
              </span>
              <button
                type="button"
                aria-label="Fechar configurações"
                style={iconBtn()}
                onClick={() => setSettingsOpen(false)}
              >
                ✕
              </button>
            </div>

            {/* Tab bar */}
            <div
              style={{
                display: "flex",
                borderBottom: `1px solid ${C.border}`,
                overflowX: "auto",
              }}
            >
              {(
                [
                  ["api", "API"],
                  ["microphone", "Microfone"],
                  ["resources", "Recursos"],
                  ["shortcuts", "Atalhos"],
                  ["logs", "Logs"],
                ] as [SettingsTab, string][]
              ).map(([id, label]) => (
                <button
                  key={id}
                  type="button"
                  onClick={() => setSettingsTab(id)}
                  style={{
                    background: "none",
                    border: "none",
                    borderBottom:
                      settingsTab === id
                        ? `2px solid ${C.accent}`
                        : "2px solid transparent",
                    color: settingsTab === id ? C.accent : C.textMuted,
                    padding: "10px 16px",
                    cursor: "pointer",
                    fontSize: 12,
                    fontWeight: settingsTab === id ? 600 : 400,
                    whiteSpace: "nowrap",
                  }}
                >
                  {label}
                </button>
              ))}
            </div>

            {/* Tab content */}
            <div
              style={{ flex: 1, overflowY: "auto", padding: "18px" }}
            >
              {/* ── API tab ────────────────────────────────────────── */}
              {settingsTab === "api" && (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: 14,
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <span
                      style={{
                        fontSize: 11,
                        color: hasGeminiApiKey ? C.success : C.error,
                        fontWeight: 600,
                      }}
                    >
                      {hasGeminiApiKey
                        ? "✓ API Key configurada"
                        : "✗ API Key não configurada"}
                    </span>
                  </div>
                  <label style={{ color: C.textMuted, fontSize: 12 }}>
                    Gemini API Key
                  </label>
                  <input
                    type="password"
                    placeholder="AIza…"
                    value={geminiApiKey}
                    onChange={(e) => setGeminiApiKey(e.target.value)}
                    style={inputStyle()}
                  />
                  <p style={{ color: C.textMuted, fontSize: 11, margin: 0 }}>
                    Obtenha gratuitamente em{" "}
                    <span style={{ color: C.accent }}>
                      aistudio.google.com/apikey
                    </span>
                  </p>
                  <p style={{ color: C.textMuted, fontSize: 11, margin: 0 }}>
                    Modelo ativo:{" "}
                    <code style={{ color: C.text }}>gemini-2.5-flash</code>{" "}
                    (configurável via{" "}
                    <code style={{ color: C.text }}>GEMINI_MODEL</code> no{" "}
                    <code style={{ color: C.text }}>.env</code>)
                  </p>
                  <button
                    type="button"
                    disabled={!geminiApiKey.trim()}
                    style={{
                      ...primaryBtn(),
                      opacity: geminiApiKey.trim() ? 1 : 0.5,
                      cursor: geminiApiKey.trim() ? "pointer" : "not-allowed",
                    }}
                    onClick={() => void handleSaveApi()}
                  >
                    Salvar
                  </button>
                  {apiSaveStatus && (
                    <span style={{ color: C.success, fontSize: 12 }}>
                      {apiSaveStatus}
                    </span>
                  )}
                </div>
              )}

              {/* ── Microphone tab ──────────────────────────────────── */}
              {settingsTab === "microphone" && (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: 14,
                  }}
                >
                  <button
                    type="button"
                    style={secondaryBtn()}
                    onClick={() => void loadAudioDevices()}
                  >
                    Solicitar permissão e listar dispositivos
                  </button>
                  {micStatus && (
                    <span style={{ color: C.textMuted, fontSize: 12 }}>
                      {micStatus}
                    </span>
                  )}
                  {audioDevices.length > 0 && (
                    <>
                      <label style={{ color: C.textMuted, fontSize: 12 }}>
                        Microfone ativo
                      </label>
                      <select
                        value={selectedDeviceId}
                        onChange={(e) => setSelectedDeviceId(e.target.value)}
                        style={inputStyle()}
                      >
                        {audioDevices.map((d) => (
                          <option key={d.deviceId} value={d.deviceId}>
                            {d.label}
                          </option>
                        ))}
                      </select>
                      <button
                        type="button"
                        style={primaryBtn()}
                        onClick={() => void handleSaveMic()}
                      >
                        Salvar microfone
                      </button>
                    </>
                  )}
                  <p style={{ color: C.textMuted, fontSize: 11, margin: 0 }}>
                    No Windows: Configurações → Privacidade e segurança →
                    Microfone
                  </p>
                </div>
              )}

              {/* ── Resources tab ───────────────────────────────────── */}
              {settingsTab === "resources" && (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: 20,
                  }}
                >
                  <ResourceToggle
                    label="Rolagem automática"
                    description="A conversa rola automaticamente para a resposta mais recente. Pausa ao rolar para cima e retoma ao voltar ao final."
                    value={autoScroll}
                    onChange={setAutoScroll}
                  />
                  <ResourceToggle
                    label="Selecionar para prompt"
                    description="Selecionar texto e pressionar Ctrl+C analisa automaticamente o conteúdo e preenche o campo de texto."
                    value={selectToPrompt}
                    onChange={setSelectToPrompt}
                  />
                  <ResourceToggle
                    label="Análise rápida de screenshots"
                    description="Ao capturar, envia imediatamente com prompt padrão otimizado. Desative para revisar o prompt antes de enviar."
                    value={quickAnalysis}
                    onChange={setQuickAnalysis}
                  />
                </div>
              )}

              {/* ── Shortcuts tab ───────────────────────────────────── */}
              {settingsTab === "shortcuts" && (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: 14,
                  }}
                >
                  {(
                    [
                      [
                        "Captura de tela",
                        captureShortcut,
                        setCaptureShortcut,
                      ],
                      [
                        "Push-to-talk (microfone)",
                        pushToTalkShortcut,
                        setPushToTalkShortcut,
                      ],
                      ["Toggle stealth", stealthShortcut, setStealthShortcut],
                    ] as [string, string, (v: string) => void][]
                  ).map(([label, value, setter]) => (
                    <div
                      key={label}
                      style={{
                        display: "flex",
                        flexDirection: "column",
                        gap: 4,
                      }}
                    >
                      <label style={{ color: C.textMuted, fontSize: 12 }}>
                        {label}
                      </label>
                      <input
                        type="text"
                        value={value}
                        onChange={(e) => setter(e.target.value)}
                        style={inputStyle()}
                      />
                    </div>
                  ))}
                  <button
                    type="button"
                    style={primaryBtn()}
                    onClick={() => void handleSaveShortcuts()}
                  >
                    Salvar atalhos
                  </button>
                  {shortcutSaveStatus && (
                    <span style={{ color: C.success, fontSize: 12 }}>
                      {shortcutSaveStatus}
                    </span>
                  )}
                  <p style={{ color: C.textMuted, fontSize: 11, margin: 0 }}>
                    Nota: atalhos globais são registrados pelo sistema. Reinicie
                    o app para aplicar mudanças.
                  </p>
                </div>
              )}

              {/* ── Logs tab ────────────────────────────────────────── */}
              {settingsTab === "logs" && (
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: 12,
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      gap: 8,
                      alignItems: "center",
                    }}
                  >
                    <label style={{ color: C.textMuted, fontSize: 12 }}>
                      Nível
                    </label>
                    <select
                      value={logLevel}
                      onChange={async (e) => {
                        const next = e.target.value as LogLevel;
                        setLogLevel(next);
                        try {
                          await window.desktopApi.setLogLevel({
                            level: next,
                          });
                          await loadDiagnostics();
                        } catch { /* silent */ }
                      }}
                      style={{ ...inputStyle(), width: "auto" }}
                    >
                      {(["debug", "info", "warn", "error"] as LogLevel[]).map(
                        (l) => (
                          <option key={l} value={l}>
                            {l}
                          </option>
                        )
                      )}
                    </select>
                    <button
                      type="button"
                      style={secondaryBtn()}
                      onClick={() => void loadDiagnostics()}
                    >
                      Atualizar
                    </button>
                  </div>
                  <div
                    style={{
                      background: C.bg,
                      border: `1px solid ${C.border}`,
                      borderRadius: 6,
                      padding: 10,
                      fontFamily: "monospace",
                      fontSize: 11,
                      color: C.textMuted,
                      maxHeight: 260,
                      overflowY: "auto",
                      userSelect: "text",
                      whiteSpace: "pre-wrap",
                      wordBreak: "break-all",
                    }}
                  >
                    {recentLogs.length === 0
                      ? "Nenhum log disponível."
                      : recentLogs.slice(-50).join("\n")}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ─── ResourceToggle sub-component ───────────────────────────────────────────

function ResourceToggle({
  label,
  description,
  value,
  onChange,
}: {
  label: string;
  description: string;
  value: boolean;
  onChange: (v: boolean) => void;
}): JSX.Element {
  return (
    <div style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
      <button
        type="button"
        role="switch"
        aria-checked={value}
        onClick={() => onChange(!value)}
        style={{
          flexShrink: 0,
          marginTop: 2,
          width: 36,
          height: 20,
          borderRadius: 10,
          background: value ? C.accent : C.surface2,
          border: `1px solid ${value ? C.accent : C.border}`,
          cursor: "pointer",
          position: "relative",
          transition: "background 0.2s",
          padding: 0,
        }}
      >
        <span
          style={{
            position: "absolute",
            top: 2,
            left: value ? 18 : 2,
            width: 14,
            height: 14,
            background: "#fff",
            borderRadius: "50%",
            transition: "left 0.2s",
            display: "block",
          }}
        />
      </button>
      <div>
        <div
          style={{ fontWeight: 600, fontSize: 13, color: C.text }}
        >
          {label}
        </div>
        <div
          style={{
            fontSize: 11,
            color: C.textMuted,
            marginTop: 2,
            lineHeight: 1.4,
          }}
        >
          {description}
        </div>
      </div>
    </div>
  );
}
