# Generated by GitHub Copilot
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$required = @("WIN_CSC_LINK", "WIN_CSC_KEY_PASSWORD")
$missing = @()

foreach ($name in $required) {
    if ([string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($name))) {
        $missing += $name
    }
}

if ($missing.Count -gt 0) {
    Write-Host "[publish-checklist] Missing signing env vars:" -ForegroundColor Red
    foreach ($m in $missing) {
        Write-Host " - $m" -ForegroundColor Red
    }
    exit 1
}

Write-Host "[publish-checklist] Signing env vars are configured." -ForegroundColor Green
Write-Host "[publish-checklist] Next: corepack pnpm pack:win; corepack pnpm dist:win" -ForegroundColor Cyan
