# Generated by GitHub Copilot
[CmdletBinding()]
param(
    [switch]$SkipTests
)

$ErrorActionPreference = "Stop"

function Invoke-Step {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][scriptblock]$Action
    )

    Write-Host "[beta-gates] $Name" -ForegroundColor Cyan
    & $Action
    if ($LASTEXITCODE -ne 0) {
        throw "Step failed: $Name"
    }
}

Invoke-Step -Name "typecheck" -Action { corepack pnpm -r typecheck }
Invoke-Step -Name "build" -Action { corepack pnpm -r build }

if (-not $SkipTests) {
    Invoke-Step -Name "test" -Action { corepack pnpm test }
    Invoke-Step -Name "test:e2e" -Action { corepack pnpm test:e2e }
}

Write-Host "[beta-gates] All rollout gates passed." -ForegroundColor Green
