# Generated by GitHub Copilot
[CmdletBinding()]
param(
    [string]$Date = (Get-Date -Format "yyyy-MM-dd")
)

$ErrorActionPreference = "Stop"

$triageDir = Join-Path $PSScriptRoot "..\..\beta\triage"
$triageDir = [System.IO.Path]::GetFullPath($triageDir)
if (-not (Test-Path $triageDir)) {
    New-Item -Path $triageDir -ItemType Directory | Out-Null
}

$target = Join-Path $triageDir "$Date.md"
if (Test-Path $target) {
    Write-Host "[triage] File already exists: $target" -ForegroundColor Yellow
    exit 0
}

$template = @"
# Daily Triage Log - $Date

## New Issues
| Issue | Title | Severity | Reporter | Repro | Status |
|---|---|---|---|---|---|

## Critical (P1)
- none

## High (P2)
- none

## Resolved Today
- none

## Health Snapshot
- Active pilots:
- Stability avg:
- Open issues (P1/P2/P3):

## Actions Before EOD
- 
"@

Set-Content -Path $target -Value $template -Encoding UTF8
Write-Host "[triage] Created: $target" -ForegroundColor Green
